/**
 * agentAssignments — single source of truth for task→agent mapping.
 *
 * Reads `data/agent-assignments.json` (committed to repo, generated by
 * scripts/generate-agent-assignments.ts) and exposes a synchronous
 * lookup helper. Zero DB query, zero runtime resolution — assignments
 * are deterministic at build time.
 *
 * If a task's assignment is missing, callers fall back to whatever
 * hardcoded agent_id the task template already had (graceful degrade).
 *
 * 2026-05-08 (CJ direction): all 498 task slots get a unique B+ agent
 * (≥400 char persona) from mos_db's qualified pool of 3,010 agents.
 */
import assignmentsData from "../../../data/agent-assignments.json" with { type: "json" };
import { normalizeTaskId } from "../../platform/core/tierCompat";

type Role =
  | "lead"
  | "imageDirector"
  | "strategist"
  | "specialty"
  | "replyWriter"
  | "timingAdvisor"
  | "followupWriter"
  | "compareTable"
  | "trendTimingAdvisor"
  | "legalAssistant";

interface AssignmentsFile {
  generatedAt: string;
  poolSize: number;
  slotCount: number;
  uniqueAgents: number;
  avgThickness: number;
  minThickness: number;
  assignments: Record<string, Partial<Record<Role, number>>>;
}

const data = assignmentsData as AssignmentsFile;

/** Returns the assigned agent_id for a (taskId, role) pair, or null
 *  if no assignment exists (caller should fall back to hardcoded). */
export function getAssignedAgent(taskId: string, role: Role): number | null {
  // 100s→99s rename: JSON keys were renamed to the new ids. Normalize the
  // incoming taskId so a legacy "fb-100-…" still resolves. Idempotent.
  return data.assignments[normalizeTaskId(taskId)]?.[role] ?? null;
}

/** Resolve an agent_id with fallback chain: JSON assignment > hardcoded > null */
export function resolveAgentId(
  taskId: string,
  role: Role,
  hardcodedFallback: number | null | undefined,
): number | null {
  return getAssignedAgent(taskId, role) ?? hardcodedFallback ?? null;
}

/** Stats for /admin endpoints */
export function getAssignmentStats() {
  return {
    poolSize: data.poolSize,
    slotCount: data.slotCount,
    uniqueAgents: data.uniqueAgents,
    avgThickness: data.avgThickness,
    minThickness: data.minThickness,
    generatedAt: data.generatedAt,
  };
}
