/**
 * theme_apply tool — returns the active Boardroom theme (colors + typography).
 *
 * Called by other deliverable tools (boardroom_pdf, boardroom_pptx) to stamp
 * a consistent visual identity on every output. For v1 we have a single
 * static SoWork theme; future versions can swap themes per brand.
 */

import { registerTool } from "./index";

export interface BoardroomTheme {
  name: string;
  colors: {
    background: string;
    surface: string;
    primary: string;
    accent: string;
    text: string;
    textMuted: string;
    border: string;
  };
  fonts: {
    heading: string;
    body: string;
    mono: string;
  };
  footerText: string;
}

export const DEFAULT_THEME: BoardroomTheme = {
  name: "SoWork Boardroom",
  colors: {
    background: "#FAFAF9",
    surface: "#FFFFFF",
    primary: "#1A1A18",
    accent: "#0A6EFA",
    text: "#1A1A18",
    textMuted: "#6B6A66",
    border: "#E4E3E1",
  },
  fonts: {
    heading: "Helvetica-Bold",
    body: "Helvetica",
    mono: "Courier",
  },
  footerText: "Generated by SoWork Marketing OS",
};

export function getTheme(_brandId?: number | string | null): BoardroomTheme {
  // v1: static theme. v2+ will read brand's custom theme from DB.
  return DEFAULT_THEME;
}

registerTool({
  name: "theme_apply",
  description:
    "Return the active visual theme (colors, fonts, footer text) for boardroom deliverables. Call this once before invoking boardroom_pdf/boardroom_pptx if you want to preview the theme; otherwise the deliverable tools load it automatically.",
  parameters: {
    type: "object",
    properties: {},
  },
  async execute(_args, ctx) {
    const theme = getTheme(ctx.brand?.id);
    return [
      `Theme: ${theme.name}`,
      "",
      "Colors:",
      `  background  ${theme.colors.background}`,
      `  surface     ${theme.colors.surface}`,
      `  primary     ${theme.colors.primary}`,
      `  accent      ${theme.colors.accent}`,
      `  text        ${theme.colors.text}`,
      `  textMuted   ${theme.colors.textMuted}`,
      `  border      ${theme.colors.border}`,
      "",
      "Fonts:",
      `  heading     ${theme.fonts.heading}`,
      `  body        ${theme.fonts.body}`,
      `  mono        ${theme.fonts.mono}`,
      "",
      `Footer: ${theme.footerText}`,
    ].join("\n");
  },
});
