/**
 * 100s tier — campaign-level deliverables with REAL-TIME DATA (2026-05-06).
 *
 * Distinct from 60s: 100s tasks output WHOLE CAMPAIGNS / SERIES / MONTHLY
 * CALENDARS, not single posts. Each task ships 8-30 assets per run, with
 * scout-fetched REAL-TIME DATA (upcoming festivals for calendars, current
 * trending events for trend rewrites, industry news for thought leadership).
 *
 * 60s = 1 post production package (5 variants of 1 caption + extras).
 * 100s = 1 campaign production package (N posts + real-time scout data).
 *
 * Many 100s tasks correspond to existing legacy squads (fb-monthly-calendar,
 * fb-event-launch-kit, fb-crisis-comms, etc.) — these squads already had
 * full agent rosters and methodology; 100s tasks reuse the SHAPE of those
 * deliverables but ship via the orchestra runner for unified UX.
 *
 * Wall budget 100s. Scout stage runs upfront to inject real data into
 * caption_writer prompts.
 */
import type { FBTaskTemplate, OrchestraConfig } from "./quickTaskFB";

const TONE_100 = `
語氣要求：自然、有 hook、不官腔。
本任務輸出 campaign 級別內容，每篇/每節都要扣回主敘事弧。
**即時資料**：scout 階段已抓回即時節慶 / 時事 / 趨勢資料，請扣回這些真實 context，不要寫得通用。`;

// ─── FB 100s (5 tasks) ────────────────────────────────────────────────
export const FB_99S_TASKS: FBTaskTemplate[] = [
  {
    // 2026-05-18 (CJ「30天行事曆結果很不理想，要結構化行事曆+指定配比」):
    // single structured 30-day calendar (NOT a strategy essay / weekly
    // chunk). Fixed content mix per CJ + coursera FB-marketing structure.
    id: "fb-99-30day-calendar",
    tier: "99s", postType: "feed",
    label: "FB 30 天內容行事曆",
    description: "結構化 30 天行事曆：4 理念WHY / 4 產品 / 2 節慶 / 2 UGC見證 / 2 國際權威",
    agent_id: 224089, // Kevin Tan — Social Media Strategist eCommerce MY (1147 char)
    skill_slug: "content-calendar",
    primary_question: "本月主推 / 主題？（可寫多個產品與目標族群）",
    primary_input: { key: "monthly_focus", placeholder: "例：母親節檔｜主推 A 產品(忙碌媽媽) + B 產品(小資女)｜品牌理念：讓每個人都能輕鬆做出好內容", type: "textarea" },
    inputs: [
      { key: "monthly_focus", label: "本月主題 + 產品 + 目標族群", type: "textarea", required: true },
    ],
    // 2026-05-18 (CJ「分配不同 agent 處理不同類型內容，比較快」): each
    // pillar group is generated by its OWN parallel agent ({label} = the
    // pillar). The orchestra then merges all groups into one 30-day
    // calendar (calendarMerge). ~5× faster, no 502.
    systemPrompt: `你是 FB 內容行事曆策略師。本次**只負責「{label}」這一個內容支柱**，產出該支柱的貼文，**只輸出嚴格 JSON 陣列**。

各支柱該產出的則數（只做你被指派的「{label}」那組）：
- 「理念WHY」→ 4 則：用黃金圈 Why 講品牌理念/創業初衷，不談產品功能
- 「產品」→ 4 則：每則只針對「一個目標族群」溝通「一個 USP」並帶到「一個產品」
- 「節慶」→ 2 則：搭配本月實際接近的節慶/檔期
- 「UGC見證」→ 2 則：使用者見證，每則見證「一個產品」、溝通「一個 USP」
- 「權威觀點」→ 2 則：引用國際權威/研究/名人觀點，印證品牌創業理念（理念，非產品）

每則物件欄位：
{"day": <1-30 整數>, "pillar": "{label}", "audience": "<對誰說；理念/權威可寫『全體受眾』>", "usp": "<單一賣點；理念/權威留空字串>", "product": "<帶到的產品；理念/權威留空字串>", "hook": "<前 2 行鉤子 ≤30字>", "message": "<核心訊息 60-110字>", "format": "圖文|短影音|輪播|直播|純文字", "cta": "<行動呼籲 ≤15字>"}

規則：
- 第一個字元就是 [，最後一個字元就是 ]。不要 markdown 圍欄、不要說明文字。
- 只產「{label}」這組、嚴格照上面對應則數；pillar 欄位一律填「{label}」。
- day 給 1-30 的合理值（系統會把所有支柱合併後重新分散排序）。
- 內容扣回用戶輸入的主題/產品/族群；事實不得捏造。
- 每一則都必守：鎖定「一個族群在一個具體情境」說話（用品牌脈絡的主受眾/痛點，audience 要具體不是「全體」除非理念/權威）、整則只打「一個」最強賣點（usp 單一、不要功能清單）、message 要鋪陳到一個可被認出的「Moment of Truth 決定性瞬間」（讀者那一刻確認「這就是我要的」）。遮掉品牌名仍適用競品＝太通用，重寫。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1600,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    // 2026-05-18 (CJ「促銷月曆也超時，分不同 agent 比較快」): replaces
    // the heavy fb-monthly-calendar-product-promo squad with the same
    // fast parallel-by-pillar engine, tuned for multi-product promo.
    id: "fb-99-monthly-calendar-promo",
    tier: "99s", postType: "feed",
    label: "FB 30 天促銷月曆（多商品）",
    description: "結構化促銷月曆：6 產品促銷 / 3 急迫限時 / 2 節慶檔期 / 2 UGC見證 / 1 理念",
    agent_id: 224089,
    skill_slug: "content-calendar",
    primary_question: "本檔促銷主題 + 要推哪些商品（各對誰、各一賣點）？",
    primary_input: { key: "monthly_focus", placeholder: "例：週年慶｜A 產品(忙碌媽媽/省時) + B 產品(小資女/CP值) + C 產品(電商主/多平台)｜檔期 5/20-5/31", type: "textarea" },
    inputs: [
      { key: "monthly_focus", label: "促銷主題 + 商品 + 族群 + 檔期", type: "textarea", required: true },
    ],
    systemPrompt: `你是 FB 促銷月曆策略師。本次**只負責「{label}」這一個支柱**，**只輸出嚴格 JSON 陣列**。

各支柱該產出的則數（只做被指派的「{label}」那組）：
- 「產品促銷」→ 6 則：每則只推「一個商品」、對「一個族群」、講「一個賣點」+ offer
- 「急迫限時」→ 3 則：限時/倒數/最後機會/數量有限，營造急迫但不浮誇
- 「節慶檔期」→ 2 則：扣本檔接近的節慶/檔期
- 「UGC見證」→ 2 則：使用者見證，每則見證「一個商品」溝通「一個賣點」
- 「理念WHY」→ 1 則：促銷檔中的品牌信任錨，講理念不講折扣

【優惠數字｜絕對禁止捏造（最高優先）】
折扣 %、價格、名額（前 N 位）、期限/截止日、贈品、會員權益等具體優惠條件，**只能用「用戶輸入裡明確提供」的**。
- 用戶沒給 → **絕對不可自行編造數字**（不可寫「85 折」「前 100 位」「再 24 小時」等）。改用無數字的急迫框架（例：「檔期內」「名額有限」「把握這次」），或用佔位符「[請填入優惠：例如 X 折／前 N 名／截止日]」讓用戶補。
- 用戶有給 → 逐字沿用，不得放大或更動。

每則物件欄位：
{"day": <1-30 整數>, "pillar": "{label}", "audience": "<對誰說>", "usp": "<單一賣點/offer；理念留空>", "product": "<帶到的商品；理念留空>", "hook": "<前 2 行鉤子 ≤30字>", "message": "<核心訊息 60-110字>", "format": "圖文|短影音|輪播|直播|純文字", "cta": "<行動呼籲 ≤15字>"}

規則：第一個字元就是 [、最後一個就是 ]，不要圍欄/說明；只產「{label}」這組、照對應則數；pillar 一律「{label}」；事實不得捏造。
每一則都必守：鎖定「一個族群在一個具體情境」說話（audience 具體、用品牌主受眾/痛點）、整則只打「一個」最強賣點/offer（usp 單一、非清單）、message 鋪陳到一個可被認出的「Moment of Truth 決定性瞬間」（讀者那刻確認「這就是我要的」）。遮掉品牌名仍適用競品＝太通用，重寫。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1800,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    // 2026-05-18 (CJ「carousel 一個貼文還是只出現一張圖 → 搬到 99s，
    // 真的出 5 張卡圖」): moved from fb-60-carousel-5. A carousel is ONE
    // post made of 5 cards, each with its own image — needs the 99s
    // budget to render 5 card images + copy.
    id: "fb-99-carousel-5",
    tier: "99s", postType: "carousel",
    label: "FB Carousel 5 卡輪播",
    description: "Hook→Build→Turn→Payoff→CTA 敘事弧 + 5 張卡（每卡獨立文案＋專屬圖）",
    agent_id: 180148, // David Chen | Social Media Manager
    skill_slug: "social-copy",
    primary_question: "輪播主題是什麼？",
    primary_input: { key: "topic", placeholder: "輪播 5 卡要傳達的主題", type: "textarea" },
    inputs: [
      { key: "topic", label: "輪播主題", type: "textarea", required: true },
    ],
    systemPrompt: `產出 FB Carousel 5 卡（敘事弧：Hook → Build → Turn → Payoff → CTA）。
caption 是輪播主貼文文（150-250 字 tease 整組要看完）。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1400,
    outputDefaults: { platform: "facebook", post_type: "carousel" },
  },
  {
    // 2026-05-18 (CJ「FB 3 篇連載超時很久，要移到 99s」): moved from
    // fb-60-serial-3 — strategist + 3 episodes + 3 images + per-episode
    // extras is too heavy for the 60s budget (hit the 5-min stale guard).
    id: "fb-99-serial-3",
    tier: "99s", postType: "feed",
    label: "FB 3 篇連載敘事",
    description: "Nelson Chen 設計 3 集弧 + Reed Lee 寫 3 篇有勾連（每集配圖＋產製配套）",
    agent_id: 220752, // Reed Lee
    skill_slug: "social-copy",
    primary_question: "想連載講什麼故事？",
    primary_input: { key: "story_topic", placeholder: "例：客戶轉型 / 團隊成長 / 產品研發歷程", type: "textarea" },
    inputs: [
      { key: "story_topic", label: "連載主題", type: "textarea", required: true },
    ],
    systemPrompt: `產出 FB 3 篇連載其中 1 篇（200-350 字）。
本次你寫的是「{label}」集（第 1 集 / 第 2 集 / 第 3 集）。
- 第 1 集：埋懸念 + 預告下集
- 第 2 集：轉折 + 加深
- 第 3 集：揭曉 / 收束 + 整體 CTA
篇與篇要有勾連（每篇結尾留 1 句鉤子帶到下一篇）。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 900,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    // 2026-05-18 (CJ「也要移動 viral/testimonial」): strategist + specialty
    // (Compare Editor) too heavy for 60s — same 502 risk as trend-rewrite.
    id: "fb-99-viral-rewrite",
    tier: "99s", postType: "feed",
    label: "FB 爆款改寫",
    description: "Kevin Liu 找原爆款結構 + Siyu Li 改寫品牌版 + 對照表（scout 抓同類爆款）",
    agent_id: 60048, // Siyu Li
    skill_slug: "fb-copywriting",
    primary_question: "貼上爆款原文（或連結），我們會分析結構並改寫成你的版本",
    primary_input: { key: "viral_source", placeholder: "貼上原爆款貼文 / 連結 / 主題", type: "textarea" },
    inputs: [
      { key: "viral_source", label: "爆款原文 / 連結 / 主題", type: "textarea", required: true },
      { key: "brand_angle", label: "我方品牌角度（可選）", type: "textarea", required: false },
    ],
    systemPrompt: `產出 FB 爆款改寫文（200-400 字）。
**核心原則**：保留原爆款的「敘事結構 / hook 機制 / 情緒節奏」，但內容換成品牌自己的事。不是抄文字，是學結構。
不要直接複製原文用詞。注意法規 / 抄襲分寸。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    id: "fb-99-testimonial-rewrite",
    tier: "99s", postType: "feed",
    label: "FB 客戶見證改寫文",
    description: "Kurt Chen 找見證結構 + Yawen Ma 改寫敘事 + Jason Evans 法務檢核",
    agent_id: 60026, // Kevin Chiang
    skill_slug: "fb-copywriting",
    primary_question: "貼上原始客戶見證 / 訪談 / 評價",
    primary_input: { key: "testimonial_source", placeholder: "客戶原話、訪談逐字、評論截圖文字", type: "textarea" },
    inputs: [
      { key: "testimonial_source", label: "客戶見證原文", type: "textarea", required: true },
      { key: "consent_status", label: "已取得發布同意？", type: "text", required: false, placeholder: "yes / 匿名化 / 待確認" },
    ],
    systemPrompt: `產出 FB 客戶見證改寫文（200-350 字）。
**核心原則**：保留客戶情感真實感，重組敘事讓重點凸顯。
**法務 / 倫理**：
- 預設匿名化（除非明確標 "yes"），姓名只留首字
- 不要編造客戶沒說過的話
- 數字 / 成效宣稱必須有原文支持
- 結尾不要寫成廣告口吻${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    // 2026-05-18 (CJ「FB 時事改寫文 502」): moved from fb-60-trend-rewrite.
    // strategist (Mark Davis) + specialty (Trend Researcher) + scout +
    // captions ran synchronously past nginx's 60s upstream timeout → 502.
    id: "fb-99-trend-rewrite",
    tier: "99s", postType: "feed",
    label: "FB 時事改寫文",
    description: "Mark Davis 評估時事關聯 + Dale Yu 寫品牌切入點 + 時效性檢核（scout 抓即時時事）",
    agent_id: 220755, // Dale Yu
    skill_slug: "social-copy",
    primary_question: "想搭哪個時事？",
    primary_input: { key: "trend_topic", placeholder: "例：奧運 / AI 新聞 / 季節節日", type: "textarea" },
    inputs: [
      { key: "trend_topic", label: "時事主題", type: "textarea", required: true },
      { key: "brand_angle", label: "品牌切入角度（可選）", type: "textarea", required: false },
    ],
    systemPrompt: `產出 FB 時事改寫文（150-300 字）。
**核心原則**：時事是 hook，品牌是 punchline。前 1/3 講時事，後 2/3 拉回品牌。
**禁忌**：不要假裝你是事件當事人；不要在敏感事件（災難、政治、人命）上消費；不要寫成蹭熱度。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 900,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    id: "fb-99-14day-countdown",
    tier: "99s", postType: "feed",
    label: "FB 14 天倒數活動",
    description: "14 天倒數 + 每天獨立 hook + 中段轉折 + 高潮收束 + scout 抓節慶/時事",
    agent_id: 224116, // Hoàng Thị Mai — Email & CRM Strategist eCommerce VN (1251 char)
    skill_slug: "fb-countdown-series",
    primary_question: "活動名稱 + 主要 hook？",
    primary_input: { key: "event_name", placeholder: "例：母親節限時優惠 / 新品上市", type: "text" },
    inputs: [
      { key: "event_name", label: "活動名稱", type: "text", required: true },
      { key: "key_offer", label: "主要 hook / 優惠", type: "textarea", required: true },
    ],
    systemPrompt: `產出 FB 14 天倒數系列其中 1 篇（80-130 字）。
本次你寫的是「{label}」這天。注意三幕結構：
- Day 14-10: 預熱、埋懸念
- Day 9-5: 揭曉細節、加溫
- Day 4-1: 緊迫感、最後機會
${TONE_100}`,
    preferredModel: "qwen", maxTokens: 700,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    id: "fb-99-launch-toolkit",
    tier: "99s", postType: "event",
    label: "FB 完整 Launch Toolkit (8 篇)",
    description: "預告 ×3 / 當日 / 即時 ×2 / 事後 / 跨平台 IG 改寫 + scout 抓節慶/時事",
    agent_id: 60014, // Cindy Mo | Social Media Marketing (F&B)
    skill_slug: "fb-copywriting",
    primary_question: "活動名稱 + 日期 + 重點？",
    primary_input: { key: "event_name", placeholder: "例：5/20 線上發表會", type: "text" },
    inputs: [
      { key: "event_name", label: "活動名稱", type: "text", required: true },
      { key: "event_when", label: "日期 / 時間", type: "text", required: true },
      { key: "event_why", label: "為什麼參加 / 重點", type: "textarea", required: true },
    ],
    systemPrompt: `本次你負責「{label}」。
- 若「{label}」=「活動總覽」：產出一頁式**活動總覽文件**（Markdown 分段）：① 活動目標與受眾 ② 整體時程與節奏（哪幾天發哪一篇）③ 8 篇貼文各自的主題與角色一覽 ④ KPI 與成效追蹤建議 ⑤ 風險/備案。這是計畫文件，不是貼文，不受字數限制；事實不得捏造，缺的用「[請補充：…]」標出。
- 否則（預告 1/2/3、當日、即時 1/2、事後、IG 跨平台改寫）：產出該篇 FB 貼文（150-300 字），扣回整個 launch arc，前一篇結尾鉤子帶到下一篇。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "facebook", post_type: "event" },
  },
  {
    id: "fb-99-livestream-9seg",
    tier: "99s", postType: "feed",
    label: "FB 直播完整 9 段配套",
    description: "預告 + 開場 + 5 爆點 + 結尾 + 精華回顧 + reel 剪輯指南",
    agent_id: 224154, // Dewi Rahayu — Social Media Strategist Health ID (1135 char)
    skill_slug: "social-copy",
    primary_question: "直播主題 + 重點？",
    primary_input: { key: "live_topic", placeholder: "Q&A / 新品試用 / 直播試吃", type: "text" },
    inputs: [
      { key: "live_topic", label: "直播主題", type: "text", required: true },
      { key: "key_points", label: "預計 3-5 個重點", type: "textarea", required: true },
    ],
    systemPrompt: `產出 FB 直播完整套組其中 1 段（80-200 字依段而異）。
本次你寫的是「{label}」（預告 / 開場宣告 / 爆點 1-5 / 結尾 / 精華回顧 / Reel 剪輯）。
${TONE_100}`,
    preferredModel: "qwen", maxTokens: 900,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    id: "fb-99-crisis-playbook",
    tier: "99s", postType: "comment",
    label: "FB 完整危機公關劇本",
    description: "偵測 + 第一份聲明 + 中期更新 ×3 + 後期 follow-up + 內部 talking points",
    agent_id: 222204, // Chen Jing-Yi — Senior Press Release Writer (1040 char)
    skill_slug: "crisis-communication",
    primary_question: "事件 / 危機內容？",
    primary_input: { key: "incident", placeholder: "完整描述事件 + 已知事實", type: "textarea" },
    inputs: [
      { key: "incident", label: "事件內容", type: "textarea", required: true },
      { key: "facts", label: "已知事實 / 已處理項", type: "textarea", required: false },
      { key: "commitment", label: "可承諾行動", type: "textarea", required: false },
    ],
    systemPrompt: `產出 FB 危機公關完整劇本其中 1 段（200-400 字）。
本次你寫的是「{label}」（偵測警示 / 第一份聲明 / 24h 更新 / 48h 更新 / 72h 更新 / 1 週後 follow-up / 媒體 talking points）。
語氣專業有人味、不推託、扣回 Lagadec 4 段。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "facebook", post_type: "comment" },
  },
];

// ─── IG 100s (3 tasks) ────────────────────────────────────────────────
export const IG_99S_TASKS: FBTaskTemplate[] = [
  {
    id: "ig-99-30day-calendar",
    tier: "99s", postType: "feed",
    label: "IG 30 天內容月曆",
    description: "30 天 feed/reel/story 配比 + 每篇 hook + hashtag 策略 + 真實爆款參考",
    agent_id: 60008, // Fiona Hsieh | Social Media Marketing Strategist (Beauty)
    skill_slug: "instagram-strategy",
    primary_question: "本月主題？",
    primary_input: { key: "monthly_focus", placeholder: "本月主推", type: "textarea" },
    inputs: [{ key: "monthly_focus", label: "本月主題", type: "textarea", required: true }],
    systemPrompt: `產出 IG 30 天月曆其中 1 週（7 天大綱，每天 60-100 字）。
本次你寫的是「{label}」這週。標明每天類型（feed / reel / story / carousel）。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1400,
    outputDefaults: { platform: "instagram", post_type: "feed" },
  },
  {
    id: "ig-99-reel-series-6",
    tier: "99s", postType: "reel",
    label: "IG Reel 6 集系列",
    description: "Strategist 設計 6 集弧 + 每集完整腳本（hook + hold + payoff）+ 縮圖 brief",
    agent_id: 60033, // Yawen Yeh | E-commerce Short Video Scriptwriter
    skill_slug: "short-video-scriptwriter",
    primary_question: "6 集系列主題？",
    primary_input: { key: "series_topic", placeholder: "教學系列 / 故事系列", type: "textarea" },
    inputs: [{ key: "series_topic", label: "系列主題", type: "textarea", required: true }],
    systemPrompt: `產出 IG Reel 6 集系列其中 1 集（300-500 字腳本）。
本次你寫的是「{label}」。每集要有勾連，最後集收束。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "instagram", post_type: "reel" },
  },
  {
    id: "ig-99-account-reposition",
    tier: "99s", postType: "profile",
    label: "IG 帳號重新定位完整套組",
    description: "新 bio + 9 個 highlight 主題 + 9 篇 launch posts + visual direction",
    agent_id: 180141, // Rachel Chen | Social Media Strategy Director
    skill_slug: "instagram-strategy",
    primary_question: "想重新定位的方向？",
    primary_input: { key: "new_direction", placeholder: "想轉成什麼方向 / 受眾", type: "textarea" },
    inputs: [{ key: "new_direction", label: "新方向", type: "textarea", required: true }],
    systemPrompt: `產出 IG 帳號重新定位套組其中 1 部分。
本次你寫的是「{label}」（新 bio / Highlight 1-9 / Launch post 1-9）。
重新定位需要明確、一致、不能跟舊 IG 衝突。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "instagram", post_type: "profile" },
  },
];

// ─── YT 100s (3 tasks) ────────────────────────────────────────────────
export const YT_99S_TASKS: FBTaskTemplate[] = [
  {
    id: "yt-99-series-6ep",
    tier: "99s", postType: "video",
    label: "YT 6 集系列完整製作包",
    description: "6 集 title + description 800-1200 字 + 縮圖 brief 各 3 種 + community 配套",
    agent_id: 224005, // Pin-Chen Lin — YouTube Marketing Strategist 金融科技 (~1000 char)
    skill_slug: "youtube-content",
    primary_question: "6 集系列主題？",
    primary_input: { key: "series_topic", placeholder: "教學/故事/評測 系列主題", type: "textarea" },
    inputs: [{ key: "series_topic", label: "系列主題", type: "textarea", required: true }],
    systemPrompt: `產出 YT 6 集系列其中 1 集（title + description 600-1000 字）。
本次你寫的是「{label}」。每集 SEO 各自最佳化但跟系列扣連。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "youtube", post_type: "video" },
  },
  {
    id: "yt-99-quarterly-strategy",
    tier: "99s", postType: "video",
    label: "YT 季度頻道策略",
    description: "12 個 video title + 內容支柱 + community 月曆 + competitor 分析",
    agent_id: 224001, // Yun-Hsuan Chen — YouTube Marketing Strategist 服飾時尚 (~1019 char)
    skill_slug: "youtube-strategy",
    primary_question: "頻道方向 / 受眾？",
    primary_input: { key: "channel_focus", placeholder: "頻道主題與目標受眾", type: "textarea" },
    inputs: [{ key: "channel_focus", label: "頻道焦點", type: "textarea", required: true }],
    systemPrompt: `產出 YT 季度策略其中 1 部分（300-600 字）。
本次你寫的是「{label}」（內容支柱規劃 / 12 個影片 title / community 月曆 / competitor 分析 / 即時趨勢報告）。
${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1200,
    outputDefaults: { platform: "youtube", post_type: "video" },
  },
  {
    id: "yt-99-premiere-kit",
    tier: "99s", postType: "premiere",
    label: "YT Premiere 完整 kit",
    description: "預告影片 + 倒數 community 貼文 + 直播配套 + 精華剪輯指南",
    agent_id: 223995, // Pei-Hsuan Liu — YouTube Marketing Strategist 電商/DTC (1025 char)
    skill_slug: "shorts-scriptwriter",
    primary_question: "Premiere 主題？",
    primary_input: { key: "premiere_topic", placeholder: "首播主題", type: "textarea" },
    inputs: [{ key: "premiere_topic", label: "首播主題", type: "textarea", required: true }],
    systemPrompt: `產出 YT Premiere kit 其中 1 部分（150-400 字）。
本次你寫的是「{label}」（預告 trailer 腳本 / Community 倒數 ×5 / 直播配套 / 精華剪輯指南）。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "youtube", post_type: "premiere" },
  },
];

// ─── Multi-channel 100s (TT/LI/Email/PR/Brand/Research) ───────────────
export const MULTI_99S_TASKS: FBTaskTemplate[] = [
  {
    id: "tt-99-30day-foryou",
    tier: "99s", postType: "foryou",
    label: "TikTok 30 天 ForYou 配方",
    description: "30 天每天 1 支腳本 + trend 對應 + sound 建議 + scout 抓節慶/時事",
    agent_id: 27, skill_slug: "short-video-script", // Chloe Chen | Short Video Strategist (Beauty)
    primary_question: "本月想衝什麼方向？",
    primary_input: { key: "monthly_theme", placeholder: "教學 / 反差 / 開箱 為主", type: "textarea" },
    inputs: [{ key: "monthly_theme", label: "本月方向", type: "textarea", required: true }],
    systemPrompt: `產出 TikTok 30 天計畫其中 1 週（7 支短腳本，每支 100-150 字）。
本次你寫的是「{label}」這週。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1500,
    outputDefaults: { platform: "tiktok", post_type: "foryou" },
  },
  {
    id: "tt-99-trend-week",
    tier: "99s", postType: "foryou",
    label: "TikTok 1 週追熱點完整套組",
    description: "7 天每天 1 個 trend + 品牌 hook + 3 種 hook 變化 + sound 建議",
    agent_id: 220507, skill_slug: "short-video-script", // Pin-Yen Liu — Short-form Video Producer Beauty
    primary_question: "想搭哪類熱點？",
    primary_input: { key: "trend_focus", placeholder: "節日 / meme / 新聞", type: "textarea" },
    inputs: [{ key: "trend_focus", label: "熱點類型", type: "textarea", required: true }],
    systemPrompt: `產出 TikTok 追熱點 1 天的腳本（200-400 字）。
本次你寫的是「{label}」這天。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1000,
    outputDefaults: { platform: "tiktok", post_type: "foryou" },
  },
  {
    id: "li-99-30day-thought-leadership",
    tier: "99s", postType: "feed",
    label: "LI 30 天 Thought-Leadership 月曆",
    description: "30 天 = 10 觀點 / 10 案例 / 10 趨勢預測 + scout 抓即時節慶",
    agent_id: 222342, skill_slug: "linkedin-b2b", // Hung Ya-Wen | Social Media Strategist – B2B SaaS
    primary_question: "這個月想立什麼專業 image？",
    primary_input: { key: "expertise_area", placeholder: "AI / 領導力 / SaaS 等", type: "textarea" },
    inputs: [{ key: "expertise_area", label: "專業領域", type: "textarea", required: true }],
    systemPrompt: `產出 LI thought-leadership 月曆其中 1 週（5-7 篇大綱）。
本次你寫的是「{label}」這週。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "linkedin", post_type: "feed" },
  },
  {
    id: "li-99-newsletter-quarterly",
    tier: "99s", postType: "newsletter",
    label: "LI 季度 Newsletter 4 期",
    description: "季度 4 期 newsletter 完整內容 + 訂閱成長策略",
    agent_id: 60062, skill_slug: "linkedin-b2b", // Nathan Lu | Media Newsletter Copywriter
    primary_question: "newsletter 季度大主題？",
    primary_input: { key: "quarter_topic", placeholder: "本季想串什麼主題", type: "textarea" },
    inputs: [{ key: "quarter_topic", label: "季度主題", type: "textarea", required: true }],
    systemPrompt: `產出 LI quarterly newsletter 其中 1 期（500-800 字）。
本次你寫的是「{label}」（第 1 期 / 第 2 期 / 第 3 期 / 第 4 期）。期與期要連貫。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1200,
    outputDefaults: { platform: "linkedin", post_type: "newsletter" },
  },
  {
    id: "em-99-4week-nurture",
    tier: "99s", postType: "edm",
    label: "Email 4 週 Onboarding Nurture",
    description: "4 週 8-12 封 emails + 行為觸發分支 + scout 抓即時節慶",
    agent_id: 224161, skill_slug: "email-marketing", // Xenia Anggraini — Email & CRM Strategist Beauty ID (1229 char)
    primary_question: "新訂閱者最該知道什麼？",
    primary_input: { key: "value_prop", placeholder: "核心價值 + onboarding 目標", type: "textarea" },
    inputs: [{ key: "value_prop", label: "核心價值", type: "textarea", required: true }],
    systemPrompt: `產出 Email 4 週 nurture 其中 1 封（200-400 字）。
本次你寫的是「{label}」。每封要扣回核心價值，逐步深入。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1000,
    outputDefaults: { platform: "email", post_type: "edm" },
  },
  {
    id: "em-99-launch-sequence",
    tier: "99s", postType: "edm",
    label: "Email 產品上線完整自動化 Sequence",
    description: "預告 ×2 / 上線 / 提醒 ×2 / 最後機會 / 後續 follow-up = 7 封",
    agent_id: 60061, skill_slug: "email-marketing", // Yahan Tsai — Retail E-commerce Newsletter Copywriter
    primary_question: "產品名稱 + 賣點？",
    primary_input: { key: "product", placeholder: "產品名 + 主要賣點", type: "textarea" },
    inputs: [{ key: "product", label: "產品", type: "textarea", required: true }],
    systemPrompt: `產出 Email launch 序列其中 1 封（200-400 字）。
本次你寫的是「{label}」。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1000,
    outputDefaults: { platform: "email", post_type: "edm" },
  },
  {
    id: "pr-99-launch-toolkit",
    tier: "99s", postType: "press",
    label: "PR 完整 Launch 媒體 Toolkit",
    description: "新聞稿 + Q&A + 媒體聯絡話術 + 後續追蹤 + spokesperson talking points",
    agent_id: 223197, skill_slug: "pr-writing", // Yi-Wen Wu — PR Strategist B2B SaaS (476 char)
    primary_question: "Launch 主題？",
    primary_input: { key: "launch_topic", placeholder: "新品 / 募資 / 重大合作", type: "textarea" },
    inputs: [{ key: "launch_topic", label: "Launch 主題", type: "textarea", required: true }],
    // 2026-05-17 (CJ「參考 PR 獎項得獎工藝」): earned-media craft inline
    // (TONE_100 is shared with non-PR toolkits — must not globally edit).
    systemPrompt: `【得獎工藝參考】Whopper Detour（Burger King / FCB，Cannes Lions 2019）：整套之所以拿獎，是「一個新聞鉤」貫穿所有素材——新聞稿、pitch、社群、Q&A 講的是同一個不可抗拒的角度，互相加乘而非各說各話。
產出 PR launch toolkit 其中 1 部分（300–700 字）。本次你寫的是「{label}」（新聞稿 / Q&A / 媒體聯絡 / 後續追蹤 / Spokesperson talking points）。

【earned-media 工藝 — 每一部分都適用】
- 先找「新聞鉤」：這個 launch 為什麼值得被報導？最強角度是什麼？整套 toolkit 都圍繞這一個鉤，不要每部分各說各話。
- 通過記者測試：記者會主動選擇報嗎？用可查證事實（數字/名字/日期/第三方背書）贏得關注，不用形容詞宣稱。沒有的事實標「[待補]」，不杜撰。
- 扣文化與時機：點出「為什麼是現在」，連結此刻受眾已在乎的事。
- 倒金字塔、客觀第三人稱（社群/talking points 可口語但事實一致）；句子寫成記者能原句引用。
- 禁 buzzword、「業界領先／顛覆」、「我們很高興宣布」、暖身式開頭。
- 各部分要能互相銜接成一套（新聞稿的角度＝pitch 賣的角度＝Q&A 防守的點＝talking points 的金句）。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "press", post_type: "press" },
  },
  {
    // 2026-05-17 (CJ B「繼續深化」→ 借時事 Newsjack，需 99s 即時 scout):
    // scout 抓回「此刻正在發燒的趨勢/新聞」，把品牌安全地接上去。
    id: "pr-99-newsjack",
    tier: "99s", postType: "press",
    label: "借時事新聞鉤（Newsjack）",
    description: "把品牌安全接上此刻正在發燒的時事，產出可報導的角度",
    agent_id: 223197, skill_slug: "pr-writing",
    primary_question: "品牌想被看見的點 / 可連結的專業或產品是什麼？",
    primary_input: { key: "context", placeholder: "品牌的專業領域/產品/觀點，以及任何手上的事實或數字（系統會自動帶入此刻熱門時事）", type: "textarea" },
    inputs: [{ key: "context", label: "品牌可連結的點 + 手上素材", type: "textarea", required: true }],
    systemPrompt: `【得獎工藝參考】Oreo「Dunk in the Dark」（2013 超級盃停電即時 newsjack，earned-media 經典）：贏在「在對的時刻、用對的角度，把品牌接上一個正在發燒的公共話題」，而且快、自然、不尷尬。

系統已透過 scout 帶入「此刻正在發燒的時事/趨勢」（見下方即時資料區塊）。你的工作：從這些真實時事中，挑出品牌能「自然且有正當性」接上的，產出一個可被記者報導的 newsjack 角度。每個變體＝接一個不同的時事 / 不同接法。

嚴格照此格式輸出：
【角度】<一句話：品牌如何接上哪個正在發燒的時事，記者會怎麼下標>
【為什麼會被報】<2–3 句：這個時事為何正熱、品牌切入的正當性與貢獻、為什麼是現在；扣具體事實/數字（無則[待補]）>
【一句 pitch】<可直接寄給記者的一句，賣「品牌×時事」的角度，不賣品牌本身>
【建議下一步】<接哪個任務展開：如「用『新聞稿標題』生標題」「用『media pitch』寄科技記者」；並標註此鉤的時效（多久內要發）>

準則：
- 只接「品牌有正當發言權」的時事；不蹭悲劇、不蹭爭議性政治、不硬湊——寧可少給也不要尷尬蹭流量（這會傷品牌，評審也會扣分）。
- 必須引用 scout 帶回的「真實時事」，不要自己編一個趨勢。沒有合適可接的就明說「此批時事無適合切入點」。
- 具體勝過修辭、不杜撰、可被記者原句引用。
- 只輸出上面四欄，不要前言或結語。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 600,
    outputDefaults: { platform: "press", post_type: "press" },
  },
  // pr-99-crisis-toolkit removed per CJ direction 2026-05-06 — risky.
  {
    id: "br-99-reposition-toolkit",
    tier: "99s", postType: "press",
    label: { en: "Brand Reposition Toolkit", zh: "品牌重新定位完整 Toolkit" },
    description: "Positioning + Tagline 套 + Voice guide + Visual direction + 應用範例",
    agent_id: 60002, skill_slug: "brand-strategy", // Ethan Chiang | DTC E-commerce Brand Strategist
    primary_question: "想往什麼方向轉？（已讀入現有定位作為起點）",
    primary_input: { key: "new_position", placeholder: "新定位方向 / 想拋下的舊包袱", type: "textarea" },
    inputs: [{ key: "new_position", label: "新定位方向", type: "textarea", required: true }],
    contextSources: [
      "brand.positioning.goldenCircle",
      "brand.positioning.differentiation",
      "brand.positioning.voice",
    ],
    systemPrompt: `產出 Brand reposition toolkit 其中 1 部分（300-600 字）。
本次你寫的是「{label}」（Positioning statement / Tagline 5 套 / Voice guide / Visual direction / 5 個應用範例）。
品牌已有完整定位 — 重新定位要明確指出哪些保留、哪些拋下，不是從零開始。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1200,
    outputDefaults: { platform: "press", post_type: "press" },
  },
  {
    id: "br-99-voice-playbook",
    tier: "99s", postType: "press",
    label: { en: "Brand Voice Playbook", zh: "品牌語氣完整 Playbook" },
    description: "8 個應用情境 + Do/Don't 詳細 + 5 個範例 + 跨平台 voice 適配",
    agent_id: 32, skill_slug: "brand-strategy", // Fiona Hsu | Copywriter
    primary_question: "想補充或微調哪些情境？（已讀入既有 Voice — 留空即直接展開 8 情境 playbook）",
    primary_input: { key: "voice_direction", placeholder: "選填 — 想強化的特定情境，如客服 / 危機 / 跨國", type: "textarea" },
    inputs: [{ key: "voice_direction", label: "情境補充（選填）", type: "textarea", required: false }],
    contextSources: [
      "brand.positioning.voice",
      "brand.positioning.goldenCircle.why",
    ],
    systemPrompt: `產出 Brand voice playbook 其中 1 部分（400-700 字）。
本次你寫的是「{label}」。品牌已有「Voice」段落（人格原型 / 語調詞 / 禁區 / 範例對比）— 此 toolkit 是把它延伸到 8 個實戰情境（社群 / 客服 / 危機 / EDM / PR / 跨國 / 內部 / API），不要重寫基礎 voice。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "press", post_type: "press" },
  },
  {
    id: "rs-99-discovery-sprint",
    tier: "99s", postType: "press",
    label: { en: "User Research · Discovery Sprint", zh: "用戶研究 5 天 Discovery Sprint" },
    description: "訪綱 + 5 personas + JTBD map + insights synthesis + 行動建議",
    agent_id: 90043, skill_slug: "user-research", // Lydia Chiu | Qualitative Research Director
    primary_question: "想了解用戶什麼？（已讀入既有受眾定位 — 留空即用既有 persona 延伸研究假設）",
    primary_input: {
      key: "research_goal",
      placeholder: "選填 — 想驗證的新假設或想深挖的角度",
      type: "textarea",
    },
    inputs: [{ key: "research_goal", label: "研究目標（選填）", type: "textarea", required: false }],
    contextSources: [
      "brand.positioning.audience.primary",
      "brand.positioning.audience.matrix",
      "brand.positioning.goldenCircle.why",
    ],
    systemPrompt: `產出 Discovery sprint 其中 1 部分（400-700 字）。
本次你寫的是「{label}」（Day 1 訪綱 / Day 2-3 訪談 + 5 personas / Day 4 JTBD map / Day 5 synthesis + 行動）。
品牌定位的「目標受眾」已建立 primary persona 與情感需求矩陣 — 請以此為起點延伸研究假設，不要重新拆受眾。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "press", post_type: "press" },
  },
  {
    id: "rs-99-competitor-mapping",
    tier: "99s", postType: "press",
    // 2026-05-11 (CJ「中英文研究意圖不一樣」): split label + correct EN
    // (this is competitor research, not user research).
    label: { en: "Competitor Research Map", zh: "競品研究完整地圖" },
    description: "5-10 競品分析 + 定位 map + opportunity gaps + 推薦策略",
    agent_id: 90006, skill_slug: "competitive-intel", // Steven Chen — Research Manager, Consumer Insights
    primary_question: "想補充什麼？（系統已讀入品牌的競品定位 — 可留空直接跑）",
    primary_input: {
      key: "category",
      placeholder: "選填 — 想額外切入的角度，例如：只看線上競品、加入海外案例",
      type: "textarea",
      // 2026-05-11 — auto-resolve the领域 from the brand's audience +
      // industry. If the brand has positioning, the modal pre-fills
      // and the question becomes optional rather than required.
      derive: {
        from: ["brand.positioning.audience.primary", "brand.industry"],
        mode: "auto",
      },
    },
    inputs: [{
      key: "category",
      label: "額外補充（選填）",
      type: "textarea",
      required: false, // ← no longer required; positioning provides ground truth
      derive: {
        from: ["brand.positioning.audience.primary", "brand.industry"],
        mode: "auto",
      },
    }],
    // 2026-05-11 — declare which positioning segments the task uses,
    // so the modal can show "我會用 X 競品 / Y 受眾 來跑這個任務".
    contextSources: [
      "brand.positioning.competition.direct",
      "brand.positioning.competition.indirect",
      "brand.positioning.differentiation",
      "brand.positioning.audience.primary",
    ],
    systemPrompt: `產出競品 mapping 其中 1 部分（300-600 字）。
本次你寫的是「{label}」（市場 overview / 競品 1-5 deep dive / 定位 map / opportunity gaps / 推薦策略）。
**重要：** 品牌定位的「競爭格局分析」已寫過 direct / indirect 競品清單與我方差異點 — 請直接引用、深化，不要重複列同一份。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1200,
    outputDefaults: { platform: "press", post_type: "press" },
  },

  // ─── 2026-05-12 (CJ「競品截圖」)──────────────────────────────
  // 競品廣告偵察 — 用 LLM web search 撈 Meta Ads Library 公開資料，
  // 不直接 scrape（避免 TOS 風險）。資料量大時請求 Claude 搭 web_search
  // 翻譯成可讀的競品 report。
  {
    id: "rs-99-competitor-ads",
    tier: "99s", postType: "press",
    label: { en: "Competitor Ad Intelligence", zh: "競品廣告偵察報告（Meta Ads Library）" },
    description: "撈最多 5 個競品在 Meta Ads Library 的近期投放 → LLM 分析比例 / 訴求 / 視覺",
    agent_id: 210225, skill_slug: "competitive-intel",
    primary_question: "要監測哪些競品？（最多 5 個品牌名，用逗號分隔）",
    primary_input: {
      key: "competitor_brands",
      placeholder: "例：屈臣氏, 康是美, 86 小舖",
      type: "textarea",
    },
    inputs: [
      { key: "competitor_brands", label: "競品品牌", type: "textarea", required: true,
        placeholder: "用逗號分隔，最多 5 個" },
      { key: "focus", label: "想看什麼？（選填）", type: "textarea", required: false,
        placeholder: "投放節奏 / 訴求語氣 / 視覺風格 / 廣告類型分佈 / 全部" },
    ],
    contextSources: [
      "brand.positioning.competition.direct",
      "brand.positioning.differentiation",
    ],
    systemPrompt: `產出競品廣告偵察報告其中 1 部分（300-600 字）。本次你寫的是「{label}」。

**資料來源（請呼叫 web_search）：**
請對每個競品搜尋 \`site:facebook.com/ads/library/ <品牌名>\` 或直接訪問
\`https://www.facebook.com/ads/library/?active_status=all&ad_type=all&country=TW&q=<競品>\`
撈該品牌近 30-90 天在台灣投放的廣告（含創意縮圖描述、文案、投放開始日）。

**輸出結構**（依本步驟所屬段落）：
- 投放節奏：每個競品幾支廣告、頻率、新舊比
- 訴求分析：情感 vs 功能 / 折扣 vs 故事 / hook 套路
- 視覺風格：色調、版面、人物 vs 產品為主
- 廣告類型分佈：圖片 / 影片 / 輪播 / Reels
- 機會點：我方差異 vs 競品空白
${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1500,
    outputDefaults: { platform: "press", post_type: "press" },
  },

  // ─── 2026-05-12 (CJ「KOL 我們提供說法，不提供名單」)──────────
  {
    id: "kl-99-campaign-toolkit",
    tier: "99s", postType: "press",
    label: { en: "KOL Campaign Toolkit", zh: "KOL Campaign 完整話術包" },
    description: "多 KOL 分層邀請 + 漏斗訊息 + brief 模板 + 報價回應 + 結案報告",
    agent_id: 220920, skill_slug: "kol-outreach", // Chloe Chen | Senior KOL & Influencer Manager
    primary_question: "活動主題 + 預計合作量級？",
    primary_input: {
      key: "campaign_brief",
      placeholder: "例：5 月母親節活動，想找 5 位媽媽育兒 KOL，預算共 30 萬",
      type: "textarea",
    },
    inputs: [
      { key: "campaign_brief", label: "活動 brief", type: "textarea", required: true },
      { key: "kol_tiers", label: "KOL 分層（選填）", type: "text", required: false,
        placeholder: "例：1 位 100K+ + 2 位 30-100K + 5 位 1-10K" },
    ],
    contextSources: [
      "brand.positioning.voice",
      "brand.positioning.goldenCircle.why",
      "brand.positioning.differentiation.summary",
    ],
    systemPrompt: `產出 KOL Campaign Toolkit 其中 1 部分（400-700 字）。
本次你寫的是「{label}」（邀請開場 / brand brief 模板 / 報價回應 / brief 確認 /
拍攝期追蹤 / 上稿確認 / 結案感謝 / 結案數據要求）。

我們**不**幫客戶找 KOL 名單。我們提供：
- 怎麼開場（不被當業配機器拒絕）
- 怎麼給 brief（KOL 能拍但不偏離品牌）
- 怎麼回應報價（守得住但不傷關係）
- 怎麼收尾（讓 KOL 願意再合作）

語氣：尊重、不卑不亢、有 brand pride 但不傲慢。
${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1400,
    outputDefaults: { platform: "press", post_type: "press" },
  },
];

// ─── Orchestra configs ──────────────────────────────────────────────────
// Image directors per channel
const MANDY = 220887, NANCY = 180170, NINA = 180157, ANNA = 180165; // Mandy → Claire Chen (977 char)
const ZEYU = 60071, NATHAN = 60062, BR_IMG = 60030, RS_IMG = 24;
// 2026-05-08: per-task unique image directors for 100s tier
const TT100_IMG2 = 220896; // Brian Chen — Digital Experience Designer
const LI100_IMG2 = 210018; // Zach Ko — AI Design Thinking Consultant (IDEO)
const EM100_IMG2 = 210019; // Sophia Liao — AI Digital Experience Strategist (McKinsey)
const BR100_IMG2 = 39;     // Tom Hsu — Marketing Designer

const fb100Common = {
  runImageGen: true, imageDirectorId: MANDY,
  imageQualitySteps: 4,
  extras: { replyTemplates: 5, postingTime: true, followupPost: true, narrativeArc: true },
};

// ─── FB 100s orchestra configs ──────────────────────────────────────────
// Legacy squad mapping (these 100s tasks reuse the SHAPE of existing
// FB squads — same multi-post deliverable structure; orchestra runner
// instead of stepExecute pipeline for unified UX):
//   fb-99-30day-calendar     ← fb-monthly-calendar squad
//   fb-99-14day-countdown    ← fb-countdown-series squad
//   fb-99-launch-toolkit     ← fb-event-launch-kit squad
//   fb-99-livestream-9seg    ← fb-livestream-prep squad
//   fb-99-crisis-playbook    ← fb-crisis-comms squad
export const FB_99S_ORCHESTRA: Record<string, OrchestraConfig> = {
  "fb-99-30day-calendar": {
    // 2026-05-18 (CJ「分配不同 agent 處理不同類型內容比較快」): each
    // pillar = its own parallel agent (callCaptionWriter fanout), then
    // merged into one 30-day calendar (calendarMerge). No image gen / no
    // strategist → ~5× faster, no 502.
    ...fb100Common,
    variants: 5, images: 0, runImageGen: false,
    imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any,
    variantLabels: ["理念WHY", "產品", "節慶", "UGC見證", "權威觀點"],
    captionMinChars: 200, captionMaxChars: 4000,
    scoutKind: "festivals", // 抓即時節慶供「節慶」支柱使用（已有 18s 上限）
    calendarMerge: true,
    extras: {},
  },
  "fb-99-monthly-calendar-promo": {
    ...fb100Common,
    variants: 5, images: 0, runImageGen: false,
    imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any,
    variantLabels: ["產品促銷", "急迫限時", "節慶檔期", "UGC見證", "理念WHY"],
    captionMinChars: 200, captionMaxChars: 4000,
    scoutKind: "festivals",
    calendarMerge: true,
    extras: {},
  },
  "fb-99-carousel-5": {
    ...fb100Common,
    // single version (one carousel), 5 cards each with its own image
    variants: 1, images: 1,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["輪播版本"],
    captionMinChars: 150, captionMaxChars: 250,
    strategistAgentId: 180030, // Kevin Lin — Content Strategy
    cardsPerVariant: 5,
    holdForImages: true,
    extras: { replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "fb-99-viral-rewrite": {
    ...fb100Common, variants: 5, images: 5,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["保結構式", "情感放大式", "反差式", "數據式", "故事式"],
    captionMinChars: 200, captionMaxChars: 400,
    strategistAgentId: 180142, // Kevin Liu — Social Listening
    specialtyAgentId: 220504,  // Cheng-Tse Liao — Compare Editor
    scoutKind: "viral",
    holdForImages: true,
    extras: { ...fb100Common.extras, compareTable: true },
  },
  "fb-99-testimonial-rewrite": {
    ...fb100Common, variants: 5, images: 5,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["故事式", "對比式", "數據式", "情感式", "簡短式"],
    captionMinChars: 200, captionMaxChars: 350,
    strategistAgentId: 220754, // Kurt Chen — Insights Storyteller
    specialtyAgentId: 180855,  // Jason Evans — Risk & Compliance
    holdForImages: true,
    extras: { ...fb100Common.extras, legalAssistant: true },
  },
  "fb-99-trend-rewrite": {
    ...fb100Common, variants: 5, images: 5,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["評論式", "幽默式", "資訊式", "立場式", "中立式"],
    captionMinChars: 150, captionMaxChars: 300,
    strategistAgentId: 90011, // Mark Davis — Public Affairs
    specialtyAgentId: 220959, // Trend Researcher — Timing Advisor
    scoutKind: "trending",
    holdForImages: true,
    extras: { ...fb100Common.extras, timingAdvisor: true },
  },
  "fb-99-serial-3": {
    ...fb100Common, variants: 3, images: 3,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["第 1 集", "第 2 集", "第 3 集"],
    captionMinChars: 200, captionMaxChars: 350,
    strategistAgentId: 220863, // Nelson Chen — Narrative Editor
    postLabels: ["第 1 集", "第 2 集", "第 3 集"],
    holdForImages: true,
    extras: { ...fb100Common.extras, postsCount: 3 },
  },
  "fb-99-14day-countdown": {
    ...fb100Common, variants: 7, images: 7,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["Day 14", "Day 12", "Day 10", "Day 7", "Day 5", "Day 3", "Day 1"],
    captionMinChars: 80, captionMaxChars: 130,
    strategistAgentId: 60013, // Kevin Kan — SEO Content Strategist
    postLabels: ["Day 14", "Day 12", "Day 10", "Day 7", "Day 5", "Day 3", "Day 1"],
    scoutKind: "festivals", // 倒數活動 → 抓相關節慶 / 行銷檔期
    extras: { ...fb100Common.extras, postsCount: 7 },
  },
  "fb-99-launch-toolkit": {
    // 2026-05-18 (CJ「launch-toolkit 加總覽」): first variant = 活動總覽
    // (one-page campaign plan doc), then the 8 posts.
    ...fb100Common, variants: 9, images: 9,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["活動總覽", "預告 1", "預告 2", "預告 3", "當日", "即時 1", "即時 2", "事後", "IG 跨平台"],
    captionMinChars: 150, captionMaxChars: 300,
    strategistAgentId: 60002, // Ethan Chiang — DTC E-commerce Brand Strategist
    postLabels: ["活動總覽", "預告 1", "預告 2", "預告 3", "當日", "即時 1", "即時 2", "事後", "IG 跨平台"],
    scoutKind: "viral", // 看同類 launch 通常用什麼 hook
    extras: { ...fb100Common.extras, postsCount: 9 },
  },
  "fb-99-livestream-9seg": {
    ...fb100Common, variants: 9, images: 9,
    aspectRatio: "16:9", fluxSize: "landscape_16_9",
    variantLabels: ["預告", "開場宣告", "爆點 1", "爆點 2", "爆點 3", "爆點 4", "爆點 5", "結尾", "Reel 剪輯"],
    captionMinChars: 80, captionMaxChars: 200,
    strategistAgentId: 224091, // Nurul Huda — Email & CRM Strategist eCommerce MY (1250 char)
    postLabels: ["預告", "開場宣告", "爆點 1", "爆點 2", "爆點 3", "爆點 4", "爆點 5", "結尾", "Reel 剪輯"],
    scoutKind: "viral",
    extras: { ...fb100Common.extras, postsCount: 9 },
  },
  "fb-99-crisis-playbook": {
    ...fb100Common, variants: 7, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any,
    variantLabels: ["偵測警示", "第一份聲明", "24h 更新", "48h 更新", "72h 更新", "1 週 follow-up", "媒體 talking points"],
    captionMinChars: 200, captionMaxChars: 400,
    strategistAgentId: 90011,
    specialtyAgentId: 180630, // Shirley Sanchez — Global Affairs & General Counsel (2355 char)
    postLabels: ["偵測警示", "第一份聲明", "24h 更新", "48h 更新", "72h 更新", "1 週 follow-up", "媒體 talking points"],
    scoutKind: "trending", // 危機處理 → 抓即時相關新聞
    extras: { ...fb100Common.extras, postsCount: 7, legalAssistant: true, narrativeArc: true },
  },
};

const ig100Common = {
  runImageGen: true, imageDirectorId: NANCY,
  imageQualitySteps: 4,
  extras: { replyTemplates: 5, postingTime: true, followupPost: true, narrativeArc: true },
};

// IG 100s — legacy squad mapping:
//   ig-99-30day-calendar     ← (no exact IG squad; reuses fb-monthly-calendar shape)
//   ig-99-reel-series-6      ← (new — adapted from fb-reels-script squad)
//   ig-99-account-reposition ← fb-account-reposition squad shape
export const IG_99S_ORCHESTRA: Record<string, OrchestraConfig> = {
  "ig-99-30day-calendar": {
    ...ig100Common, variants: 4, images: 4,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    captionMinChars: 400, captionMaxChars: 800,
    strategistAgentId: 60008, // Fiona Hsieh — Social Media Marketing Strategist (Beauty)
    postLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    scoutKind: "festivals",
    extras: { ...ig100Common.extras, postsCount: 4 },
  },
  "ig-99-reel-series-6": {
    ...ig100Common, variants: 6, images: 6,
    aspectRatio: "9:16", fluxSize: "portrait_9_16",
    variantLabels: ["第 1 集", "第 2 集", "第 3 集", "第 4 集", "第 5 集", "第 6 集"],
    captionMinChars: 250, captionMaxChars: 500,
    strategistAgentId: 180162, // Jason Peng — Social Media Copywriter (1440 char)
    postLabels: ["第 1 集", "第 2 集", "第 3 集", "第 4 集", "第 5 集", "第 6 集"],
    scoutKind: "viral",
    extras: { ...ig100Common.extras, postsCount: 6 },
  },
  "ig-99-account-reposition": {
    ...ig100Common, variants: 5, images: 5,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["新 Bio", "Highlight 套組", "Launch Post 1-3", "Launch Post 4-6", "Launch Post 7-9"],
    captionMinChars: 250, captionMaxChars: 500,
    strategistAgentId: 60005, // Aaron Pei — B2B Tech Brand Marketing (1181 char)
    postLabels: ["新 Bio", "Highlight 套組", "Launch Post 1-3", "Launch Post 4-6", "Launch Post 7-9"],
    scoutKind: "viral",
    extras: { ...ig100Common.extras, postsCount: 5 },
  },
};

const yt100Common = {
  runImageGen: true, imageDirectorId: NINA,
  imageQualitySteps: 8,
  extras: { replyTemplates: 5, postingTime: true, followupPost: true, narrativeArc: true },
};

// YT 100s — legacy squad mapping:
//   yt-99-quarterly-strategy ← fb-quarterly-strategy squad shape
//   yt-99-series-6ep         ← (new — extends 60s yt-60-series-3ep)
//   yt-99-premiere-kit       ← (new — adapted from fb-livestream-prep)
export const YT_99S_ORCHESTRA: Record<string, OrchestraConfig> = {
  "yt-99-series-6ep": {
    ...yt100Common, variants: 6, images: 6,
    aspectRatio: "16:9", fluxSize: "landscape_16_9",
    variantLabels: ["EP1", "EP2", "EP3", "EP4", "EP5", "EP6"],
    captionMinChars: 500, captionMaxChars: 1000,
    strategistAgentId: 90002, // Darren Freeman — Creative Excellence Director (2348 char)
    postLabels: ["EP1", "EP2", "EP3", "EP4", "EP5", "EP6"],
    scoutKind: "viral",
    extras: { ...yt100Common.extras, postsCount: 6 },
  },
  "yt-99-quarterly-strategy": {
    ...yt100Common, variants: 5, images: 5,
    aspectRatio: "16:9", fluxSize: "landscape_16_9",
    variantLabels: ["內容支柱", "12 影片 title", "Community 月曆", "Competitor 分析", "即時趨勢報告"],
    captionMinChars: 300, captionMaxChars: 600,
    strategistAgentId: 30001, // Alex Chen — AI Growth Hacker CMO (1831 char)
    postLabels: ["內容支柱", "12 影片 title", "Community 月曆", "Competitor 分析", "即時趨勢報告"],
    scoutKind: "news", // 季度策略 → 抓產業最新
    extras: { ...yt100Common.extras, postsCount: 5 },
  },
  "yt-99-premiere-kit": {
    ...yt100Common, variants: 4, images: 4,
    aspectRatio: "16:9", fluxSize: "landscape_16_9",
    variantLabels: ["Trailer 腳本", "Community 倒數 ×5", "直播配套", "精華剪輯指南"],
    captionMinChars: 200, captionMaxChars: 400,
    strategistAgentId: 90022, // Andy Gallagher — Head of Creative & Media (1464 char)
    postLabels: ["Trailer 腳本", "Community 倒數 ×5", "直播配套", "精華剪輯指南"],
    scoutKind: "viral",
    extras: { ...yt100Common.extras, postsCount: 4 },
  },
};

// Multi-channel 100s — legacy squad mapping (where applicable):
//   tt-99-trend-week → (new — TikTok trend chasing)
//   tt-99-30day-foryou → (new — extends fb-monthly-calendar shape)
//   li-99-newsletter-quarterly → (new)
//   em-99-launch-sequence → fb-event-launch-kit shape adapted to email
//   pr-99-crisis-toolkit → fb-crisis-comms shape adapted to PR
//   rs-99-competitor-mapping → fb-account-reposition + competitor-audit shape
export const MULTI_99S_ORCHESTRA: Record<string, OrchestraConfig> = {
  "tt-99-30day-foryou": {
    variants: 4, images: 4, runImageGen: true, imageDirectorId: ANNA,
    aspectRatio: "9:16", fluxSize: "portrait_9_16", imageQualitySteps: 4,
    variantLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    captionMinChars: 300, captionMaxChars: 700,
    strategistAgentId: 90015, // Sonia Belgacem — Global Client Service Manager, Creative Excellence (1547 char)
    postLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    scoutKind: "festivals",
    extras: { postsCount: 4, narrativeArc: true, replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "tt-99-trend-week": {
    variants: 7, images: 7, runImageGen: true, imageDirectorId: TT100_IMG2,
    aspectRatio: "9:16", fluxSize: "portrait_9_16", imageQualitySteps: 4,
    variantLabels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    captionMinChars: 200, captionMaxChars: 400,
    postLabels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    scoutKind: "trending", // 追熱點 → 抓即時時事
    extras: { postsCount: 7, replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "li-99-30day-thought-leadership": {
    variants: 4, images: 4, runImageGen: true, imageDirectorId: ZEYU,
    aspectRatio: "1.91:1", fluxSize: "landscape_4_3", imageQualitySteps: 4,
    variantLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    captionMinChars: 400, captionMaxChars: 800,
    postLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    scoutKind: "news", // thought-leadership → 抓產業最新
    extras: { postsCount: 4, replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "li-99-newsletter-quarterly": {
    variants: 4, images: 4, runImageGen: true, imageDirectorId: LI100_IMG2,
    aspectRatio: "1.91:1", fluxSize: "landscape_4_3", imageQualitySteps: 4,
    variantLabels: ["第 1 期", "第 2 期", "第 3 期", "第 4 期"],
    captionMinChars: 400, captionMaxChars: 800,
    strategistAgentId: 180015, // Kevin Lin — Content Strategy Director
    postLabels: ["第 1 期", "第 2 期", "第 3 期", "第 4 期"],
    scoutKind: "news",
    extras: { postsCount: 4, narrativeArc: true, replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "em-99-4week-nurture": {
    variants: 4, images: 4, runImageGen: true, imageDirectorId: NATHAN,
    aspectRatio: "1.91:1", fluxSize: "landscape_4_3", imageQualitySteps: 4,
    variantLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    captionMinChars: 200, captionMaxChars: 400,
    strategistAgentId: 180141, // Rachel Chen — Social Media Strategy Director
    postLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    scoutKind: "viral",
    extras: { postsCount: 4, narrativeArc: true, replyTemplates: 3, postingTime: true, followupPost: true },
  },
  "em-99-launch-sequence": {
    variants: 7, images: 7, runImageGen: true, imageDirectorId: EM100_IMG2,
    aspectRatio: "1.91:1", fluxSize: "landscape_4_3", imageQualitySteps: 4,
    variantLabels: ["預告 1", "預告 2", "上線", "提醒 1", "提醒 2", "最後機會", "後續"],
    captionMinChars: 200, captionMaxChars: 400,
    strategistAgentId: 60080, // Ethan Yeh — Cross-border Marketing Strategy
    postLabels: ["預告 1", "預告 2", "上線", "提醒 1", "提醒 2", "最後機會", "後續"],
    scoutKind: "viral",
    extras: { postsCount: 7, narrativeArc: true, replyTemplates: 3, postingTime: true, followupPost: true },
  },
  "pr-99-launch-toolkit": {
    variants: 5, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    variantLabels: ["新聞稿", "Q&A", "媒體聯絡", "後續追蹤", "Spokesperson talking"],
    captionMinChars: 300, captionMaxChars: 700,
    postLabels: ["新聞稿", "Q&A", "媒體聯絡", "後續追蹤", "Spokesperson talking"],
    scoutKind: "news",
    extras: { postsCount: 5, replyTemplates: 3 },
  },
  "pr-99-newsjack": {
    // pool of 6 distinct trend-hooks; RunPage >4 = 「再給我幾個」.
    variants: 6, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    variantLabels: ["時事 A", "時事 B", "時事 C", "另一接法 D", "另一接法 E", "長尾 F"],
    captionMinChars: 80, captionMaxChars: 420,
    scoutKind: "trending", // 借時事 → 抓此刻正在發燒的趨勢/新聞
  },
  // pr-99-crisis-toolkit orchestra config removed.
  "br-99-reposition-toolkit": {
    variants: 5, images: 5, runImageGen: true, imageDirectorId: BR_IMG,
    aspectRatio: "1:1", fluxSize: "square_hd", imageQualitySteps: 4,
    variantLabels: ["Positioning", "Tagline 5 套", "Voice guide", "Visual direction", "5 應用範例"],
    captionMinChars: 300, captionMaxChars: 600,
    strategistAgentId: 180038, // Daniel Wu — D2C Strategy Manager
    postLabels: ["Positioning", "Tagline 5 套", "Voice guide", "Visual direction", "5 應用範例"],
    scoutKind: "news",
    extras: { postsCount: 5, narrativeArc: true, replyTemplates: 3 },
  },
  "br-99-voice-playbook": {
    variants: 4, images: 4, runImageGen: true, imageDirectorId: BR100_IMG2,
    aspectRatio: "1:1", fluxSize: "square_hd", imageQualitySteps: 4,
    variantLabels: ["8 應用情境", "Do/Don't", "5 範例", "跨平台適配"],
    captionMinChars: 400, captionMaxChars: 700,
    postLabels: ["8 應用情境", "Do/Don't", "5 範例", "跨平台適配"],
    scoutKind: "viral",
    extras: { postsCount: 4, replyTemplates: 3 },
  },
  "rs-99-discovery-sprint": {
    variants: 5, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    variantLabels: ["Day 1 訪綱", "Day 2-3 Personas", "Day 4 JTBD map", "Day 5 Synthesis", "行動建議"],
    captionMinChars: 400, captionMaxChars: 700,
    postLabels: ["Day 1 訪綱", "Day 2-3 Personas", "Day 4 JTBD map", "Day 5 Synthesis", "行動建議"],
    scoutKind: "news",
    extras: { postsCount: 5, replyTemplates: 3 },
  },
  "rs-99-competitor-mapping": {
    variants: 5, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    variantLabels: ["市場 overview", "競品 deep dive ×5", "定位 map", "Opportunity gaps", "推薦策略"],
    captionMinChars: 300, captionMaxChars: 600,
    postLabels: ["市場 overview", "競品 deep dive ×5", "定位 map", "Opportunity gaps", "推薦策略"],
    scoutKind: "news",
    extras: { postsCount: 5, replyTemplates: 3 },
  },
};

// ─── Unified lookup ─────────────────────────────────────────────────────
const ALL_99_TASKS = [...FB_99S_TASKS, ...IG_99S_TASKS, ...YT_99S_TASKS, ...MULTI_99S_TASKS];
const ALL_99_ORCH: Record<string, OrchestraConfig> = {
  ...FB_99S_ORCHESTRA, ...IG_99S_ORCHESTRA, ...YT_99S_ORCHESTRA, ...MULTI_99S_ORCHESTRA,
};

export const ALL_99S_TASKS = ALL_99_TASKS;
export const ALL_99S_ORCHESTRA = ALL_99_ORCH;

export function get99Template(taskId: string): FBTaskTemplate | null {
  return ALL_99_TASKS.find((t) => t.id === taskId) ?? null;
}
export function get99OrchestraConfig(taskId: string): OrchestraConfig | null {
  return ALL_99_ORCH[taskId] ?? null;
}
