/**
 * 100s tier — campaign-level deliverables with REAL-TIME DATA (2026-05-06).
 *
 * Distinct from 60s: 100s tasks output WHOLE CAMPAIGNS / SERIES / MONTHLY
 * CALENDARS, not single posts. Each task ships 8-30 assets per run, with
 * scout-fetched REAL-TIME DATA (upcoming festivals for calendars, current
 * trending events for trend rewrites, industry news for thought leadership).
 *
 * 60s = 1 post production package (5 variants of 1 caption + extras).
 * 100s = 1 campaign production package (N posts + real-time scout data).
 *
 * Many 100s tasks correspond to existing legacy squads (fb-monthly-calendar,
 * fb-event-launch-kit, fb-crisis-comms, etc.) — these squads already had
 * full agent rosters and methodology; 100s tasks reuse the SHAPE of those
 * deliverables but ship via the orchestra runner for unified UX.
 *
 * Wall budget 100s. Scout stage runs upfront to inject real data into
 * caption_writer prompts.
 */
import type { FBTaskTemplate, OrchestraConfig } from "./quickTaskFB";

const TONE_100 = `
語氣要求：自然、有 hook、不官腔。
本任務輸出 campaign 級別內容，每篇/每節都要扣回主敘事弧。
**即時資料**：scout 階段已抓回即時節慶 / 時事 / 趨勢資料，請扣回這些真實 context，不要寫得通用。`;

// ─── FB 100s (5 tasks) ────────────────────────────────────────────────
export const FB_99S_TASKS: FBTaskTemplate[] = [
  {
    // 2026-05-18 (CJ「30天行事曆結果很不理想，要結構化行事曆+指定配比」):
    // single structured 30-day calendar (NOT a strategy essay / weekly
    // chunk). Fixed content mix per CJ + coursera FB-marketing structure.
    id: "fb-99-30day-calendar",
    tier: "99s", postType: "feed",
    label: "FB 30 天內容行事曆",
    description: "結構化 30 天行事曆：4 理念WHY / 4 產品 / 2 節慶 / 2 UGC見證 / 2 國際權威",
    agent_id: 224089, // Kevin Tan — Social Media Strategist eCommerce MY (1147 char)
    skill_slug: "content-calendar",
    primary_question: "本月主推 / 主題？（可寫多個產品與目標族群）",
    primary_input: { key: "monthly_focus", placeholder: "例：母親節檔｜主推 A 產品(忙碌媽媽) + B 產品(小資女)｜品牌理念：讓每個人都能輕鬆做出好內容", type: "textarea" },
    inputs: [
      { key: "monthly_focus", label: "本月主題 + 產品 + 目標族群", type: "textarea", required: true },
    ],
    // 2026-05-18 (CJ「分配不同 agent 處理不同類型內容，比較快」): each
    // pillar group is generated by its OWN parallel agent ({label} = the
    // pillar). The orchestra then merges all groups into one 30-day
    // calendar (calendarMerge). ~5× faster, no 502.
    systemPrompt: `你是 FB 內容行事曆策略師。本次**只負責「{label}」這一個內容支柱**，產出該支柱的貼文，**只輸出嚴格 JSON 陣列**。

各支柱該產出的則數（只做你被指派的「{label}」那組）：
- 「理念WHY」→ 4 則：用黃金圈 Why 講品牌理念/創業初衷，不談產品功能
- 「產品」→ 4 則：每則只針對「一個目標族群」溝通「一個 USP」並帶到「一個產品」
- 「節慶」→ 2 則：搭配本月實際接近的節慶/檔期
- 「UGC見證」→ 2 則：使用者見證，每則見證「一個產品」、溝通「一個 USP」
- 「權威觀點」→ 2 則：引用國際權威/研究/名人觀點，印證品牌創業理念（理念，非產品）

每則物件欄位：
{"day": <1-30 整數>, "pillar": "{label}", "audience": "<對誰說；理念/權威可寫『全體受眾』>", "usp": "<單一賣點；理念/權威留空字串>", "product": "<帶到的產品；理念/權威留空字串>", "hook": "<前 2 行鉤子 ≤30字>", "message": "<核心訊息 60-110字>", "format": "圖文|短影音|輪播|直播|純文字", "cta": "<行動呼籲 ≤15字>"}

規則：
- 第一個字元就是 [，最後一個字元就是 ]。不要 markdown 圍欄、不要說明文字。
- 只產「{label}」這組、嚴格照上面對應則數；pillar 欄位一律填「{label}」。
- day 給 1-30 的合理值（系統會把所有支柱合併後重新分散排序）。
- 內容扣回用戶輸入的主題/產品/族群；事實不得捏造。
- 每一則都必守：鎖定「一個族群在一個具體情境」說話（用品牌脈絡的主受眾/痛點，audience 要具體不是「全體」除非理念/權威）、整則只打「一個」最強賣點（usp 單一、不要功能清單）、message 要鋪陳到一個可被認出的「Moment of Truth 決定性瞬間」（讀者那一刻確認「這就是我要的」）。遮掉品牌名仍適用競品＝太通用，重寫。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1600,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    // 2026-05-18 (CJ「促銷月曆也超時，分不同 agent 比較快」): replaces
    // the heavy fb-monthly-calendar-product-promo squad with the same
    // fast parallel-by-pillar engine, tuned for multi-product promo.
    id: "fb-99-monthly-calendar-promo",
    tier: "99s", postType: "feed",
    label: "FB 30 天促銷月曆（多商品）",
    description: "結構化促銷月曆：6 產品促銷 / 3 急迫限時 / 2 節慶檔期 / 2 UGC見證 / 1 理念",
    agent_id: 224089,
    skill_slug: "content-calendar",
    primary_question: "本檔促銷主題 + 要推哪些商品（各對誰、各一賣點）？",
    primary_input: { key: "monthly_focus", placeholder: "例：週年慶｜A 產品(忙碌媽媽/省時) + B 產品(小資女/CP值) + C 產品(電商主/多平台)｜檔期 5/20-5/31", type: "textarea" },
    inputs: [
      { key: "monthly_focus", label: "促銷主題 + 商品 + 族群 + 檔期", type: "textarea", required: true },
    ],
    systemPrompt: `你是 FB 促銷月曆策略師。本次**只負責「{label}」這一個支柱**，**只輸出嚴格 JSON 陣列**。

各支柱該產出的則數（只做被指派的「{label}」那組）：
- 「產品促銷」→ 6 則：每則只推「一個商品」、對「一個族群」、講「一個賣點」+ offer
- 「急迫限時」→ 3 則：限時/倒數/最後機會/數量有限，營造急迫但不浮誇
- 「節慶檔期」→ 2 則：扣本檔接近的節慶/檔期
- 「UGC見證」→ 2 則：使用者見證，每則見證「一個商品」溝通「一個賣點」
- 「理念WHY」→ 1 則：促銷檔中的品牌信任錨，講理念不講折扣

【優惠數字｜絕對禁止捏造（最高優先）】
折扣 %、價格、名額（前 N 位）、期限/截止日、贈品、會員權益等具體優惠條件，**只能用「用戶輸入裡明確提供」的**。
- 用戶沒給 → **絕對不可自行編造數字**（不可寫「85 折」「前 100 位」「再 24 小時」等）。改用無數字的急迫框架（例：「檔期內」「名額有限」「把握這次」），或用佔位符「[請填入優惠：例如 X 折／前 N 名／截止日]」讓用戶補。
- 用戶有給 → 逐字沿用，不得放大或更動。

每則物件欄位：
{"day": <1-30 整數>, "pillar": "{label}", "audience": "<對誰說>", "usp": "<單一賣點/offer；理念留空>", "product": "<帶到的商品；理念留空>", "hook": "<前 2 行鉤子 ≤30字>", "message": "<核心訊息 60-110字>", "format": "圖文|短影音|輪播|直播|純文字", "cta": "<行動呼籲 ≤15字>"}

規則：第一個字元就是 [、最後一個就是 ]，不要圍欄/說明；只產「{label}」這組、照對應則數；pillar 一律「{label}」；事實不得捏造。
每一則都必守：鎖定「一個族群在一個具體情境」說話（audience 具體、用品牌主受眾/痛點）、整則只打「一個」最強賣點/offer（usp 單一、非清單）、message 鋪陳到一個可被認出的「Moment of Truth 決定性瞬間」（讀者那刻確認「這就是我要的」）。遮掉品牌名仍適用競品＝太通用，重寫。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1800,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    // 2026-05-18 (CJ「carousel 一個貼文還是只出現一張圖 → 搬到 99s，
    // 真的出 5 張卡圖」): moved from fb-60-carousel-5. A carousel is ONE
    // post made of 5 cards, each with its own image — needs the 99s
    // budget to render 5 card images + copy.
    id: "fb-99-carousel-5",
    tier: "99s", postType: "carousel",
    label: "FB Carousel 5 卡輪播",
    description: "Hook→Build→Turn→Payoff→CTA 敘事弧 + 5 張卡（每卡獨立文案＋專屬圖）",
    agent_id: 180148, // David Chen | Social Media Manager
    skill_slug: "social-copy",
    primary_question: "輪播主題是什麼？",
    primary_input: { key: "topic", placeholder: "輪播 5 卡要傳達的主題", type: "textarea" },
    inputs: [
      { key: "topic", label: "輪播主題", type: "textarea", required: true },
    ],
    systemPrompt: `產出 FB Carousel 5 卡（敘事弧：Hook → Build → Turn → Payoff → CTA）。
caption 是輪播主貼文文（150-250 字 tease 整組要看完）。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1400,
    outputDefaults: { platform: "facebook", post_type: "carousel" },
  },
  {
    // 2026-05-18 (CJ「FB 3 篇連載超時很久，要移到 99s」): moved from
    // fb-60-serial-3 — strategist + 3 episodes + 3 images + per-episode
    // extras is too heavy for the 60s budget (hit the 5-min stale guard).
    id: "fb-99-serial-3",
    tier: "99s", postType: "feed",
    label: "FB 3 篇連載敘事",
    description: "Nelson Chen 設計 3 集弧 + Reed Lee 寫 3 篇有勾連（每集配圖＋產製配套）",
    agent_id: 220752, // Reed Lee
    skill_slug: "social-copy",
    primary_question: "想連載講什麼故事？",
    primary_input: { key: "story_topic", placeholder: "例：客戶轉型 / 團隊成長 / 產品研發歷程", type: "textarea" },
    inputs: [
      { key: "story_topic", label: "連載主題", type: "textarea", required: true },
    ],
    systemPrompt: `產出 FB 3 篇連載其中 1 篇（200-350 字）。
本次你寫的是「{label}」集（第 1 集 / 第 2 集 / 第 3 集）。
- 第 1 集：埋懸念 + 預告下集
- 第 2 集：轉折 + 加深
- 第 3 集：揭曉 / 收束 + 整體 CTA
篇與篇要有勾連（每篇結尾留 1 句鉤子帶到下一篇）。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 900,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    // 2026-05-18 (CJ「也要移動 viral/testimonial」): strategist + specialty
    // (Compare Editor) too heavy for 60s — same 502 risk as trend-rewrite.
    id: "fb-99-viral-rewrite",
    tier: "99s", postType: "feed",
    label: "FB 爆款改寫",
    description: "Kevin Liu 找原爆款結構 + Siyu Li 改寫品牌版 + 對照表（scout 抓同類爆款）",
    agent_id: 60048, // Siyu Li
    skill_slug: "fb-copywriting",
    primary_question: "貼上爆款原文（或連結），我們會分析結構並改寫成你的版本",
    primary_input: { key: "viral_source", placeholder: "貼上原爆款貼文 / 連結 / 主題", type: "textarea" },
    inputs: [
      { key: "viral_source", label: "爆款原文 / 連結 / 主題", type: "textarea", required: true },
      { key: "brand_angle", label: "我方品牌角度（可選）", type: "textarea", required: false },
    ],
    systemPrompt: `產出 FB 爆款改寫文（200-400 字）。
**核心原則**：保留原爆款的「敘事結構 / hook 機制 / 情緒節奏」，但內容換成品牌自己的事。不是抄文字，是學結構。
不要直接複製原文用詞。注意法規 / 抄襲分寸。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    id: "fb-99-testimonial-rewrite",
    tier: "99s", postType: "feed",
    label: "FB 客戶見證改寫文",
    description: "Kurt Chen 找見證結構 + Yawen Ma 改寫敘事 + Jason Evans 法務檢核",
    agent_id: 60026, // Kevin Chiang
    skill_slug: "fb-copywriting",
    primary_question: "貼上原始客戶見證 / 訪談 / 評價",
    primary_input: { key: "testimonial_source", placeholder: "客戶原話、訪談逐字、評論截圖文字", type: "textarea" },
    inputs: [
      { key: "testimonial_source", label: "客戶見證原文", type: "textarea", required: true },
      { key: "consent_status", label: "已取得發布同意？", type: "text", required: false, placeholder: "yes / 匿名化 / 待確認" },
    ],
    systemPrompt: `產出 FB 客戶見證改寫文（200-350 字）。
**核心原則**：保留客戶情感真實感，重組敘事讓重點凸顯。
**法務 / 倫理**：
- 預設匿名化（除非明確標 "yes"），姓名只留首字
- 不要編造客戶沒說過的話
- 數字 / 成效宣稱必須有原文支持
- 結尾不要寫成廣告口吻${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    // 2026-05-18 (CJ「FB 時事改寫文 502」): moved from fb-60-trend-rewrite.
    // strategist (Mark Davis) + specialty (Trend Researcher) + scout +
    // captions ran synchronously past nginx's 60s upstream timeout → 502.
    id: "fb-99-trend-rewrite",
    tier: "99s", postType: "feed",
    label: "FB 時事改寫文",
    description: "Mark Davis 評估時事關聯 + Dale Yu 寫品牌切入點 + 時效性檢核（scout 抓即時時事）",
    agent_id: 220755, // Dale Yu
    skill_slug: "social-copy",
    primary_question: "想搭哪個時事？",
    primary_input: { key: "trend_topic", placeholder: "例：奧運 / AI 新聞 / 季節節日", type: "textarea" },
    inputs: [
      { key: "trend_topic", label: "時事主題", type: "textarea", required: true },
      { key: "brand_angle", label: "品牌切入角度（可選）", type: "textarea", required: false },
    ],
    systemPrompt: `產出 FB 時事改寫文（150-300 字）。
**核心原則**：時事是 hook，品牌是 punchline。前 1/3 講時事，後 2/3 拉回品牌。
**禁忌**：不要假裝你是事件當事人；不要在敏感事件（災難、政治、人命）上消費；不要寫成蹭熱度。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 900,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    // 2026-05-18 (CJ 驗收報告): consolidated countdown — each day is its
    // OWN FB post variant (per-variant pills = 每天一個 FB mockup). Adds
    // the two report fixes: (a) ask 倒數天數 + 截止日 in intake so the
    // agent doesn't have to infer; (b) D-4 起每篇必含可執行 CTA.
    id: "fb-99-14day-countdown",
    tier: "99s", postType: "feed",
    label: "FB 倒數活動系列（7 / 14 天）",
    description: "每天一篇獨立倒數貼文 + 三幕節奏 + D-4 起含可執行 CTA + scout 抓節慶/時事",
    agent_id: 224116, // Hoàng Thị Mai — Email & CRM Strategist eCommerce VN (1251 char)
    skill_slug: "fb-countdown-series",
    primary_question: "活動名稱 + 主要 hook/優惠 + 倒數天數(7或14) + 活動截止日？",
    primary_input: {
      key: "event_name",
      placeholder: "例：OnBrand 年中升級活動｜主 hook：品牌 DNA 固化｜倒數 7 天｜截止日 7/1",
      type: "textarea",
    },
    inputs: [
      { key: "event_name", label: "活動名稱 + hook/優惠 + 倒數天數 + 截止日", type: "textarea", required: true },
    ],
    systemPrompt: `你負責倒數系列的「{label}」這一篇 FB 貼文（80-130 字），這是一篇可直接發佈的 FB 貼文（不是文件）。
依用戶輸入的「倒數天數（7 或 14）」與「截止日」對位三幕節奏：
- 前段（倒數第 7~5 天 / 14~10）：喚醒痛點、埋懸念、教育型，**不硬銷**。
- 中段（第 4~3 天 / 9~5）：示範解法、加溫、情境型。
- 後段（第 2~1 天 / 4~1）：質變展現、緊迫、最後機會。
【CTA 規則（驗收要求，必守）】倒數第 4 天起（含）每篇結尾**必須有一個具體可執行的 CTA**：可點連結指引 / 「留言『關鍵字』取得連結」/ 明確下一步（如「按下升級」）。倒數第 7~5 天可只鋪痛點不放 CTA。
每篇結尾保留記憶錨點「（活動主題，倒數 X 天）」。事實/數字/截止日不得捏造，用戶沒給的用「[請補充：…]」標出。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 700,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    id: "fb-99-launch-toolkit",
    tier: "99s", postType: "event",
    label: "FB 完整 Launch Toolkit (8 篇)",
    description: "預告 ×3 / 當日 / 即時 ×2 / 事後 / 跨平台 IG 改寫 + scout 抓節慶/時事",
    agent_id: 60014, // Cindy Mo | Social Media Marketing (F&B)
    skill_slug: "fb-copywriting",
    primary_question: "活動名稱 + 日期 + 重點？",
    primary_input: { key: "event_name", placeholder: "例：5/20 線上發表會", type: "text" },
    inputs: [
      { key: "event_name", label: "活動名稱", type: "text", required: true },
      { key: "event_when", label: "日期 / 時間", type: "text", required: true },
      { key: "event_why", label: "為什麼參加 / 重點", type: "textarea", required: true },
    ],
    systemPrompt: `本次你負責「{label}」。
- 若「{label}」=「活動總覽」：產出一頁式**活動總覽文件**（Markdown 分段）：① 活動目標與受眾 ② 整體時程與節奏（哪幾天發哪一篇）③ 8 篇貼文各自的主題與角色一覽 ④ KPI 與成效追蹤建議 ⑤ 風險/備案。這是計畫文件，不是貼文，不受字數限制；事實不得捏造，缺的用「[請補充：…]」標出。
- 否則（預告 1/2/3、當日、即時 1/2、事後、IG 跨平台改寫）：產出該篇 FB 貼文（150-300 字），扣回整個 launch arc，前一篇結尾鉤子帶到下一篇。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "facebook", post_type: "event" },
  },
  {
    id: "fb-99-livestream-9seg",
    tier: "99s", postType: "feed",
    label: "FB 直播完整 9 段配套",
    description: "預告 + 開場 + 5 爆點 + 結尾 + 精華回顧 + reel 剪輯指南",
    agent_id: 224154, // Dewi Rahayu — Social Media Strategist Health ID (1135 char)
    skill_slug: "social-copy",
    primary_question: "直播主題 + 重點？",
    primary_input: { key: "live_topic", placeholder: "Q&A / 新品試用 / 直播試吃", type: "text" },
    inputs: [
      { key: "live_topic", label: "直播主題", type: "text", required: true },
      { key: "key_points", label: "預計 3-5 個重點", type: "textarea", required: true },
    ],
    systemPrompt: `產出 FB 直播完整套組其中 1 段（80-200 字依段而異）。
本次你寫的是「{label}」（預告 / 開場宣告 / 爆點 1-5 / 結尾 / 精華回顧 / Reel 剪輯）。
${TONE_100}`,
    preferredModel: "qwen", maxTokens: 900,
    outputDefaults: { platform: "facebook", post_type: "feed" },
  },
  {
    id: "fb-99-crisis-playbook",
    tier: "99s", postType: "comment",
    label: "FB 完整危機公關劇本",
    description: "偵測 + 第一份聲明 + 中期更新 ×3 + 後期 follow-up + 內部 talking points",
    agent_id: 222204, // Chen Jing-Yi — Senior Press Release Writer (1040 char)
    skill_slug: "crisis-communication",
    primary_question: "事件 / 危機內容？",
    primary_input: { key: "incident", placeholder: "完整描述事件 + 已知事實", type: "textarea" },
    inputs: [
      { key: "incident", label: "事件內容", type: "textarea", required: true },
      { key: "facts", label: "已知事實 / 已處理項", type: "textarea", required: false },
      { key: "commitment", label: "可承諾行動", type: "textarea", required: false },
    ],
    systemPrompt: `產出 FB 危機公關完整劇本其中 1 段（200-400 字）。
本次你寫的是「{label}」（偵測警示 / 第一份聲明 / 24h 更新 / 48h 更新 / 72h 更新 / 1 週後 follow-up / 媒體 talking points）。
語氣專業有人味、不推託、扣回 Lagadec 4 段。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "facebook", post_type: "comment" },
  },
];

// ─── IG 100s (3 tasks) ────────────────────────────────────────────────
export const IG_99S_TASKS: FBTaskTemplate[] = [
  {
    id: "ig-99-30day-calendar",
    tier: "99s", postType: "feed",
    label: "IG 30 天內容月曆",
    description: "30 天 feed/reel/story 配比 + 每篇 hook + hashtag 策略 + 真實爆款參考",
    agent_id: 60008, // Fiona Hsieh | Social Media Marketing Strategist (Beauty)
    skill_slug: "instagram-strategy",
    primary_question: "本月主題？",
    primary_input: { key: "monthly_focus", placeholder: "本月主推", type: "textarea" },
    inputs: [{ key: "monthly_focus", label: "本月主題", type: "textarea", required: true }],
    systemPrompt: `產出 IG 30 天月曆其中 1 週（7 天大綱，每天 60-100 字）。
本次你寫的是「{label}」這週。標明每天類型（feed / reel / story / carousel）。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1400,
    outputDefaults: { platform: "instagram", post_type: "feed" },
  },
  {
    id: "ig-99-reel-series-6",
    tier: "99s", postType: "reel",
    label: "IG Reel 6 集系列",
    description: "Strategist 設計 6 集弧 + 每集完整腳本（hook + hold + payoff）+ 縮圖 brief",
    agent_id: 60033, // Yawen Yeh | E-commerce Short Video Scriptwriter
    skill_slug: "short-video-scriptwriter",
    primary_question: "6 集系列主題？",
    primary_input: { key: "series_topic", placeholder: "教學系列 / 故事系列", type: "textarea" },
    inputs: [{ key: "series_topic", label: "系列主題", type: "textarea", required: true }],
    systemPrompt: `產出 IG Reel 6 集系列其中 1 集（300-500 字腳本）。
本次你寫的是「{label}」。每集要有勾連，最後集收束。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "instagram", post_type: "reel" },
  },
  {
    id: "ig-99-account-reposition",
    tier: "99s", postType: "profile",
    label: "IG 帳號重新定位完整套組",
    description: "新 bio + 9 個 highlight 主題 + 9 篇 launch posts + visual direction",
    agent_id: 180141, // Rachel Chen | Social Media Strategy Director
    skill_slug: "instagram-strategy",
    primary_question: "想重新定位的方向？",
    primary_input: { key: "new_direction", placeholder: "想轉成什麼方向 / 受眾", type: "textarea" },
    inputs: [{ key: "new_direction", label: "新方向", type: "textarea", required: true }],
    systemPrompt: `產出 IG 帳號重新定位套組其中 1 部分。
本次你寫的是「{label}」（新 bio / Highlight 1-9 / Launch post 1-9）。
重新定位需要明確、一致、不能跟舊 IG 衝突。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "instagram", post_type: "profile" },
  },
];

// ─── YT 100s (3 tasks) ────────────────────────────────────────────────
export const YT_99S_TASKS: FBTaskTemplate[] = [
  {
    id: "yt-99-series-6ep",
    tier: "99s", postType: "video",
    label: "YT 6 集系列完整製作包",
    description: "6 集 title + description 800-1200 字 + 縮圖 brief 各 3 種 + community 配套",
    agent_id: 224005, // Pin-Chen Lin — YouTube Marketing Strategist 金融科技 (~1000 char)
    skill_slug: "youtube-content",
    primary_question: "6 集系列主題？",
    primary_input: { key: "series_topic", placeholder: "教學/故事/評測 系列主題", type: "textarea" },
    inputs: [{ key: "series_topic", label: "系列主題", type: "textarea", required: true }],
    systemPrompt: `產出 YT 6 集系列其中 1 集（title + description 600-1000 字）。
本次你寫的是「{label}」。每集 SEO 各自最佳化但跟系列扣連。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "youtube", post_type: "video" },
  },
  {
    // 2026-05-19 (Yi-Wen 驗收 v#1 — 12/14):
    // 原 2-行 prompt → Community 月曆驚嘆號/PR 腔、影片 title 裸數字 68%。
    // v#2: Community ✅ 驚嘆號 ✅；但 eMarketer 68% / Competitor 捏造 / hashtag。
    // v#3: eMarketer 68% ✅；但 Marketing Dive 73% / Grammarly-Copy.ai（競品鎖只在 Competitor
    //   tab）/ emoji+驚嘆號遷移至 Tab2 片頭段 / Community 假投票（56%/32%/567票）。
    // v#4: 全 tabs 競品鎖 + Marketing Dive 73% 反例 + emoji 任何位置 + 格式模板。
    //   ❌ 換源第三輪：Adweek 73% + VentureBeat 42%→18%（counterexample 已無效）
    //   ❌ Grammarly/Writer AI 4/5 tabs（模型視為「常識」競品，直接繞過）
    //   ❌ Community 假投票 v#3/v#4 完全相同（固定模板輸出，非隨機，counterexample 無法打破）
    //   ❌ hashtag 惡化（Tab3 5 個 + Tab1/5 #BrandVoiceAI）
    //   ❌ 驚嘆號/emoji 遷移：Tab3「一起期待吧！」🎤+數字emoji / Tab4 🔥
    // 根因：逐輪 counterexample 已達極限。模型在「換源/換 tab/換數字」三軸旋轉繞過。
    //   Community 投票是固定模板，不是隨機捏造，加禁規無效。
    // 修法 v#5（根本策略轉向）：禁止列表 → 嚴格格式模板（prescriptive not prohibitive）：
    //   A: 數字規則 = 邏輯等式（輸入0個% → 輸出0個%）；Community poll 整個輸出結構禁止
    //   B: 競品規則加「即使你認為是業界常見競品（如 Grammarly）…」點破繞過邏輯
    //   E: 每個 tab 提供剛性輸出格式模板 — Community [週次][正文][問題句]，
    //      格式以外的任何元素（emoji/hashtag/poll/片頭段/結尾CTA）物理上沒有位置存在
    id: "yt-99-quarterly-strategy",
    tier: "99s", postType: "video",
    label: "YT 季度頻道策略",
    description: "即時趨勢報告 + 內容支柱 + 12 個 video title + community 月曆",
    agent_id: 224001, // Yun-Hsuan Chen — YouTube Marketing Strategist 服飾時尚 (~1019 char)
    skill_slug: "youtube-strategy",
    primary_question: "頻道主題 + 目標受眾職稱 + 品牌主張 + 競品（四項合填）",
    primary_input: {
      key: "channel_focus",
      placeholder: "例：OnBrand AI YouTube 頻道｜目標受眾：品牌行銷主管 / 中小企業內容策略師｜品牌主張：品牌聲音有溯源憑據，AI 輔助產出不失品牌靈魂｜競品：Jasper AI / Writer / Copy.ai",
      type: "textarea",
    },
    inputs: [{ key: "channel_focus", label: "頻道主題 + 受眾 + 品牌主張 + 競品", type: "textarea", required: true }],
    systemPrompt: `你負責撰寫 YT 季度頻道策略「{label}」這一部分。

══════════════════════════════════════════
【A. 數字規則 — 最高優先】
══════════════════════════════════════════
數輸入原文中「%」符號出現幾次 = N。
你的輸出中「%」符號必須也是 N 個。
輸入通常沒有統計數字，所以輸出也不能有。
媒體名稱（Adweek / eMarketer / Marketing Dive / VentureBeat 等）不能授權你創造不存在的數字，換媒體名稱仍是捏造。
→ 改質化描述：「多數行銷主管把語氣一致性列為優先項目」

影片 title 裡的數字（如「50 個 SaaS 團隊」「減少 70%」）同樣需逐字出現於輸入。

Community 月曆模擬投票數字（「56% / 32% / 12% / 567 票 / 1.2K」）在 v#3 和 v#4 完全相同，是固定模板輸出。v#5 直接禁止輸出任何投票 UI 元件，改用純文字問題句（見 E）。
══════════════════════════════════════════

══════════════════════════════════════════
【B. 競品來源鎖定 — 全文所有 tabs】
══════════════════════════════════════════
全文不得出現用戶輸入未明確點名的競品公司名稱。
即使你認為 Grammarly、Writer AI 是業界公認競品，只要輸入未提，一律不得出現。
這是合規要求，不是風格建議，「常識」不能授權你引用未點名競品。
→ 改泛稱：「同類 AI 寫作工具」「市面品牌語音工具」
Scout 回傳資訊提到某競品 → 仍需輸入中已點名才可引用
══════════════════════════════════════════

【C. 全文禁 hashtag（任何 # 開頭的 tag 詞）】
不得以 # 起頭加社群 tag，包括 #BrandVoiceAI #品牌聲音 #AI工具 等所有形式。
（## 三個以上的 markdown 標題符號不受限）

【D. 品牌聲音 — 所有 tabs 必守】
SoWork 語氣 = 精準守護者、有憑據的科技感。
① 驚嘆號（任何位置）→ 全改句號
② emoji（任何位置，含 🎤 🔥 ✨ 和數字 emoji 1️⃣2️⃣ 等）→ 全刪
③ 爆料腔：「行銷圈最熱的話題」「貼文數暴增 X%」「精彩影片」「一起期待」→ 改具體觀察句
④ 煽動詞：「快來」「把握」「心動不如行動」「讓每一句話…」

【E. 嚴格格式模板 — 每個 tab 按以下格式輸出，格式以外的元素不得出現】

▌內容支柱（label 含「支柱」）
## 支柱 1：[名稱]
說明：[2 句，功能性，無捏造數字，無競品名稱]
受眾痛點：[1 句]

（重複 3-4 次。不要散文導言，不要結尾 CTA，只有上述結構）

▌12 影片 title（label 含「title」）
只輸出 12 行，格式：①[title] ②[title] … ⑫[title]
不要片頭段，不要結尾 CTA，不要 emoji，不要 hashtag，不要驚嘆號。
title 內的數字必須來自輸入。競品名稱必須來自輸入。

▌Community 月曆（label 含「Community」）
每篇貼文嚴格按以下三段格式，格式以外不得添加任何元素：

YYYY年M月D日（週N）｜發布時機：[星期幾 時段]
[正文，純文字，100-180 字，無 emoji，無 hashtag，無驚嘆號，無數字統計，無投票選項]
問題：[一個開放式問題句，不含選項、不含百分比、不含票數]

日期格式說明：用真實的 2026 年月日（例：2026年6月1日（週一））。
從當前月份起算，共輸出 8-12 篇，每篇間隔 5-7 天。
絕對不輸出「A. XX%  B. XX%  票數：XXX」類的投票 UI。
絕對不用「第 N 週 · 貼文 M」這類抽象佔位符。

▌即時趨勢報告（label 含「趨勢」）
## 趨勢 N：[名稱]
觀察：[2-3 句，不含輸入無根據的數字，不含輸入未提的競品名稱]
本頻道應用：[1-2 句具體行動]
（重複 3 條）

【F. 輸出前自查（按順序）】
1. 輸出的「%」數量 = 輸入的「%」數量嗎？多了就刪
2. 有輸入未提的競品名嗎？→ 換泛稱（全文所有 tabs）
3. 有以 # 開頭的 hashtag 嗎？→ 全刪
4. 有驚嘆號嗎？→ 全換句號
5. 有 emoji（含數字 emoji 1️⃣）嗎？→ 全刪
6. Community 月曆每篇是否符合 [週次行][正文][問題句] 三段，且無投票 UI？→ 不符就重排
→ 任一不符，就地改寫再輸出。${TONE_100}`,
    preferredModel: "anthropic", maxTokens: 1200,
    outputDefaults: { platform: "youtube", post_type: "video" },
  },
  {
    id: "yt-99-premiere-kit",
    tier: "99s", postType: "premiere",
    label: "YT Premiere 完整 kit",
    description: "預告影片 + 倒數 community 貼文 + 直播配套 + 精華剪輯指南",
    agent_id: 223995, // Pei-Hsuan Liu — YouTube Marketing Strategist 電商/DTC (1025 char)
    skill_slug: "shorts-scriptwriter",
    primary_question: "Premiere 主題？",
    primary_input: { key: "premiere_topic", placeholder: "首播主題", type: "textarea" },
    inputs: [{ key: "premiere_topic", label: "首播主題", type: "textarea", required: true }],
    // 2026-05-19 (CJ 驗收 v#2 11/14 → v#3 P2): 直播配套開場太導覽介紹腔、
    // 中括號殘留包正文、英文直引號、通過/透過錯字。補品牌聲音 + 排版規則。
    systemPrompt: `產出 YT Premiere kit 其中 1 部分（150-400 字）。
本次你寫的是「{label}」（預告 trailer 腳本 / Community 倒數 ×5 / 直播配套 / 精華剪輯指南）。

【品牌聲音與排版規則（每個部分都適用，輸出前自查）】
- 沉穩觀察者／守護者語氣。開場（特別是「直播配套」）**不要導覽式自我介紹腔**（「歡迎來到」「今天要為大家介紹」），改用一個對品牌行銷主管有共鳴的觀察句或反問句切入。
- 全程繁體中文台灣用字：表達「藉由／經由」時用「**透過**」不要寫「通過」；不要簡體字。
- **中括號 [ ] 只能用於 [請補充：…] 這類待補佔位**。正文句子、CTA、收尾**一律不得用中括號包起來**（壞例：「[計劃首映，直播時我們在評論區見]」→ 直接寫成正常句子）。
- 引號用全形「」或『』，**不要用英文直引號 " "**。
- 收尾語意要通順自然，不要為了金句硬湊（壞例：「不再迷失現身」）；寧可平實也不要拗口。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1100,
    outputDefaults: { platform: "youtube", post_type: "premiere" },
  },
];

// ─── Multi-channel 100s (TT/LI/Email/PR/Brand/Research) ───────────────
export const MULTI_99S_TASKS: FBTaskTemplate[] = [
  {
    id: "tt-99-30day-foryou",
    tier: "99s", postType: "foryou",
    label: "TikTok 30 天 ForYou 配方",
    description: "30 天每天 1 支腳本 + trend 對應 + sound 建議 + scout 抓節慶/時事",
    agent_id: 27, skill_slug: "short-video-script", // Chloe Chen | Short Video Strategist (Beauty)
    primary_question: "本月想衝什麼方向？",
    primary_input: { key: "monthly_theme", placeholder: "教學 / 反差 / 開箱 為主", type: "textarea" },
    inputs: [{ key: "monthly_theme", label: "本月方向", type: "textarea", required: true }],
    systemPrompt: `產出 TikTok 30 天計畫其中 1 週（7 支短腳本，每支 100-150 字）。
本次你寫的是「{label}」這週。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1500,
    outputDefaults: { platform: "tiktok", post_type: "foryou" },
  },
  {
    id: "tt-99-trend-week",
    tier: "99s", postType: "foryou",
    label: "TikTok 1 週追熱點完整套組",
    description: "7 天每天 1 個 trend + 品牌 hook + 3 種 hook 變化 + sound 建議",
    agent_id: 220507, skill_slug: "short-video-script", // Pin-Yen Liu — Short-form Video Producer Beauty
    primary_question: "想搭哪類熱點？",
    primary_input: { key: "trend_focus", placeholder: "節日 / meme / 新聞", type: "textarea" },
    inputs: [{ key: "trend_focus", label: "熱點類型", type: "textarea", required: true }],
    // 2026-05-19 (CJ 驗收 7/14「品牌一致性 0」根因): 原 2-行 prompt 無
    // 任何品牌聲音 guardrail。「追熱點」框架本身帶高能量 FYP 預設，模型
    // 直接以 TikTok 網紅帶貨腔填充，把 SoWork 守護者敘事完全蓋掉，
    // 驚嘆號 / 「宇宙無敵」/ 「快來試試」/ 捏造效益集體爆發。
    // 修法：明確品牌聲音 + 反差鉤起手 + 禁語 + 漏斗暖身（依 CJ 四點）。
    systemPrompt: `產出 TikTok 追熱點 1 天的腳本（200-400 字）。本次你寫的是「{label}」這天。

【品牌聲音 — 最高優先，違反即整篇不合格（追熱點最容易崩，輸出前逐條自查）】
1. 你是「沉穩的觀察者 / 守護者」，不是帶貨網紅。追熱點＝用一個冷靜的提問把熱點翻成品牌的觀點，**不是**蹭流量喊話。
2. **全文禁句尾驚嘆號**（! 與 ！都禁，連「快來分享吧！」這種收尾都不行，改成句號的陳述或提問）。
3. **禁帶貨／浮誇／效率詞**：「快來試試」「趕快試試看」「大放異彩」「宇宙無敵」「超神奇」「業界佼佼者」「亮起來」「不再擔心」「提升效率」「行銷新篇章」「一起來討論吧」等一律不准出現；也不要 emoji 開場。
4. **起手必須是「觀察者提問」不是品牌廣告**：第一句先點出大家正在熱議的這個熱點現象，用一個反差問題切入，**不要**第一句就推 OnBrand 功能。
   反差鉤範例語感：「大家都在說 AI 工具很強，但很少有人問——它有沒有在用『你的品牌邏輯』在說話？」
5. **漏斗對位**：Day 1-2 是 Awareness 暖身（只談現象與觀點，品牌只作為「提出這個問題的人」自然帶過，不 push 功能）；越後面才逐步帶到品牌怎麼回應這個問題。不要每天都直接推銷功能。
6. **不捏造效益 / 數據**：沒有來源的「瀏覽量上升」「企業用戶成長」一律不准寫；要講效果就講「它在做什麼」而非「它有多神」。缺具體事實用「[請補充：例如 實際案例]」標出。
7. 受眾是品牌行銷主管 / 經營者（B2B 場景），不是一般消費者，措辭對齊專業決策者。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1000,
    outputDefaults: { platform: "tiktok", post_type: "foryou" },
  },
  {
    // 2026-05-19 (Yi-Wen 驗收 v#1 — 12/14):
    // 原 2-行 prompt 無格式規定、無品牌聲音 guardrail →
    // 第 2-3 週驚嘆號回流、散文腔（「如歌般悠揚」「情感連結又跑掉了！」）、
    // 第 3 週捏造 SaaS 100億美元統計無來源。
    // 問題設計 placeholder 「AI / 領導力 / SaaS 等」太精簡，導致 agent 缺乏
    // 月份主題、受眾職稱、品牌主張，只能 week 1 撐全場。
    // v#2 (12.5/14): 驚嘆號/散文腔已清除，仍剩兩個 P1：
    //   (1) Hook 裸數字（Week 1 的 67% 無來源——偏偏是最需要衛生的位置）
    //   (2) Week 2-3 CTA 問句退化成泛問題
    //        壞例：「你的品牌是否已在這樣的變革中找到了方向呢？」
    //        好例（Week 1 水準）：「你現在的品牌內容，有多少是按照品牌定位產出的？
    //              還是 70% 都是『趕稿戰士模式』？」
    //   (3) Week 2-3 PR腔殘留：「在這個數位時代品牌必須與時俱進」「持續發光」
    // 修法：(1) 統計數據硬規則擴充至 hook；(2) 結尾問句品質規則；(3) 增加禁詞。
    id: "li-99-30day-thought-leadership",
    tier: "99s", postType: "feed",
    label: "LI 30 天 Thought-Leadership 月曆",
    description: "30 天 = 10 觀點 / 10 案例 / 10 趨勢預測 + scout 抓即時節慶",
    agent_id: 222342, skill_slug: "linkedin-b2b", // Hung Ya-Wen | Social Media Strategist – B2B SaaS
    primary_question: "這個月想立什麼專業 image？（月份 + 核心主題 + 目標受眾職稱 + 你的品牌主張，四項合填）",
    primary_input: {
      key: "expertise_area",
      placeholder: "例：5月｜AI 品牌一致性｜目標受眾：品牌行銷主管 / 內容策略師｜品牌主張：品牌聲音不因速度而失真，每一篇 AI 產出都有溯源憑據",
      type: "textarea",
    },
    inputs: [{ key: "expertise_area", label: "月份 + 主題 + 受眾職稱 + 品牌主張", type: "textarea", required: true }],
    systemPrompt: `你負責撰寫 LinkedIn Thought-Leadership 月曆「{label}」這一週的主力貼文（1 篇完整 Feed 貼文，非大綱）。

【格式｜必守】
- 長度：150-350 字（中文字符計算）
- 結構：強 hook（前 2 行）→ 論述 / 案例 / 數據 → 結尾互動問句（1 句）
- Hashtag：結尾附 4-5 個，無空格（如 #品牌策略 #AIMarketing）
- 不要段落標題 / 不要 markdown / 不要條列

【每週 hook 角度 — 不得跨週混用】
- 第 1 週（Why / 痛點框架）：以受眾親身痛點切入，「凌晨兩點、趕稿交件」式具體情境，不要空泛起手
- 第 2 週（What / 案例解析）：真實或高度可信的案例，說清楚「這個方法如何解決上週的痛點」，不堆術語，不用 PR 腔開場
- 第 3 週（How / 方法拆解）：3 步驟以內的具體操作邏輯，讀者當場拿走一個可用 insight，不用時代/變革/發光等空洞收尾
- 第 4 週（So What / 趨勢主張）：品牌主場景的趨勢預測，基於輸入資料推論，有明確立場（非「也許可能」）

【統計數據硬規則 — hook 行最嚴格】
★ Hook（前 2 行）裡若出現百分比 / 數字，**必須在同一行內附上來源**（如「根據 Edelman 信任報告，67%…」）。
★ 正文中任何不在輸入中的數字 → 一律用「[請補充：研究來源]」標出。
★ 「最新研究顯示」「數據顯示」等籠統引用，不算有來源，補來源機構名稱或改成 [請補充]。
✗ 違反例（v#2 Week 1 踩過）：「67% 的消費者更信任聲音一致的品牌—— 但大多數行銷團隊根本做不到。」（67% 無來源 = 不衛生）

【品牌聲音 guardrail — 四週必守，違反即不合格】
SoWork 語氣 = 「精準守護者、有憑據的科技感」，不是散文，不是媒體公關腔。
逐條禁止（v#1 + v#2 踩過的錯誤，原詞禁止）：
- 驚嘆號結尾（任何句子）→ 改句號
- 散文腔：「如歌般悠揚」「讓每一句話都…」「持續發光」「走出桎梏」
- PR / 教授腔開場：「在這個數位時代，品牌必須與時俱進」「隨著科技演進」→ 改成具體情境句
- emoji（任何）、hashtag 混入正文

【結尾互動問句品質規則 — 四週必守】
結尾問句必須讓讀者能「對號入座」回答，不能泛問。
✗ 壞例（v#2 Week 2-3 踩過）：「你的品牌是否已在這樣的變革中找到了方向呢？」（無具體情境，B2B 主管無法回答）
✓ 好例（Week 1 水準）：「你現在的品牌內容，有多少是真的按照品牌定位產出的？還是 70% 都是『趕稿戰士模式』？」
規則：問句要鎖定「受眾當前的具體困境或選擇題」，不問「是否有方向」「是否認同」等虛問。

【寄出前自我檢查｜必做】
1. Hook 前 2 行：有數字就有來源（Edelman / Forbes / 輸入資料）？
2. 本週角度（Why/Case/How/Trend）與 {label} 對應？
3. 驚嘆號全換句號？有未標來源的數字？PR 腔開場換掉？
4. 結尾問句夠具體、讀者能對號入座回答？
→ 任一不符，就地改寫再輸出。${TONE_100}`,
    preferredModel: "anthropic", maxTokens: 1300,
    outputDefaults: { platform: "linkedin", post_type: "feed" },
  },
  {
    // 2026-05-19 (Yi-Wen 驗收 v#1 — 13/14):
    // 品牌聲音穩定，受眾切入精準（溯源三問、三人小團隊）。
    // v#2 (10/14) — 嚴重退步：捏造數字+植入馬來西亞市場。
    // v#3 — 地域鎖定 ✅；驚嘆號第3期 1 處殘留；新漏洞「偽具名」。
    // v#4 — 驚嘆號 ✅；地域重大退步（第3期+進階版 吉隆坡/MOH/Shopee MY）；
    //   「78%」固定幻覺：封 Marketing Dive → 換 Adweek 繞過，相同數字。
    //   根因1：規則攻防是「有無來源名稱」→ 模型找新媒體名繞過。
    //   根因2：SoftLink MY 的 MY 後綴被模型當地域授權訊號 → 解鎖馬來西亞情境。
    // 修法 v#5：
    //   (1) 規則 ① 重寫：「數字本身是否逐字出現在輸入原文」，完全移除
    //       「有無媒體名稱」概念——因為模型會換媒體名繞過。
    //       改成「掃描輸入原文字串，找到這個數字了嗎？找不到 → 刪掉，改質化描述」。
    //   (2) 地域規則新增：「公司名後綴（MY/TW/JP）不代表地域授權；
    //       SoftLink MY ≠ 可提及吉隆坡/檳城/Bahasa Malaysia/MOH/Shopee MY」。
    //   (3) hashtag 改為「所有期（含第1期）全文禁 # 字符」。
    id: "li-99-newsletter-quarterly",
    tier: "99s", postType: "newsletter",
    label: "LI 季度 Newsletter 4 期",
    description: "季度 4 期 newsletter 完整內容 + 訂閱成長策略",
    agent_id: 60062, skill_slug: "linkedin-b2b", // Nathan Lu | Media Newsletter Copywriter
    primary_question: "季度大主題 + 各期子題 + 目標讀者行動 + 品牌主張（四項合填）",
    primary_input: {
      key: "quarter_topic",
      placeholder: "例：Q2 品牌一致性｜第1期 為什麼AI寫的稿讀起來像別人的 / 第2期 溯源三問：語氣怎麼來的 / 第3期 三人小團隊如何做到品牌一致 / 第4期 升級到 Pro 解鎖進階分析｜目標行動：讀完每期都能帶走 1 個可立刻執行的 insight｜品牌主張：品牌聲音有據可循，不因速度失真",
      type: "textarea",
    },
    inputs: [{ key: "quarter_topic", label: "季度主題 + 各期子題 + 目標行動 + 品牌主張", type: "textarea", required: true }],
    systemPrompt: `你負責撰寫 LinkedIn 季度 Newsletter「{label}」這一期（第 1 期 / 第 2 期 / 第 3 期 / 第 4 期）。

══════════════════════════════════════════
【A. 數字零容忍規則 — 最高優先，違反直接不合格】
══════════════════════════════════════════
寫作前先做一件事：把用戶輸入完整讀一遍，記住哪些數字出現在原文裡。

▸ 規則（只有一條）：
  全文任何「百分比 / 次數 / 得分 / 比率」數字，必須逐字出現在用戶輸入原文中。
  沒有在輸入原文找到 → 刪掉這個數字，改成質化描述，或留 [請補充：數據來源]。
  媒體名稱（Adweek / Marketing Dive / Forrester…）不能作為數字的授權依據。
  ✗ 違反例（v#2）：「42%的品牌行銷人員表示」（輸入無此數字）
  ✗ 違反例（v#3）：「Marketing Dive 數據：60%」（輸入無此數字，附媒體名稱無效）
  ✗ 違反例（v#4）：「Adweek 最新調查：78%」（輸入無此數字，換媒體名稱同樣無效）
  ✗ 違反例（v#4）：「語氣一致性得分 68%→52%」（OnBrand AI 無此指標）
  ✓ 正確：「多數品牌行銷主管反映…」「品牌一致性問題正在引發行銷圈關注…」

▸ 數字自我驗證步驟（寫完後執行）：
  找出全文所有帶「%」「次」「得分」「倍」的句子 → 對照輸入原文 → 找不到 → 刪改。
══════════════════════════════════════════

══════════════════════════════════════════
【B. 地域零容忍規則 — 同等優先，違反直接不合格】
══════════════════════════════════════════
▸ 規則：只能提及輸入原文中明確出現的城市、國家、語言、市場名稱。
  輸入無地域 → 全文不得出現任何城市/國家/語言/監管機構/在地平台名稱。

▸ 重要：公司名後綴（MY/TW/JP 等）不代表地域授權。
  ✗ 違反例（v#2/v#4）：SoftLink MY → 不等於可以提及吉隆坡、檳城、
    Bahasa Malaysia、MOH 合規、Shopee MY 等任何馬來西亞語境。
  ✓ 正確：以「SoftLink MY 的內容團隊」稱呼，不展開地域情境。

▸ 地域自我驗證步驟：全文搜尋城市名/語言名/監管機構 → 對照輸入 → 找不到來源 → 刪改。
══════════════════════════════════════════

【C. 格式｜必守】
- 長度：500-800 字（中文字符計算）
- 結構：標題（≤20 字）→ 副標（1 句）→ 正文（論述/案例/操作邏輯）→ 結尾 CTA 或下期預告
- 期與期有主題連貫性（引用前期框架、為下期埋梗）
- 全文（第 1 期至進階版，每一個 variant）不得出現任何 # 字符（LinkedIn Newsletter 非 Feed，無 hashtag）
- 不要 markdown 粗體 ** / 不要行首 # 標題

【D. 台灣中文用語】
- 「透過」而非「通過」（表示方法/途徑）
- 「內容」而非「内容」（正體字）

【E. 品牌聲音 guardrail — 四期必守，違反即不合格】
SoWork 語氣 = 「精準守護者、有憑據的科技感」，深度論述但不煽情。
逐條禁止：
- 驚嘆號（任何句子，含數字後 "60%！"）→ 全改句號，無例外
- 旅程敘事：「艱辛卻令人期待的旅程」「一起走過」→ 改具體行動
- 語法不通：「從單純快速產出自由」「讓XXX兼具…」
- emoji（任何）
- 散文腔：「如歌般悠揚」「持續發光」

【F. 每期 hook 角度 — 依 {label} 對應】
- 第 1 期（Why / 問題框架）：揭示讀者「習以為常其實有問題」的現象，第一句是讀者自我認出的 moment
- 第 2 期（What / 解法機制）：說清楚解決方案的具體機制，一個功能說清楚，不堆功能清單
- 第 3 期（How / 落地實踐）：小團隊 / 中小品牌如何用最少資源落地，讀者可帶走的操作框架
- 第 4 期（So What / 升級/預告）：展示前幾期邏輯積累，升級邀請或 Q3 預告；成效數字無輸入 → [請補充]

【G. 結尾問句品質規則】
結尾問句須讓讀者對號入座能具體回答，不泛問「準備好了嗎」「是否有方向」。
✗ 壞例（v#3+v#4 踩過）：「你的品牌準備好了嗎？」「你是否也在考慮…」
✓ 好例：「你現在的內容審核流程，有沒有能追溯到品牌聲音來源的機制？」

【H. 寄出前自我檢查｜必做】
1. 【數字】全文帶「%」「次」「得分」「倍」的句子 → 逐一對照輸入原文 → 找不到 → 刪改
2. 【地域】全文有城市/語言/監管機構名稱嗎？→ 對照輸入 → 找不到 → 刪改
3. 【驚嘆號】全文有「！」「!」嗎？→ 全換句號
4. 【hashtag】全文有「#」嗎？→ 全刪
5. 標題 ≤20 字，結尾問句具體？
→ 任一不符，就地改寫。${TONE_100}`,
    preferredModel: "anthropic", maxTokens: 1200,
    outputDefaults: { platform: "linkedin", post_type: "newsletter" },
  },
  {
    // 2026-05-19 (Yi-Wen 驗收 v#1 — 9/14 分, 4維度剛好過門檻):
    // 原 2-行 prompt 無格式規定 → 三封相同主旨、無 CTA 差異、品牌聲音漂移。
    // 問題設計 placeholder 過於抽象 → agent 無週次主題資訊，無法分工主旨。
    // 完整重寫 prompt（對照 em-99-launch-sequence 工法）+問題+orchestra 修復。
    id: "em-99-4week-nurture",
    tier: "99s", postType: "edm",
    label: "Email 4 週 Onboarding Nurture",
    description: "4 週 onboarding：第1週 Why / 第2週 What / 第3週 How / 第4週 Deepen",
    agent_id: 224161, skill_slug: "email-marketing", // Xenia Anggraini — Email & CRM Strategist Beauty ID
    primary_question: "品牌/產品名稱 + 目標受眾職稱 + 4 週各週主題 + 核心功能名稱（四項一起填）",
    primary_input: {
      key: "value_prop",
      placeholder: "例：OnBrand AI — 讓品牌聲音不因速度失真｜受眾：品牌行銷主管 / 內容策略師｜第1週 為什麼品牌一致性對你很重要 / 第2週 品牌腳色設定讓 AI 真的懂你 / 第3週 用溯源注解功能產出第一篇內容 / 第4週 解鎖進階分析 升級 Pro｜功能名稱：溯源注解、品牌字典對照、品牌腳色設定",
      type: "textarea",
    },
    inputs: [{ key: "value_prop", label: "品牌名 + 受眾 + 4週主題 + 功能名稱", type: "textarea", required: true }],
    systemPrompt: `你負責這封 4 週 Onboarding Nurture email「{label}」（第 1 週 / 第 2 週 / 第 3 週 / 第 4 週）。這是一封可直接寄出的 EDM。

【輸出格式｜必守】**前三行**一定是這三行，純文字（不要 markdown 粗體 **、不要 # 標題、行首不要符號）：
主旨：<8-22 字，本週專屬主旨，必須反映本週主題，不得與其他週重複>
預覽：<30-50 字 preview text，不含 stage label（不要寫「第 X 週」「第一封」等內部標記）>
CTA：<本週 CTA 按鈕文字，依下方週次規則，≤8 字>
（空一行後）<信件本文 200-400 字>

【主旨差異化硬規則 — 違反即不合格】
每週主旨必須各異，且與該週核心主題直接掛鉤。每週的 hook 角度如下，不得互換：

- 第 1 週主旨（Why / 痛點）→ 以「為什麼」或「你是否…」開頭，聚焦受眾真實痛點
  ✔ 正例：「為什麼你的 AI 文案，讀起來總像是別人寫的」
  ✗ 禁止：第 2/3/4 週使用這個 hook 角度

- 第 2 週主旨（What / 功能介紹）→ 聚焦「品牌腳色設定 / 讓 AI 真的讀懂你的品牌風格」（功能引導，不是問句）
  ✔ 正例：「品牌腳色設定：讓 AI 學會你說話的方式」
  ✗ 禁止：以「為什麼」開頭（那是第 1 週的 hook）；不得與第 1 週主旨相同或近似

- 第 3 週主旨（How / 第一次行動）→ 聚焦「你的第一篇 AI 產出 / 看到成果那一刻」（行動引導，動詞開頭）
  ✔ 正例：「產出你的第一篇品牌文案，只要三步驟」
  ✗ 禁止：以「為什麼」或「品牌腳色」開頭

- 第 4 週主旨（Deepen / 升級）→ 聚焦「解鎖更多 / 升級 / 品牌一致性的下一階段」（升級勾引）
  ✔ 正例：「你已產出第一篇——現在解鎖進階分析」
  ✗ 禁止：重複前三週任何主旨或 hook 角度

**同一句主旨（或同一個 hook 角度）出現在超過一封 = 不合格，必須重寫**
**特別檢查：你的第 2 週主旨不可以是「為什麼…」句型，也不可以和第 1 週主旨相同**

【CTA 週次差異化｜必守，寫進 CTA：行】
- 第 1 週：低摩擦認識 → 「了解 OnBrand」
- 第 2 週：功能設定 → 「設定我的品牌腳色」
- 第 3 週：產出行動 → 「產出第一篇內容」
- 第 4 週：升級 → 「升級解鎖更多」

【週次內容骨架｜本週寫什麼】
- 第 1 週（Why / 信任建立）：點出受眾真實痛點（具體情境，不是業配語）→ 說明為什麼品牌一致性是解方 → CTA 引導了解平台，不推功能清單
- 第 2 週（What / 核心功能）：介紹品牌腳色設定 / 品牌字典功能的具體機制 → 一個功能說清楚，不堆功能清單 → CTA 引導設定動作
- 第 3 週（How / 第一次行動）：鼓勵產出第一篇內容 → 說明用溯源注解功能確認品牌一致性的流程 → CTA 推動動手
- 第 4 週（Deepen / 升級）：展示進階用法或數據回顧 → 升級邀請或專屬優惠（有才寫，沒有輸入就標 [請補充：優惠內容]）→ CTA 升級

【品牌聲音 guardrail — 四封跨週一致，違反即不合格】
SoWork 語氣＝「精準守護者、有憑據的科技感」，不是散文、不是煽情。
逐條禁止（v#1 踩過的錯誤，原詞禁止）：
- 文學/煽情腔：「如歌般悠揚」「熙來攘往」「走出…桎梏」「在…的世界裡」「讓每一句話…」
- 語法不通組合：「既速且具一致性」「讓XXX兼具…」此類中西混用
- emoji（任何，含 💡 ✨ 🚀）
- 驚嘆號結尾（含「！」「!」）— 全部換成句號
- 行銷業配煽動：「快來體驗」「心動不如行動」「別再猶豫」「趕快加入」
- hashtag（EDM 不是社群，不得出現任何 #標籤）
- 效率詞：快／高效／省時（空洞，改用具體動作或數據）
【寄出前自我檢查｜必做】送出前依序確認：
1. 前三行是「主旨：」「預覽：」「CTA：」，純文字，無粗體 ** 無 # 無行首符號
2. 若本封是第 2 週：主旨【不以「為什麼」開頭】且【不與第 1 週主旨相同或近似】
3. 品牌聲音違禁詞（emoji、驚嘆號、快來體驗、別再猶豫等）全部已改
4. 功能名稱逐字忠實（溯源注解、品牌腳色設定…）
如發現任何一條不符 → 立刻就地改寫，不要交出違規版本

【功能名稱忠實規則】
輸入怎麼寫就怎麼用，逐字沿用，不得自行改字：
- 「溯源注解」不可寫成「溯源**註**解」
- 「品牌一致性溯源證」不可縮寫成「溯源憑證」
- 輸入沒有的日期、數字、優惠一律標「[請補充：…]」，不捏造

【依輸入解析】從輸入抓「目標受眾職稱」「4 週主題」「功能名稱」；信中點名受眾真實情境（不泛化成「所有人」）。${TONE_100}`,
    preferredModel: "anthropic", maxTokens: 1000,
    outputDefaults: { platform: "email", post_type: "edm" },
  },
  {
    id: "em-99-launch-sequence",
    tier: "99s", postType: "edm",
    label: "Email 產品上線完整自動化 Sequence",
    description: "預告 ×2 / 上線 / 提醒 ×2 / 最後機會 / 後續 follow-up = 7 封",
    agent_id: 60061, skill_slug: "email-marketing", // Yahan Tsai — Retail E-commerce Newsletter Copywriter
    // 2026-05-18 (CJ 驗收 P0): 原本只問「產品名+賣點」→ 主旨空白、CTA
    // 不分階段、最後機會/follow-up 無從設計。四項合一引導 textarea。
    primary_question: "產品名+賣點 + 目標受眾 + 上線日期 + 早鳥/限時機制 + 發送間隔？",
    primary_input: {
      key: "product",
      placeholder: "例：品牌一致性溯源證｜每次 AI 產出自動附品牌字典對照｜受眾：品牌行銷主管/內容策略師｜上線 7/1｜早鳥前 100 名免費｜每 2 天發一封",
      type: "textarea",
    },
    inputs: [{ key: "product", label: "產品+賣點+受眾+上線日+早鳥+發送間隔", type: "textarea", required: true }],
    systemPrompt: `你負責這封 Email launch 序列信「{label}」（預告 1 / 預告 2 / 上線 / 提醒 1 / 提醒 2 / 最後機會 / 後續）。這是一封可直接寄出的 EDM。

【輸出格式｜必守】**前三行**一定是這三行，且為**純文字**（不要 markdown 粗體 ** 、不要 # 標題、行首不要任何符號）：
主旨：<8-22 字、能決定開信率，無驚嘆號>
預覽：<30-50 字 preview text>
CTA：<本封按鈕文字，依下方階段規則，≤8 字>
（空一行後）<信件本文 200-400 字>

【主旨/預覽/CTA 絕對不可省略或留空、不可包成 markdown】沒有它整封信無法使用；系統會逐行解析這三行。

【依輸入解析】從輸入抓「目標受眾」「上線日期」「早鳥/限時機制」「發送間隔」；信中該點名受眾情境（不要泛化成「所有品牌」）。**輸入沒給的用「[請補充：上線日期]」這類標出，不要自行假設或捏造日期/數字/優惠**。產品/功能名稱**逐字沿用輸入**，不得改字（例：「溯源證」不可寫成「溃源證」）。

【CTA 依階段差異化｜必守，寫進上面的 CTA：行】
- 預告 1/2：低摩擦 → 「搶先看」或「加入候補」
- 上線：「立即體驗」
- 提醒 1/2：緊迫 → 「立即鎖定」或「剩 X 天」（X 依輸入截止；沒給用「立即鎖定」）
- 最後機會：「最後機會」或依輸入早鳥（沒給不編數字）
- 後續：re-engagement → 「為你留了位子」

【品牌調性 guardrail｜每一封都適用（含上線/提醒/最後機會），違反即不合格】
維持 SoWork 守護者、創造者語氣。**逐條禁止**：
- emoji（任何，含 💡 ✨ 🚀）
- 任何句子以驚嘆號收尾（含「！」「!」）— 含「心動不如行動！」「別再猶豫！」「搶先看！」等，全部換成句號
- 促銷煽動句（以下原詞均禁止）：「快來體驗」「快來搶先體驗」「趕快來加入」「不要錯過了」「立即搶購」「心動不如行動」「別再猶豫」「快來加入」
- 純效率詞：快／高效／省時
- hashtag：EDM 不是社群，**全文不得出現任何 #標籤**
- 與其他封句式雷同（尤其別重複上線封的核心句）
- 預覽文字（第 2 行）不得夾帶 stage label（如「提醒 1｜」「最後機會｜」「預告｜」等內部分類詞），預覽文字只給訂閱者看，不需要知道這是第幾封
【寄出前自我檢查｜必做】送出前掃一遍：出現 emoji／句尾驚嘆號／上述促銷句 / #標籤 / 效率詞 / 預覽夾 stage label → **就地改寫再輸出**，不要交出違規版本。${TONE_100}`,
    preferredModel: "anthropic", maxTokens: 1000,
    outputDefaults: { platform: "email", post_type: "edm" },
  },
  {
    // 2026-05-19 (Yi-Wen 評測修復):
    // 1. primary_question 擴充：原只問「Launch 主題」，導致 agent 缺乏目標媒體、
    //    發言人姓名/職稱、embargo 資訊，只能腦補（杜撰 70% 統計數字、泛化發言人）。
    //    現在四項合一，placeholder 帶範例讓填寫不費力。
    // 2. systemPrompt 新增四條硬規則：
    //    a. 反杜撰：統計數字沒有來源一律 [待補]，絕不捏造。
    //    b. 發言人：從輸入提取姓名+職稱；無則 [待補]，不寫「創辦人表示」。
    //    c. 受眾適配：Headline 從記者的讀者角度（新聞性）切入，非品牌 WHY。
    //    d. Q&A 格式：嚴格 Q：/A：結構 6-8 組，禁止段落敘述取代。
    //    e. 功能名稱校正：輸入中明顯形似字錯誤（溌/溃→溯）標注並全篇用正確字。
    //    f. 媒體聯絡結尾：沉穩守護者調性，禁業配腔。
    id: "pr-99-launch-toolkit",
    tier: "99s", postType: "press",
    label: "PR 完整 Launch 媒體 Toolkit",
    description: "新聞稿 + 採訪問答 + 媒體聯絡話術 + 後續追蹤 + spokesperson talking points",
    agent_id: 223197, skill_slug: "pr-writing", // Yi-Wen Wu — PR Strategist B2B SaaS (476 char)
    primary_question: "Launch 主題 + 目標媒體類型 + 發言人姓名職稱 + 發稿時機（四項一起填）",
    primary_input: {
      key: "launch_topic",
      placeholder: "例：推出「品牌一致性溯源證」新功能；目標：數位時代、TechOrange（科技媒體）；發言人：CJ Wang，Founder & CEO；embargo：2026-06-01 10:00 AM",
      type: "textarea",
    },
    inputs: [{ key: "launch_topic", label: "Launch 主題 + 目標媒體 + 發言人 + 時機", type: "textarea", required: true }],
    systemPrompt: `══════════ 開始寫作前必讀：數字核對 + 驚嘆號禁令 ══════════
你即將寫「{label}」。動筆前完成以下兩個協議，違反任一即輸出不合格。

【A. 數字核對協議 — 寫每一句前執行，無例外】
① 先掃 launch_topic，把用戶明確給的數字/百分比/案例記下來（通常很少，甚至沒有）。
② 你要寫的句子含有數字、百分比、倍數、調查結果、成效數據、「某品牌/某用戶」匿名案例嗎？
   → 「有」：這個數字/案例在 ① 的清單裡嗎？
       → 在：可以寫，並標明來源。
       → 不在：把它改成 [待補：數據來源] 或改用完全質化的敘述，禁止寫原數字。
   → 「沒有」：繼續正常寫。
③ 特別警示場景（出現即自動違規）：
   - 「75% 的行銷人認為…」「根據我們研究…」「某品牌提升了 30%」— 用戶沒給，不可寫，改 [待補：數據來源]
   - 「根據內部測試」「根據最新調查」「業界研究指出」— 均屬杜撰，改 [待補：數據來源]
   - 匿名成效案例（「某客戶」「一家中小企業」+成效數字）— 完全刪除或改成 [待補：真實案例來源]

【B. 驚嘆號禁令 — 全文零容忍】
全文禁止驚嘆號（！/!），包括：
   - 正文任何句子：「這更是行業中的一大創新！」→ 改為「這是行業中的重要進展。」
   - 結尾語句：「謝謝！」「期待合作！」「感謝！」→ 全部刪除，改為具體的 next step 句子。
     （正確結尾範例：「如需進一步資料或安排專訪，歡迎回信確認時段。」）
   - 禁止任何以「謝謝」「感謝」「期待」開頭的收尾句。
══════════════════════════════════════════════

本次你寫的是「{label}」，產出 PR launch toolkit 其中 1 部分。
【得獎工藝參考】Whopper Detour（Burger King / FCB，Cannes Lions 2019）：整套之所以拿獎，是「一個新聞鉤」貫穿所有素材——新聞稿、pitch、社群、採訪問答，講的是同一個不可抗拒的角度，互相加乘而非各說各話。

【字數硬規定】
- 「新聞稿」：總字數 ≥ 700 中文字；Body ≥ 3 段每段 ≥ 80 字；Headline 完整語句，絕不以省略號結尾。
- 「採訪問答」：6–8 組；每個 A ≥ 60 字。
- 「媒體聯絡」：≥ 250 字，Subject + 開場 + angle + offer + 結尾全部完整。
- 「後續追蹤」：≥ 300 字，3 波段策略完整呈現。
- 「Spokesperson talking」：≥ 400 字，≥ 5 個 talking point 各附支撐說法。
結構完整前不可截斷，即使已達 500 字也繼續寫到收尾。

【earned-media 工藝 — 每一部分都適用】
- 先找「新聞鉤」：這個 launch 為什麼值得被報導？最強角度是什麼？整套 toolkit 圍繞同一個鉤。
- 通過記者測試：用可查證事實（名字/日期/第三方背書）贏得關注，不用形容詞宣稱。
- 扣文化與時機：點出「為什麼是現在」，連結此刻受眾已在乎的事。
- 倒金字塔、客觀第三人稱；句子寫成記者能原句引用。
- 禁 buzzword、「業界領先／顛覆」、「我們很高興宣布」、暖身式開頭。

【發言人引述規則】
從 launch_topic 提取發言人姓名＋職稱。未提供 → 寫「[待補：發言人姓名 + 職稱] 表示」，不寫「OnBrand AI 創辦人表示」。

【受眾定向規則 — 新聞稿 Headline 最關鍵】
識別目標媒體類型，Headline 從「記者的讀者」角度切入：這件事為什麼是新聞？禁止暖身式 headline。

【功能/產品名稱校正】
輸入有形似字錯誤（例：溌→溯）→ 首次出現時括號標注，此後全篇用正確字。

【各部分專屬格式硬規定】
【全文禁止 Markdown 格式符號】## / # / ** / __ / --- / \`\`\` 等符號一律禁止，改用純文字標題與換行分段。新聞稿是給記者看的排版文件，不是 Markdown 文件。
- 「新聞稿」：Headline（≤25字，主動語態，記者視角，完整語句不加省略號）→ Dateline（格式：【城市，{today}】，**必須使用此確切日期，不可自行猜測年份**）→ Lead（5W 倒三角，首句 ≤35字）→ Body（≥3段，每段 ≥80字）→ 發言人引言（姓名+職稱，引號，≥60字）→ 關於 OnBrand AI（Boilerplate ≥80字）→ 媒體聯絡欄（聯絡人/電話/email）。
- 「採訪問答」：嚴格 6–8 組，格式：
    Q：<記者真實尖銳問題，含最不想被問的點>
    A：<≥60字；首句直接答問題；數字/調查/成效若輸入未給 → [待補：數據來源]>
  （組間空一行，不加編號）
- 「媒體聯絡」：Subject（≤30字，新聞角度）→ 個人化開場一句（指定記者路線，非群發）→ news angle + hook → 具體 offer → embargo/時間 → 具體 next step 結尾（無謝謝，無驚嘆號）。
  禁：「親愛的媒體朋友們」「我們很高興地宣布」「業界領先/顛覆」「謝謝！」「期待！」及任何驚嘆號。
  語氣＝沉穩守護者，像資深公關寫給認識的記者。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 2500,
    outputDefaults: { platform: "press", post_type: "press-release" },
  },
  {
    // 2026-05-17 (CJ B「繼續深化」→ 借時事 Newsjack，需 99s 即時 scout):
    // scout 抓回「此刻正在發燒的趨勢/新聞」，把品牌安全地接上去。
    id: "pr-99-newsjack",
    tier: "99s", postType: "press",
    label: "借時事新聞鉤（Newsjack）",
    description: "把品牌安全接上此刻正在發燒的時事，產出可報導的角度",
    agent_id: 223197, skill_slug: "pr-writing",
    primary_question: "品牌想被看見的點 / 可連結的專業或產品？（若有想接的時事可一併寫）",
    primary_input: { key: "context", placeholder: "品牌專業領域/產品/觀點 + 手上事實或數字。系統會自動抓此刻熱門時事；若你已有想接的具體時事事件也可直接寫進來（沒抓到時就用你寫的）", type: "textarea" },
    inputs: [{ key: "context", label: "品牌可連結的點 + 手上素材（可附想接的時事）", type: "textarea", required: true }],
    systemPrompt: `【得獎工藝參考】Oreo「Dunk in the Dark」（2013 超級盃停電即時 newsjack，earned-media 經典）：贏在「在對的時刻、用對的角度，把品牌接上一個正在發燒的公共話題」，而且快、自然、不尷尬。

系統已透過 scout 帶入「此刻正在發燒的時事/趨勢」（見下方即時資料區塊）。你的工作：從這些真實時事中，挑出品牌能「自然且有正當性」接上的，產出一個可被記者報導的 newsjack 角度。每個變體＝接一個不同的時事 / 不同接法。

【絕對規則（違反即整篇不合格，輸出前逐條自查）】
1. 這**不是社群貼文**，是給品牌方用的「時事鉤角度卡」。**全文不得出現任何 # 標籤、emoji、句尾驚嘆號**。
2. 禁效率/行銷腔詞：包含但不限「提升效率」「秘密武器」「不再憂心」「放心不少」「好消息來了」「切莫錯過」「快來」「立刻掌握」「更棒的是」「吧！」。
3. **五個變體格式完全相同**（一律下面四欄），語氣基準一致（沉穩守護者），只有「接的時事/角度」不同；**不准任何一個變體切換成別種格式或浮誇語氣**。
4. 沒有真實時事時 → 見下方「scout 為空」規則：標 [請補充：時事事件]，**不得拿陳舊/不確定的融資或舊聞硬充當週時事**。
5. **本變體必須鎖定上方「本次只產 1 個變體」指定的時事『類別』**（競品動態／產業數據報告／法規政策／社群熱話／媒體議題／技術突破其中之一）。只在這個類別裡找鉤——例如類別＝「競品動態」就要接一個具名競品的具體動作（產品發表／併購／定價），類別＝「產業數據／報告」就要接一份具名機構的具體報告與數字。**嚴禁**跨類別漂移成「行銷科技持續演進」「品牌一致性成為焦點」這種放諸四海皆準的趨勢氛圍——那不是該類別的時事，直接判不合格。
6. 若該類別在下方 scout 即時資料中找不到對得上的具體事件：**不要用模糊趨勢硬湊**，【角度】直接寫「本類別（<類別名>）未取得可用時事 → [請補充：你想接的<類別名>事件]」，其餘欄位照填可填的部分。寧可誠實標缺，不要造一個假時事。

嚴格照此格式輸出：
【角度】<一句話：品牌如何接上哪個正在發燒的時事，記者會怎麼下標>
【為什麼會被報】<2–3 句：這個時事為何正熱、品牌切入的正當性與貢獻、為什麼是現在；扣具體事實/數字（無則[待補]）>
【一句 pitch】<可直接寄給記者的一句，賣「品牌×時事」的角度，不賣品牌本身>
【建議下一步】<接哪個任務展開：如「用『新聞稿標題』生標題」「用『media pitch』寄科技記者」；並標註此鉤的**具體時效**——必須是可執行的明確窗口，例如「3 天內」「本週五前」「事件發生後 48 小時內」。**禁**寫「下個月內」「近期」「儘快」這種模糊時效（newsjack 的價值來自時間窗，模糊＝無效）>

準則：
- 只接「品牌有正當發言權」的時事；不蹭悲劇、不蹭爭議性政治、不硬湊——寧可少給也不要尷尬蹭流量（這會傷品牌，評審也會扣分）。
- 【角度】必須點到一個**具體、可指認、最好有日期/出處的事件**（來自下方 scout 即時資料，或用戶 context 中自己寫的時事）。**嚴禁**用「行銷科技的發展」「AI 生成成為常態」這種趨勢氛圍冒充時事——那不是 newsjack，會被判場景不符。
- 若 scout 即時資料區塊為空 / 無合適可接，**不要自己編一個趨勢**：【角度】直接寫「本批未取得可用時事 → [請補充：你想接的時事事件]」，並在【建議下一步】說明可手動補時事再重跑；其餘欄位照填可填的部分。
- 受眾說明：本任務產出是品牌方的 earned-media 工具——【一句 pitch】本來就是「代品牌向記者賣這個角度」用的（記者是擴散管道，非最終受眾）；【角度】【為什麼會被報】要讓品牌行銷主管一看就懂這鉤的價值。三個變體對「同一品牌訊息」用不同接法，不要其中一個改成對記者撒嬌的語氣。
- 語氣 guardrail（每個變體都適用，違反即不合格）：沉穩守護者；**禁**任何句子以驚嘆號收尾、**禁**行銷腔／效率語言（「秘密武器」「不再憂心」「放心不少」「快來」「立刻掌握」）、**禁** emoji。輸出前自我掃一遍，違規就改掉再交。
- 具體勝過修辭、不杜撰、可被記者原句引用。
- 只輸出上面四欄，不要前言或結語。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 600,
    outputDefaults: { platform: "press", post_type: "press" },
  },
  // pr-99-crisis-toolkit removed per CJ direction 2026-05-06 — risky.
  {
    id: "br-99-reposition-toolkit",
    tier: "99s", postType: "press",
    label: { en: "Brand Reposition Toolkit", zh: "品牌重新定位完整 Toolkit" },
    description: "Positioning + Tagline 套 + Voice guide + Visual direction + 應用範例",
    agent_id: 60002, skill_slug: "brand-strategy", // Ethan Chiang | DTC E-commerce Brand Strategist
    primary_question: "想往什麼方向轉？（已讀入現有定位作為起點）",
    primary_input: { key: "new_position", placeholder: "新定位方向 / 想拋下的舊包袱", type: "textarea" },
    inputs: [{ key: "new_position", label: "新定位方向", type: "textarea", required: true }],
    contextSources: [
      "brand.positioning.goldenCircle",
      "brand.positioning.differentiation",
      "brand.positioning.voice",
    ],
    systemPrompt: `產出 Brand reposition toolkit 其中 1 部分（300-600 字）。
本次你寫的是「{label}」（Positioning statement / Tagline 5 套 / Voice guide / Visual direction / 5 個應用範例）。
品牌已有完整定位 — 重新定位要明確指出哪些保留、哪些拋下，不是從零開始。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1200,
    outputDefaults: { platform: "press", post_type: "press" },
  },
  {
    id: "br-99-voice-playbook",
    tier: "99s", postType: "press",
    label: { en: "Brand Voice Playbook", zh: "品牌語氣完整 Playbook" },
    description: "8 個應用情境 + Do/Don't 詳細 + 5 個範例 + 跨平台 voice 適配",
    agent_id: 32, skill_slug: "brand-strategy", // Fiona Hsu | Copywriter
    primary_question: "想補充或微調哪些情境？（已讀入既有 Voice — 留空即直接展開 8 情境 playbook）",
    primary_input: { key: "voice_direction", placeholder: "選填 — 想強化的特定情境，如客服 / 危機 / 跨國", type: "textarea" },
    inputs: [{ key: "voice_direction", label: "情境補充（選填）", type: "textarea", required: false }],
    contextSources: [
      "brand.positioning.voice",
      "brand.positioning.goldenCircle.why",
    ],
    systemPrompt: `產出 Brand voice playbook 其中 1 部分（400-700 字）。
本次你寫的是「{label}」。品牌已有「Voice」段落（人格原型 / 語調詞 / 禁區 / 範例對比）— 此 toolkit 是把它延伸到 8 個實戰情境（社群 / 客服 / 危機 / EDM / PR / 跨國 / 內部 / API），不要重寫基礎 voice。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "press", post_type: "press" },
  },
  {
    id: "rs-99-discovery-sprint",
    tier: "99s", postType: "press",
    label: { en: "User Research · Discovery Sprint", zh: "用戶研究 5 天 Discovery Sprint" },
    description: "訪綱 + 5 personas + JTBD map + insights synthesis + 行動建議",
    agent_id: 90043, skill_slug: "user-research", // Lydia Chiu | Qualitative Research Director
    primary_question: "想了解用戶什麼？（已讀入既有受眾定位 — 留空即用既有 persona 延伸研究假設）",
    primary_input: {
      key: "research_goal",
      placeholder: "選填 — 想驗證的新假設或想深挖的角度",
      type: "textarea",
    },
    inputs: [{ key: "research_goal", label: "研究目標（選填）", type: "textarea", required: false }],
    contextSources: [
      "brand.positioning.audience.primary",
      "brand.positioning.audience.matrix",
      "brand.positioning.goldenCircle.why",
    ],
    systemPrompt: `產出 Discovery sprint 其中 1 部分（400-700 字）。
本次你寫的是「{label}」（Day 1 訪綱 / Day 2-3 訪談 + 5 personas / Day 4 JTBD map / Day 5 synthesis + 行動）。
品牌定位的「目標受眾」已建立 primary persona 與情感需求矩陣 — 請以此為起點延伸研究假設，不要重新拆受眾。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1300,
    outputDefaults: { platform: "press", post_type: "press" },
  },
  {
    id: "rs-99-competitor-mapping",
    tier: "99s", postType: "press",
    // 2026-05-11 (CJ「中英文研究意圖不一樣」): split label + correct EN
    // (this is competitor research, not user research).
    label: { en: "Competitor Research Map", zh: "競品研究完整地圖" },
    description: "5-10 競品分析 + 定位 map + opportunity gaps + 推薦策略",
    agent_id: 90006, skill_slug: "competitive-intel", // Steven Chen — Research Manager, Consumer Insights
    primary_question: "想補充什麼？（系統已讀入品牌的競品定位 — 可留空直接跑）",
    primary_input: {
      key: "category",
      placeholder: "選填 — 想額外切入的角度，例如：只看線上競品、加入海外案例",
      type: "textarea",
      // 2026-05-11 — auto-resolve the领域 from the brand's audience +
      // industry. If the brand has positioning, the modal pre-fills
      // and the question becomes optional rather than required.
      derive: {
        from: ["brand.positioning.audience.primary", "brand.industry"],
        mode: "auto",
      },
    },
    inputs: [{
      key: "category",
      label: "額外補充（選填）",
      type: "textarea",
      required: false, // ← no longer required; positioning provides ground truth
      derive: {
        from: ["brand.positioning.audience.primary", "brand.industry"],
        mode: "auto",
      },
    }],
    // 2026-05-11 — declare which positioning segments the task uses,
    // so the modal can show "我會用 X 競品 / Y 受眾 來跑這個任務".
    contextSources: [
      "brand.positioning.competition.direct",
      "brand.positioning.competition.indirect",
      "brand.positioning.differentiation",
      "brand.positioning.audience.primary",
    ],
    systemPrompt: `產出競品 mapping 其中 1 部分（300-600 字）。
本次你寫的是「{label}」（市場 overview / 競品 1-5 deep dive / 定位 map / opportunity gaps / 推薦策略）。
**重要：** 品牌定位的「競爭格局分析」已寫過 direct / indirect 競品清單與我方差異點 — 請直接引用、深化，不要重複列同一份。${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1200,
    outputDefaults: { platform: "press", post_type: "press" },
  },

  // ─── 2026-05-12 (CJ「競品截圖」)──────────────────────────────
  // 競品廣告偵察 — 用 LLM web search 撈 Meta Ads Library 公開資料，
  // 不直接 scrape（避免 TOS 風險）。資料量大時請求 Claude 搭 web_search
  // 翻譯成可讀的競品 report。
  {
    id: "rs-99-competitor-ads",
    tier: "99s", postType: "press",
    label: { en: "Competitor Ad Intelligence", zh: "競品廣告偵察報告（Meta Ads Library）" },
    description: "撈最多 5 個競品在 Meta Ads Library 的近期投放 → LLM 分析比例 / 訴求 / 視覺",
    agent_id: 210225, skill_slug: "competitive-intel",
    primary_question: "要監測哪些競品？（最多 5 個品牌名，用逗號分隔）",
    primary_input: {
      key: "competitor_brands",
      placeholder: "例：屈臣氏, 康是美, 86 小舖",
      type: "textarea",
    },
    inputs: [
      { key: "competitor_brands", label: "競品品牌", type: "textarea", required: true,
        placeholder: "用逗號分隔，最多 5 個" },
      { key: "focus", label: "想看什麼？（選填）", type: "textarea", required: false,
        placeholder: "投放節奏 / 訴求語氣 / 視覺風格 / 廣告類型分佈 / 全部" },
    ],
    contextSources: [
      "brand.positioning.competition.direct",
      "brand.positioning.differentiation",
    ],
    systemPrompt: `產出競品廣告偵察報告其中 1 部分（300-600 字）。本次你寫的是「{label}」。

**資料來源（請呼叫 web_search）：**
請對每個競品搜尋 \`site:facebook.com/ads/library/ <品牌名>\` 或直接訪問
\`https://www.facebook.com/ads/library/?active_status=all&ad_type=all&country=TW&q=<競品>\`
撈該品牌近 30-90 天在台灣投放的廣告（含創意縮圖描述、文案、投放開始日）。

**輸出結構**（依本步驟所屬段落）：
- 投放節奏：每個競品幾支廣告、頻率、新舊比
- 訴求分析：情感 vs 功能 / 折扣 vs 故事 / hook 套路
- 視覺風格：色調、版面、人物 vs 產品為主
- 廣告類型分佈：圖片 / 影片 / 輪播 / Reels
- 機會點：我方差異 vs 競品空白
${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1500,
    outputDefaults: { platform: "press", post_type: "press" },
  },

  // ─── 2026-05-12 (CJ「KOL 我們提供說法，不提供名單」)──────────
  {
    id: "kl-99-campaign-toolkit",
    tier: "99s", postType: "press",
    label: { en: "KOL Campaign Toolkit", zh: "KOL Campaign 完整話術包" },
    description: "多 KOL 分層邀請 + 漏斗訊息 + brief 模板 + 報價回應 + 結案報告",
    agent_id: 220920, skill_slug: "kol-outreach", // Chloe Chen | Senior KOL & Influencer Manager
    // 2026-05-18 (CJ 驗收「問題設計 1/2」): 99s 表單只送單一主輸入，把
    // 合作形式 + 平台 併進同一引導 textarea（這兩點對 outreach 話術影響
    // 極大），prompt 從中解析；沒給就標 [請補充] 不臆測。
    primary_question: "活動主題 + 合作量級 + 合作形式 + 主要平台？",
    primary_input: {
      key: "campaign_brief",
      placeholder: "例：OnBrand 年中活動｜找 3-5 位品牌行銷/內容策略 KOL｜預算共 20 萬｜合作形式：試用體驗+業配｜平台：IG+LinkedIn｜7 月完成",
      type: "textarea",
    },
    inputs: [
      { key: "campaign_brief", label: "活動 brief（主題/量級/合作形式/平台/時程）", type: "textarea", required: true },
      { key: "kol_tiers", label: "KOL 分層（選填）", type: "text", required: false,
        placeholder: "例：1 位 100K+ + 2 位 30-100K + 5 位 1-10K" },
    ],
    contextSources: [
      "brand.positioning.voice",
      "brand.positioning.goldenCircle.why",
      "brand.positioning.differentiation.summary",
    ],
    systemPrompt: `你負責 KOL Campaign Toolkit 的「{label}」（邀請開場 / brand brief 模板 / 報價回應 / brief 確認 / 拍攝期追蹤 / 上稿確認 / 結案感謝 / 結案數據要求）。

【最高優先規則 — 違反即不合格】
這份 brief 的「合作形式」（試用體驗／業配／品牌大使）與「主要平台」（IG／YT／LinkedIn），**只能用 brief 字面明確寫到的**。brief 沒寫＝**未知**：
- **絕對禁止臆測、推論、舉例或預設**（不可寫「1-2 支原生內容」「業配級合作」「主要平台為 IG/YT」之類自填值）。
- 未知的欄位，在話術中該出現該資訊的位置，**原樣保留佔位符**「[請補充：合作形式]」「[請補充：主要平台]」，照常把其餘話術寫完。
- 數字／預算／檔期同理：brief 沒給就標 [請補充：…]，不得捏造。

【強制前置步驟｜輸出的第一段一定是這個 Brief 解析區塊】
先逐欄判讀，照此格式輸出（不可省略）：
〔Brief 解析〕
- 合作形式：<brief 原文寫到的值；沒寫就寫「未提供 → [請補充：合作形式]」>
- 主要平台：<同上規則 → [請補充：主要平台]>
- 合作量級／預算：<同上>
- 時程／截止：<同上>

接著空一行，再寫「{label}」這部分的話術（400-700 字）。話術中凡涉及上面標為「未提供」的欄位，一律沿用該佔位符，不得自行補值。

我們**不**幫客戶找 KOL 名單。我們提供：怎麼開場（不被當業配機器拒絕）、怎麼給 brief（KOL 能拍但不偏離品牌）、怎麼回應報價（守得住但不傷關係）、怎麼收尾（讓 KOL 願意再合作）。

語氣：尊重、不卑不亢、有 brand pride 但不傲慢。
${TONE_100}`,
    preferredModel: "qwen", maxTokens: 1400,
    outputDefaults: { platform: "press", post_type: "press" },
  },
];

// ─── Orchestra configs ──────────────────────────────────────────────────
// Image directors per channel
const MANDY = 220887, NANCY = 180170, NINA = 180157, ANNA = 180165; // Mandy → Claire Chen (977 char)
const ZEYU = 60071, NATHAN = 60062, BR_IMG = 60030, RS_IMG = 24;
// 2026-05-08: per-task unique image directors for 100s tier
const TT100_IMG2 = 220896; // Brian Chen — Digital Experience Designer
const LI100_IMG2 = 210018; // Zach Ko — AI Design Thinking Consultant (IDEO)
const EM100_IMG2 = 210019; // Sophia Liao — AI Digital Experience Strategist (McKinsey)
const BR100_IMG2 = 39;     // Tom Hsu — Marketing Designer

const fb100Common = {
  runImageGen: true, imageDirectorId: MANDY,
  imageQualitySteps: 4,
  extras: { replyTemplates: 5, postingTime: true, followupPost: true, narrativeArc: true },
};

// ─── FB 100s orchestra configs ──────────────────────────────────────────
// Legacy squad mapping (these 100s tasks reuse the SHAPE of existing
// FB squads — same multi-post deliverable structure; orchestra runner
// instead of stepExecute pipeline for unified UX):
//   fb-99-30day-calendar     ← fb-monthly-calendar squad
//   fb-99-14day-countdown    ← fb-countdown-series squad
//   fb-99-launch-toolkit     ← fb-event-launch-kit squad
//   fb-99-livestream-9seg    ← fb-livestream-prep squad
//   fb-99-crisis-playbook    ← fb-crisis-comms squad
export const FB_99S_ORCHESTRA: Record<string, OrchestraConfig> = {
  "fb-99-30day-calendar": {
    // 2026-05-18 (CJ「分配不同 agent 處理不同類型內容比較快」): each
    // pillar = its own parallel agent (callCaptionWriter fanout), then
    // merged into one 30-day calendar (calendarMerge). No image gen / no
    // strategist → ~5× faster, no 502.
    ...fb100Common,
    variants: 5, images: 0, runImageGen: false,
    imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any,
    variantLabels: ["理念WHY", "產品", "節慶", "UGC見證", "權威觀點"],
    captionMinChars: 200, captionMaxChars: 4000,
    scoutKind: "festivals", // 抓即時節慶供「節慶」支柱使用（已有 18s 上限）
    calendarMerge: true,
    extras: {},
  },
  "fb-99-monthly-calendar-promo": {
    ...fb100Common,
    variants: 5, images: 0, runImageGen: false,
    imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any,
    variantLabels: ["產品促銷", "急迫限時", "節慶檔期", "UGC見證", "理念WHY"],
    captionMinChars: 200, captionMaxChars: 4000,
    scoutKind: "festivals",
    calendarMerge: true,
    extras: {},
  },
  "fb-99-carousel-5": {
    ...fb100Common,
    // single version (one carousel), 5 cards each with its own image
    variants: 1, images: 1,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["輪播版本"],
    captionMinChars: 150, captionMaxChars: 250,
    strategistAgentId: 180030, // Kevin Lin — Content Strategy
    cardsPerVariant: 5,
    holdForImages: true,
    extras: { replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "fb-99-viral-rewrite": {
    ...fb100Common, variants: 5, images: 5,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["保結構式", "情感放大式", "反差式", "數據式", "故事式"],
    captionMinChars: 200, captionMaxChars: 400,
    strategistAgentId: 180142, // Kevin Liu — Social Listening
    specialtyAgentId: 220504,  // Cheng-Tse Liao — Compare Editor
    scoutKind: "viral",
    holdForImages: true,
    extras: { ...fb100Common.extras, compareTable: true },
  },
  "fb-99-testimonial-rewrite": {
    ...fb100Common, variants: 5, images: 5,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["故事式", "對比式", "數據式", "情感式", "簡短式"],
    captionMinChars: 200, captionMaxChars: 350,
    strategistAgentId: 220754, // Kurt Chen — Insights Storyteller
    specialtyAgentId: 180855,  // Jason Evans — Risk & Compliance
    holdForImages: true,
    extras: { ...fb100Common.extras, legalAssistant: true },
  },
  "fb-99-trend-rewrite": {
    ...fb100Common, variants: 5, images: 5,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["評論式", "幽默式", "資訊式", "立場式", "中立式"],
    captionMinChars: 150, captionMaxChars: 300,
    strategistAgentId: 90011, // Mark Davis — Public Affairs
    specialtyAgentId: 220959, // Trend Researcher — Timing Advisor
    scoutKind: "trending",
    holdForImages: true,
    extras: { ...fb100Common.extras, timingAdvisor: true },
  },
  "fb-99-serial-3": {
    ...fb100Common, variants: 3, images: 3,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["第 1 集", "第 2 集", "第 3 集"],
    captionMinChars: 200, captionMaxChars: 350,
    strategistAgentId: 220863, // Nelson Chen — Narrative Editor
    postLabels: ["第 1 集", "第 2 集", "第 3 集"],
    holdForImages: true,
    extras: { ...fb100Common.extras, postsCount: 3 },
  },
  "fb-99-14day-countdown": {
    ...fb100Common, variants: 7, images: 7,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["倒數第 7 天", "倒數第 6 天", "倒數第 5 天", "倒數第 4 天", "倒數第 3 天", "倒數第 2 天", "最後 1 天"],
    captionMinChars: 80, captionMaxChars: 130,
    strategistAgentId: 60013, // Kevin Kan — SEO Content Strategist
    postLabels: ["倒數第 7 天", "倒數第 6 天", "倒數第 5 天", "倒數第 4 天", "倒數第 3 天", "倒數第 2 天", "最後 1 天"],
    scoutKind: "festivals", // 倒數活動 → 抓相關節慶 / 行銷檔期
    extras: { ...fb100Common.extras, postsCount: 7 },
  },
  "fb-99-launch-toolkit": {
    // 2026-05-18 (CJ「launch-toolkit 加總覽」): first variant = 活動總覽
    // (one-page campaign plan doc), then the 8 posts.
    ...fb100Common, variants: 9, images: 9,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["活動總覽", "預告 1", "預告 2", "預告 3", "當日", "即時 1", "即時 2", "事後", "IG 跨平台"],
    captionMinChars: 150, captionMaxChars: 300,
    strategistAgentId: 60002, // Ethan Chiang — DTC E-commerce Brand Strategist
    postLabels: ["活動總覽", "預告 1", "預告 2", "預告 3", "當日", "即時 1", "即時 2", "事後", "IG 跨平台"],
    scoutKind: "viral", // 看同類 launch 通常用什麼 hook
    extras: { ...fb100Common.extras, postsCount: 9 },
  },
  "fb-99-livestream-9seg": {
    ...fb100Common, variants: 9, images: 9,
    aspectRatio: "16:9", fluxSize: "landscape_16_9",
    variantLabels: ["預告", "開場宣告", "爆點 1", "爆點 2", "爆點 3", "爆點 4", "爆點 5", "結尾", "Reel 剪輯"],
    captionMinChars: 80, captionMaxChars: 200,
    strategistAgentId: 224091, // Nurul Huda — Email & CRM Strategist eCommerce MY (1250 char)
    postLabels: ["預告", "開場宣告", "爆點 1", "爆點 2", "爆點 3", "爆點 4", "爆點 5", "結尾", "Reel 剪輯"],
    scoutKind: "viral",
    extras: { ...fb100Common.extras, postsCount: 9 },
  },
  "fb-99-crisis-playbook": {
    ...fb100Common, variants: 7, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any,
    variantLabels: ["偵測警示", "第一份聲明", "24h 更新", "48h 更新", "72h 更新", "1 週 follow-up", "媒體 talking points"],
    captionMinChars: 200, captionMaxChars: 400,
    strategistAgentId: 90011,
    specialtyAgentId: 180630, // Shirley Sanchez — Global Affairs & General Counsel (2355 char)
    postLabels: ["偵測警示", "第一份聲明", "24h 更新", "48h 更新", "72h 更新", "1 週 follow-up", "媒體 talking points"],
    scoutKind: "trending", // 危機處理 → 抓即時相關新聞
    extras: { ...fb100Common.extras, postsCount: 7, legalAssistant: true, narrativeArc: true },
  },
};

const ig100Common = {
  runImageGen: true, imageDirectorId: NANCY,
  imageQualitySteps: 4,
  extras: { replyTemplates: 5, postingTime: true, followupPost: true, narrativeArc: true },
};

// IG 100s — legacy squad mapping:
//   ig-99-30day-calendar     ← (no exact IG squad; reuses fb-monthly-calendar shape)
//   ig-99-reel-series-6      ← (new — adapted from fb-reels-script squad)
//   ig-99-account-reposition ← fb-account-reposition squad shape
//   ig-99-save-worthy        ← Hormozi Save-Worthy squad (5 slides + 2 research tabs)
export const IG_99S_ORCHESTRA: Record<string, OrchestraConfig> = {
  "ig-99-30day-calendar": {
    ...ig100Common, variants: 4, images: 4,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    captionMinChars: 400, captionMaxChars: 800,
    strategistAgentId: 60008, // Fiona Hsieh — Social Media Marketing Strategist (Beauty)
    postLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    scoutKind: "festivals",
    extras: { ...ig100Common.extras, postsCount: 4 },
  },
  "ig-99-reel-series-6": {
    ...ig100Common, variants: 6, images: 6,
    aspectRatio: "9:16", fluxSize: "portrait_9_16",
    variantLabels: ["第 1 集", "第 2 集", "第 3 集", "第 4 集", "第 5 集", "第 6 集"],
    captionMinChars: 250, captionMaxChars: 500,
    strategistAgentId: 180162, // Jason Peng — Social Media Copywriter (1440 char)
    postLabels: ["第 1 集", "第 2 集", "第 3 集", "第 4 集", "第 5 集", "第 6 集"],
    scoutKind: "viral",
    extras: { ...ig100Common.extras, postsCount: 6 },
  },
  "ig-99-account-reposition": {
    ...ig100Common, variants: 5, images: 5,
    aspectRatio: "1:1", fluxSize: "square_hd",
    variantLabels: ["新 Bio", "Highlight 套組", "Launch Post 1-3", "Launch Post 4-6", "Launch Post 7-9"],
    captionMinChars: 250, captionMaxChars: 500,
    strategistAgentId: 60005, // Aaron Pei — B2B Tech Brand Marketing (1181 char)
    postLabels: ["新 Bio", "Highlight 套組", "Launch Post 1-3", "Launch Post 4-6", "Launch Post 7-9"],
    scoutKind: "viral",
    extras: { ...ig100Common.extras, postsCount: 5 },
  },
  // 2026-05-19 v2 (CJ): one copy + one image = one tab, per slide.
  // Slides come FIRST (positions 0-4) so images:5 maps cleanly — the
  // orchestra assigns image[n] to variant[n], so all 5 Slide tabs get
  // AI-generated 1:1 carousel images. The two research tabs at the end
  // (positions 5-6) don't get images (research-doc mockup ignores imageUrl).
  // RunPage.tsx effectiveVariant routes:
  //   /^Slide\s+\d+/i → instagram:carousel
  //   /主題研究/       → generic:research-doc
  //   /指標追蹤/       → generic:research-doc (existing rule)
  "ig-99-save-worthy": {
    ...ig100Common,
    variants: 7, images: 5,
    aspectRatio: "1:1", fluxSize: "square_hd", imageQualitySteps: 4,
    variantLabels: ["Slide 1", "Slide 2", "Slide 3", "Slide 4", "Slide 5", "主題研究", "指標追蹤"],
    captionMinChars: 60, captionMaxChars: 320,
    postLabels: ["Slide 1", "Slide 2", "Slide 3", "Slide 4", "Slide 5", "主題研究", "指標追蹤"],
    scoutKind: "viral",
    extras: { postsCount: 5, replyTemplates: 3, postingTime: true },
  },
};

const yt100Common = {
  runImageGen: true, imageDirectorId: NINA,
  imageQualitySteps: 8,
  extras: { replyTemplates: 5, postingTime: true, followupPost: true, narrativeArc: true },
};

// YT 100s — legacy squad mapping:
//   yt-99-quarterly-strategy ← fb-quarterly-strategy squad shape
//   yt-99-series-6ep         ← (new — extends 60s yt-60-series-3ep)
//   yt-99-premiere-kit       ← (new — adapted from fb-livestream-prep)
export const YT_99S_ORCHESTRA: Record<string, OrchestraConfig> = {
  "yt-99-series-6ep": {
    ...yt100Common, variants: 6, images: 6,
    aspectRatio: "16:9", fluxSize: "landscape_16_9",
    variantLabels: ["EP1", "EP2", "EP3", "EP4", "EP5", "EP6"],
    captionMinChars: 500, captionMaxChars: 1000,
    strategistAgentId: 90002, // Darren Freeman — Creative Excellence Director (2348 char)
    postLabels: ["EP1", "EP2", "EP3", "EP4", "EP5", "EP6"],
    scoutKind: "viral",
    extras: { ...yt100Common.extras, postsCount: 6 },
  },
  "yt-99-quarterly-strategy": {
    ...yt100Common, variants: 4, images: 4,
    aspectRatio: "16:9", fluxSize: "landscape_16_9",
    // 2026-05-19 (CJ): reorder tabs + remove Competitor 分析 (5→4 tabs)
    variantLabels: ["即時趨勢報告", "內容支柱", "12 影片 title", "Community 月曆"],
    captionMinChars: 300, captionMaxChars: 600,
    strategistAgentId: 30001, // Alex Chen — AI Growth Hacker CMO (1831 char)
    postLabels: ["即時趨勢報告", "內容支柱", "12 影片 title", "Community 月曆"],
    scoutKind: "news", // 季度策略 → 抓產業最新
    extras: { ...yt100Common.extras, postsCount: 4 },
  },
  "yt-99-premiere-kit": {
    ...yt100Common, variants: 4, images: 4,
    aspectRatio: "16:9", fluxSize: "landscape_16_9",
    variantLabels: ["Trailer 腳本", "Community 倒數 ×5", "直播配套", "精華剪輯指南"],
    captionMinChars: 200, captionMaxChars: 400,
    strategistAgentId: 90022, // Andy Gallagher — Head of Creative & Media (1464 char)
    postLabels: ["Trailer 腳本", "Community 倒數 ×5", "直播配套", "精華剪輯指南"],
    scoutKind: "viral",
    extras: { ...yt100Common.extras, postsCount: 4 },
  },
};

// Multi-channel 100s — legacy squad mapping (where applicable):
//   tt-99-trend-week → (new — TikTok trend chasing)
//   tt-99-30day-foryou → (new — extends fb-monthly-calendar shape)
//   li-99-newsletter-quarterly → (new)
//   em-99-launch-sequence → fb-event-launch-kit shape adapted to email
//   pr-99-crisis-toolkit → fb-crisis-comms shape adapted to PR
//   rs-99-competitor-mapping → fb-account-reposition + competitor-audit shape
export const MULTI_99S_ORCHESTRA: Record<string, OrchestraConfig> = {
  // 2026-05-18 (CJ 驗收 P0「Unknown task id: kl-99-campaign-toolkit」):
  // the task template existed in MULTI_99S_TASKS but had NO matching
  // orchestra config → get99OrchestraConfig returned null → the resolver
  // discarded the found template and fell through to "Unknown task id".
  // KOL 話術包 is a text deliverable (8 parts, no images).
  "kl-99-campaign-toolkit": {
    variants: 8, images: 0, runImageGen: false,
    imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any,
    imageQualitySteps: 4,
    variantLabels: ["邀請開場", "brand brief 模板", "報價回應", "brief 確認", "拍攝期追蹤", "上稿確認", "結案感謝", "結案數據要求"],
    captionMinChars: 400, captionMaxChars: 900,
    postLabels: ["邀請開場", "brand brief 模板", "報價回應", "brief 確認", "拍攝期追蹤", "上稿確認", "結案感謝", "結案數據要求"],
    extras: { postsCount: 8 },
  },
  "tt-99-30day-foryou": {
    variants: 4, images: 4, runImageGen: true, imageDirectorId: ANNA,
    aspectRatio: "9:16", fluxSize: "portrait_9_16", imageQualitySteps: 4,
    variantLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    captionMinChars: 300, captionMaxChars: 700,
    strategistAgentId: 90015, // Sonia Belgacem — Global Client Service Manager, Creative Excellence (1547 char)
    postLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    scoutKind: "festivals",
    extras: { postsCount: 4, narrativeArc: true, replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "tt-99-trend-week": {
    variants: 7, images: 7, runImageGen: true, imageDirectorId: TT100_IMG2,
    aspectRatio: "9:16", fluxSize: "portrait_9_16", imageQualitySteps: 4,
    variantLabels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    captionMinChars: 200, captionMaxChars: 400,
    postLabels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7"],
    scoutKind: "trending", // 追熱點 → 抓即時時事
    extras: { postsCount: 7, replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "li-99-30day-thought-leadership": {
    variants: 4, images: 4, runImageGen: true, imageDirectorId: ZEYU,
    aspectRatio: "1.91:1", fluxSize: "landscape_4_3", imageQualitySteps: 4,
    variantLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    captionMinChars: 400, captionMaxChars: 800,
    postLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    scoutKind: "news", // thought-leadership → 抓產業最新
    extras: { postsCount: 4, replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "li-99-newsletter-quarterly": {
    variants: 4, images: 4, runImageGen: true, imageDirectorId: LI100_IMG2,
    aspectRatio: "1.91:1", fluxSize: "landscape_4_3", imageQualitySteps: 4,
    variantLabels: ["第 1 期", "第 2 期", "第 3 期", "第 4 期"],
    captionMinChars: 400, captionMaxChars: 800,
    strategistAgentId: 180015, // Kevin Lin — Content Strategy Director
    postLabels: ["第 1 期", "第 2 期", "第 3 期", "第 4 期"],
    scoutKind: "news",
    extras: { postsCount: 4, narrativeArc: true, replyTemplates: 5, postingTime: true, followupPost: true },
  },
  "em-99-4week-nurture": {
    // 2026-05-19 (Yi-Wen 驗收 v#1): images:4+runImageGen was same pattern that
    // caused em-99-launch-sequence to drop last variants. strategist/scout/
    // narrativeArc add overhead without benefiting per-email nurture content.
    // Prompt fully rewritten with format + per-week subject/CTA rules.
    // 2026-05-19 (Yi-Wen 驗收 v#2): Week 2 triple failure — same subject as
    // Week 1, "主旨：" prefix leaking into h1/body, double CTA button.
    // Fix: (1) prompt hardened with per-week hook-angle prohibition + explicit
    // example subjects + Week-2 self-check; (2) email.tsx _grabCta() loose
    // fallback removed; (3) bodyText strip also covers parenthesised inline
    // CTA hints; (4) _stripMetaPrefix() safety ensures "主旨：" never leaks.
    variants: 4, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    variantLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    captionMinChars: 200, captionMaxChars: 500,
    postLabels: ["第 1 週", "第 2 週", "第 3 週", "第 4 週"],
    disableScout: true,
    extras: { postsCount: 4, replyTemplates: 2, postingTime: true },
  },
  "em-99-launch-sequence": {
    // 2026-05-18 (CJ 驗收 P0「只產 5 封，少了最後機會/follow-up」):
    // strategist + scout + narrativeArc 讓 7 封 fanout 過重，後段信
    // 失敗→靜默少產。砍掉非必要的 strategist/scout/narrativeArc，讓
    // 7 封都穩定產出（序列邏輯已由 systemPrompt 的階段規則承載）。
    // 2026-05-19: images:7 + runImageGen caused 7 parallel image-gen requests
    // → overwhelmed pipeline → last 2 caption calls dropped silently (only 5/7 produced).
    // Email sequences don't need AI hero images per-email; hero image can be added
    // via 改配圖 after the fact. Disabling image gen makes all 7 captions reliable.
    variants: 7, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    variantLabels: ["預告 1", "預告 2", "上線", "提醒 1", "提醒 2", "最後機會", "後續"],
    captionMinChars: 200, captionMaxChars: 500,
    postLabels: ["預告 1", "預告 2", "上線", "提醒 1", "提醒 2", "最後機會", "後續"],
    disableScout: true,
    extras: { postsCount: 7, replyTemplates: 3, postingTime: true, followupPost: true },
  },
  "pr-99-launch-toolkit": {
    // 2026-05-19 (Yi-Wen 評測): "Q&A" label 觸發 RunPage.tsx:894 的 /Q&A/i
    // 正規式 → 被路由到 facebook:qa 版型（錯誤）。改為「採訪問答」——
    // 不含「Q&A」「FAQ」「常見問答」任一 token，不會觸發 facebook:qa 路由，
    // 但保留「問答」的語意讓使用者看懂。systemPrompt 的格式規定也同步更新。
    variants: 5, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    variantLabels: ["新聞稿", "採訪問答", "媒體聯絡", "後續追蹤", "Spokesperson talking"],
    // 2026-05-19: raised from 300/700 — press releases need full structure
    // (headline + dateline + 3-para body + quote + boilerplate + contacts ≈ 1500-2500 chars).
    // Old 700-char cap was truncating output mid-sentence → "助力..." incomplete headline.
    captionMinChars: 600, captionMaxChars: 3000,
    postLabels: ["新聞稿", "採訪問答", "媒體聯絡", "後續追蹤", "Spokesperson talking"],
    scoutKind: "news",
    extras: { postsCount: 5, replyTemplates: 3 },
  },
  "pr-99-newsjack": {
    // pool of 6 distinct trend-hooks; RunPage >4 = 「再給我幾個」.
    variants: 6, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    // 2026-05-19 (CJ 驗收 #4 P2「B/D/E 同質、都是趨勢模糊型」): generic
    // 「時事 A/B」labels gave the per-variant fanout zero category steering
    // → 模型對每個都吐「行銷科技演進」這種趨勢氛圍。改成「類別 lens」
    // labels，每個變體被釘在一個不同的時事類別上，逼出多樣性。
    variantLabels: ["競品動態", "產業數據／報告", "法規政策", "社群熱話", "媒體議題", "技術突破"],
    captionMinChars: 80, captionMaxChars: 420,
    scoutKind: "trending", // 借時事 → 抓此刻正在發燒的趨勢/新聞
    cleanPrompt: true, // strict 4-field format — bypass social scaffolding
  },
  // pr-99-crisis-toolkit orchestra config removed.
  "br-99-reposition-toolkit": {
    variants: 5, images: 5, runImageGen: true, imageDirectorId: BR_IMG,
    aspectRatio: "1:1", fluxSize: "square_hd", imageQualitySteps: 4,
    variantLabels: ["Positioning", "Tagline 5 套", "Voice guide", "Visual direction", "5 應用範例"],
    captionMinChars: 300, captionMaxChars: 600,
    strategistAgentId: 180038, // Daniel Wu — D2C Strategy Manager
    postLabels: ["Positioning", "Tagline 5 套", "Voice guide", "Visual direction", "5 應用範例"],
    scoutKind: "news",
    extras: { postsCount: 5, narrativeArc: true, replyTemplates: 3 },
  },
  "br-99-voice-playbook": {
    variants: 4, images: 4, runImageGen: true, imageDirectorId: BR100_IMG2,
    aspectRatio: "1:1", fluxSize: "square_hd", imageQualitySteps: 4,
    variantLabels: ["8 應用情境", "Do/Don't", "5 範例", "跨平台適配"],
    captionMinChars: 400, captionMaxChars: 700,
    postLabels: ["8 應用情境", "Do/Don't", "5 範例", "跨平台適配"],
    scoutKind: "viral",
    extras: { postsCount: 4, replyTemplates: 3 },
  },
  "rs-99-discovery-sprint": {
    variants: 5, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    variantLabels: ["Day 1 訪綱", "Day 2-3 Personas", "Day 4 JTBD map", "Day 5 Synthesis", "行動建議"],
    captionMinChars: 400, captionMaxChars: 700,
    postLabels: ["Day 1 訪綱", "Day 2-3 Personas", "Day 4 JTBD map", "Day 5 Synthesis", "行動建議"],
    scoutKind: "news",
    extras: { postsCount: 5, replyTemplates: 3 },
  },
  "rs-99-competitor-mapping": {
    variants: 5, images: 0, runImageGen: false, imageDirectorId: null as any,
    aspectRatio: null as any, fluxSize: null as any, imageQualitySteps: 0,
    variantLabels: ["市場 overview", "競品 deep dive ×5", "定位 map", "Opportunity gaps", "推薦策略"],
    captionMinChars: 300, captionMaxChars: 600,
    postLabels: ["市場 overview", "競品 deep dive ×5", "定位 map", "Opportunity gaps", "推薦策略"],
    scoutKind: "news",
    extras: { postsCount: 5, replyTemplates: 3 },
  },
};

// ─── Unified lookup ─────────────────────────────────────────────────────
const ALL_99_TASKS = [...FB_99S_TASKS, ...IG_99S_TASKS, ...YT_99S_TASKS, ...MULTI_99S_TASKS];
const ALL_99_ORCH: Record<string, OrchestraConfig> = {
  ...FB_99S_ORCHESTRA, ...IG_99S_ORCHESTRA, ...YT_99S_ORCHESTRA, ...MULTI_99S_ORCHESTRA,
};

export const ALL_99S_TASKS = ALL_99_TASKS;
export const ALL_99S_ORCHESTRA = ALL_99_ORCH;

export function get99Template(taskId: string): FBTaskTemplate | null {
  return ALL_99_TASKS.find((t) => t.id === taskId) ?? null;
}
export function get99OrchestraConfig(taskId: string): OrchestraConfig | null {
  return ALL_99_ORCH[taskId] ?? null;
}
