import type { TaskEnMap, VariantLabelEnMap } from "./types";

export const TASK_EN: TaskEnMap = {
  // ── Email ──────────────────────────────────────────────
  "em-30-subject-line": {
    question: "What should people do after opening this email?",
    placeholder: "e.g. Announce a new product / Remind about an unfinished order / Monthly report / Invite to an event",
    inputs: { context: { label: "Email goal + content" } },
  },
  "em-30-preview-text": {
    question: "What is the subject line?",
    placeholder: "Paste your subject line",
    inputs: { subject: { label: "Subject line + body summary" } },
  },
  "em-30-welcome": {
    question: "What is your brand? What will subscribers get?",
    placeholder: "Brand intro + what subscribers gain",
    inputs: { context: { label: "Brand + value" } },
  },
  "em-30-promo": {
    question: "What is the campaign or offer?",
    placeholder: "e.g. Anniversary sale, 20% off everything / 10% off a new member's first order / Limited-edition items",
    inputs: { promo: { label: "Promo details" } },
  },
  "em-30-drip": {
    question: "Which email in the drip is this? What did the last one say?",
    placeholder: "Drip sequence context + what this email should say",
    inputs: { context: { label: "Drip sequence context + this email's content" } },
  },
  "em-30-abandoned-cart": {
    question: "What did the customer leave in the cart?",
    placeholder: "Product name + price + any key features",
    inputs: { product: { label: "Abandoned product" } },
  },
  "em-30-re-engagement": {
    question: "Who are these dormant users? When was their last interaction?",
    placeholder: "User background + how long they've been dormant",
    inputs: { context: { label: "Dormant user background" } },
  },
  "em-30-event-invite": {
    question: "Event topic / time / audience / sign-up link?",
    placeholder: "All event details",
    inputs: { event: { label: "Event details" } },
  },
  "em-30-cold-email": {
    question: "Who is the recipient? What do you want?",
    placeholder: "Recipient's role / company + what you want to propose",
    inputs: { context: { label: "Recipient + goal" } },
  },
  "em-30-transactional": {
    question: "Which transaction event? Order number / product / amount?",
    placeholder: "Event + details",
    inputs: { transaction: { label: "Transaction event" } },
  },
  "em-30-annual-recap": {
    question: "What numbers do you have about a single customer?",
    placeholder: "e.g. How many times they bought this year / Date of their first purchase / Their most-bought item",
    inputs: { topic: { label: "Numbers you can tell a single customer" } },
    source: {
      short: "Spotify Wrapped",
      metric: "200M participants in 24 hours, 630M+ shares",
      takeaway: "A yearly recap email gets screenshotted only if the whole email is about the reader; once brand-wide totals appear, the urge to share disappears.",
    },
  },
  "em-30-subject-ai-variants": {
    question: "What is this newsletter about? Who is it for?",
    placeholder: "e.g. Autumn new arrivals / Audience: members who bought warm items last year",
    inputs: { topic: { label: "This issue's content + audience" } },
    source: {
      short: "サンコー (Sanko) newsletter AI subject-line drafts",
      metric: "Rakuten Ichiba newsletter open rate about 20% to 45%; production time 3 hours to 1 hour",
      caveat: "Japanese case; no comparison period given and no sample subject lines shown.",
      takeaway: "The open-rate lever is subject plus subheads: generating several versions per send and picking beats polishing one draft, and the saved time goes to reviewing opens and clicks and updating subject rules.",
    },
  },
  "em-30-trigger-plus-story": {
    question: "Which data can trigger automated emails? Which brand story do you want to write this month?",
    placeholder: "e.g. Browsing history, points / Story: which town our fabric comes from",
    inputs: { topic: { label: "Available trigger data + this month's brand story topic" } },
    source: {
      short: "STAMPS (STAMP AND DIARY) newsletter",
      metric: "Average open rate 30%+, peak 40%+; membership grew 2x+",
      caveat: "Japanese case; membership doubling counted from spring 2024, open rate has no before/after comparison; the reading-style newsletter is only planned.",
      takeaway: "Four personal automated emails (browsing history, rankings, recommendations, points statement) hold the base open rate, and a brand reading on fabric sources, factory and philosophy builds loyalty.",
    },
  },

  // ── Press release ──────────────────────────────────────
  "pr-30-headline": {
    question: "What is the core news event?",
    placeholder: "Who + did what + when / where",
    inputs: { event: { label: "News event" } },
    source: {
      short: "The Tampon Book (Cannes Lions 2019)",
      takeaway: "Reframe an old fact and the news grows on its own.",
    },
  },
  "pr-30-subhead": {
    question: "What is the headline's key point + what angle do you want to expand?",
    placeholder: "Headline + what you want to build on",
    inputs: { context: { label: "Headline + expansion" } },
    source: {
      short: "Project Revoice (Cannes Lions 2018)",
      takeaway: "The headline gives the event; the subhead gives the reason it must be read.",
    },
  },
  "pr-30-lead-paragraph": {
    question: "What are the 5W1H of the event?",
    placeholder: "Who / what / when / where / why / how",
    inputs: { event: { label: "5W1H details" } },
    source: {
      short: "The Lost Class (Cannes Lions 2022)",
      takeaway: "The first revealed fact makes people see the whole story differently.",
    },
  },
  "pr-30-ceo-quote": {
    question: "What is the speech topic and the core point to convey?",
    placeholder: "Speaker name + title | occasion / time / place | speech topic and point of view + facts or numbers to mention",
    inputs: { context: { label: "Speaker + occasion + speech topic and point of view" } },
    source: {
      short: "Patagonia 2022 open letter",
      takeaway: "Stance comes before rhetoric, and every sentence can be quoted on its own.",
    },
  },
  "pr-30-boilerplate": {
    question: "What are the company's core business / size / key milestones?",
    placeholder: "Business + size + founding date + main products",
    inputs: { context: { label: "Company information" } },
    source: {
      short: "PR Awards Asia judging criteria",
      takeaway: "Rankings come from provable results, not adjectives.",
    },
  },
  "pr-30-fact-sheet": {
    question: "What are all the quantifiable facts of the event?",
    placeholder: "All numbers / names / dates that can go in the fact sheet",
    inputs: { context: { label: "Fact material" } },
    source: {
      short: "Spotify Wrapped",
      takeaway: "Turn data into numbers people grasp in 10 seconds and want to share.",
    },
  },
  "pr-30-media-pitch": {
    question: "What is the news topic + why would this reporter care?",
    placeholder: "News topic + the reporter's past coverage + why it's relevant",
    inputs: { context: { label: "Pitch context" } },
    source: {
      short: "Whopper Detour (Cannes Lions 2019)",
      takeaway: "The angle is itself the story, which is why reporters cover it.",
    },
  },
  "pr-30-spokesperson-qa": {
    question: "What is the news topic + which points will likely be challenged?",
    placeholder: "Topic + the tough questions you worry about being asked",
    inputs: { context: { label: "Topic + pain points" } },
    source: {
      short: "KFC \"FCK\" (Cannes Lions 2019)",
      takeaway: "Own it immediately, be candid and witty, and say right away how you'll fix it.",
    },
  },
  "pr-30-launch-social": {
    question: "What is the news topic + what should social followers do after clicking through to the release?",
    placeholder: "News core + CTA",
    inputs: { context: { label: "News + call to action" } },
    source: {
      short: "Spotify Wrapped social spread",
      takeaway: "What gets shared is a line with a point of view, not an announcement.",
    },
  },
  "pr-30-news-hook": {
    question: "What does the company want to say publicly / what material do you have? (The more specific the better)",
    placeholder: "What you want to announce or let people know + the facts, numbers, people and dates you have",
    inputs: { context: { label: "What you want to say + material on hand" } },
    source: {
      short: "The Tampon Book (Cannes Lions 2019)",
      takeaway: "Find the claim a reporter would want to write first, then talk about the product.",
    },
  },
  "pr-30-stunt-release": {
    question: "What physical, photographable thing could you make?",
    placeholder: "e.g. Turn a store into a themed scene / Open a special space for one day",
    inputs: { topic: { label: "Photographable physical scene" } },
    source: {
      short: "Airbnb \"Barbie DreamHouse\"",
      metric: "13,000+ media articles, 250M social impressions",
      takeaway: "Widely republished releases have a photographable physical thing behind them: build that first, and the release is just the manual.",
    },
  },
  "pr-30-media-own-mistake": {
    question: "What happened? What facts are known?",
    placeholder: "e.g. Stockout / System outage / Quality issue, plus the confirmed cause",
    inputs: { topic: { label: "Incident + currently confirmed facts" } },
    source: {
      short: "KFC \"FCK\"",
      metric: "700+ articles, reach of about 797M people",
      takeaway: "Crisis coverage lasts as long as reporters can still ask questions: state everything known up front and use one self-deprecating move to lower hostility, and the story ends sooner.",
    },
  },

  // ── Research ───────────────────────────────────────────
  "rs-30-interview-guide": {
    question: "What do you want to learn about users? What is the interview topic?",
    placeholder: "e.g. Why mid-size SaaS customers churn / How new moms choose baby food",
    inputs: { topic: { label: "Interview topic" } },
  },
  "rs-30-persona-draft": {
    question: "Who is your target audience? What do you already know?",
    placeholder: "Target customer data + known behavior",
    inputs: { context: { label: "Audience information" } },
  },
  "rs-30-survey": {
    question: "What metric or hypothesis do you want to quantify?",
    placeholder: "e.g. NPS drivers / Purchase decision journey / Competitor preference",
    inputs: { topic: { label: "Survey topic" } },
  },
  "rs-30-journey-map": {
    question: "How do users go from discovering you to becoming loyal customers?",
    placeholder: "Product / service + known touchpoints",
    inputs: { context: { label: "Product + touchpoints" } },
  },
  "rs-30-competitive-interview": {
    question: "Goal: a win or loss interview?",
    placeholder: "You / competitor + interviewee + known background",
    inputs: { context: { label: "Interview background" } },
  },
  "rs-30-jtbd-guide": {
    question: "What do users \"hire\" your product to do?",
    placeholder: "Product + the job you want to understand",
    inputs: { context: { label: "Product + job" } },
  },
  "rs-30-synthesis-template": {
    question: "What is the interview topic + how many people did you interview?",
    placeholder: "Topic + sample size + the decision you want to make",
    inputs: { context: { label: "Synthesis context" } },
  },
  "rs-30-consent-form": {
    question: "Interview topic / audio and video recording / compensation?",
    placeholder: "Interview format + compensation + intended use",
    inputs: { context: { label: "Interview terms" } },
  },
  "rs-30-usability-script": {
    question: "Which product / interface will you test? What are the key flows?",
    placeholder: "Product + key tasks to test",
    inputs: { context: { label: "Test subject + tasks" } },
  },
  "rs-30-screener": {
    question: "What kind of people do you want to screen in?",
    placeholder: "Audience criteria (background / behavior / attributes)",
    inputs: { context: { label: "Audience criteria" } },
  },
  "rs-30-gap-experiment": {
    question: "What do you think users misunderstand?",
    placeholder: "e.g. They think they care about price, but they really care about wait time",
    inputs: { topic: { label: "User misconception to test" } },
    source: {
      short: "Dove \"Real Beauty Sketches\"",
      metric: "50M+ views and 3.7M shares in 12 days",
      takeaway: "Research spreads when the finding becomes two versions side by side: the gap is the conclusion, and no further explanation is needed.",
    },
  },
  "rs-30-personal-data-story": {
    question: "Which numbers in your research can be traced back to a single user?",
    placeholder: "e.g. Average time each person spends waiting in a year",
    inputs: { topic: { label: "Numbers that can be traced to an individual" } },
    source: {
      short: "Spotify Wrapped",
      metric: "200M participants in 24 hours, 630M+ shares",
      takeaway: "For research results to spread, translate totals into \"what this means for you\": people don't forward statistics, they forward findings about themselves.",
    },
  },

  // ── Website ────────────────────────────────────────────
  "web-30-longform": {
    question: "What case, issue or point of view is this piece about? Include the angle you want to bring.",
    placeholder: "e.g. A healthy-housing case from abroad, with the angle \"how air quality affects daily sleep\"",
    inputs: { context: { label: "Topic and angle" } },
  },
  "web-30-column": {
    question: "Which brand claim or standard is this piece about? Whose point of view tells it?",
    placeholder: "e.g. The CEO's view on \"quiet\": why we treat soundproofing as a baseline, not a paid option",
    inputs: { context: { label: "Claim + speaker's point of view" } },
  },
  "web-30-case-study": {
    question: "Which case will you feature? What makes it worth writing about?",
    placeholder: "e.g. A Dutch primary school, timber frame + bio-based materials, matching the claims \"nature\", \"quiet\", \"cherish\"",
    inputs: { context: { label: "Case + the brand claim it supports" } },
  },
  "web-30-product-desc": {
    question: "What is this product? Who is it for and what problem does it solve?",
    placeholder: "Product name + key specs + selling points to stress + target customers",
    inputs: { context: { label: "Product information" } },
  },
  "web-30-product-faq": {
    question: "What do this product's customers ask most? What concerns do they have?",
    placeholder: "Product + known common questions + customers' usual doubts or misconceptions",
    inputs: { context: { label: "Product + known questions" } },
  },
  "web-30-longform-open-books": {
    question: "Which costs or trade-offs of your product are normally kept private?",
    placeholder: "e.g. Water used per item / Why it costs more than others / Where we compromised",
    inputs: { topic: { label: "Costs or trade-offs not usually disclosed" } },
    source: {
      short: "Patagonia \"Don't Buy This Jacket\"",
      metric: "Revenue up about 30% the following year, to $543M",
      takeaway: "Write out the numbers that hurt you yourself, and readers have no reason to doubt the rest: the persuasive power of transparency comes from the excuses you give up.",
    },
  },
  "web-30-product-page-plain-talk": {
    question: "If you could only say one paragraph about this product, what would you say?",
    placeholder: "e.g. It's just a razor that shaves well, $3 a month",
    inputs: { topic: { label: "The paragraph you'd say in your own words" } },
    source: {
      short: "Dollar Shave Club",
      metric: "12,000 orders in 48 hours; site overwhelmed in the first hour",
      takeaway: "The most effective product page is often one person saying it all: give the price and the most direct benefit first, and leave specs for those who keep scrolling.",
    },
  },
  "web-30-product-limited-pass": {
    question: "What offer could you turn into a \"pass\"? How many are available? What priority do members get?",
    placeholder: "e.g. One hand-brewed coffee a month for a year / Limited to 300 / Members can buy 24 hours early",
    inputs: { topic: { label: "Offer details + quota + member priority" } },
    source: {
      short: "UNO Pizzeria $99 Pizza Pass",
      metric: "Website briefly crashed from the rush and a second round was added; about 65% of buyers were members",
      caveat: "US case; no traffic or revenue figures; it is a promo page, not a content page.",
      takeaway: "Package unlimited access for a period as a limited, time-boxed single-page pass, give members first access so site traffic spikes at one moment, then publish a sell-out report and add a second round.",
    },
  },
};

export const VARIANT_LABEL_EN: VariantLabelEnMap = {
  // Email
  "好奇心": "Curiosity",
  "數字反差": "Number contrast",
  "個人化": "Personalized",
  "懸念延伸": "Suspense extension",
  "補充資訊": "Added info",
  "熱情擁抱": "Warm embrace",
  "理性說明": "Rational explainer",
  "故事開場": "Story opening",
  "稀缺感": "Scarcity",
  "價值論證": "Value case",
  "故事感": "Storytelling",
  "教學式": "Tutorial",
  "故事式": "Story-driven",
  "提問式": "Question-led",
  "提醒式": "Reminder",
  "限時誘因": "Time-limited incentive",
  "解惑式": "Objection-busting",
  "朋友召喚": "Friend's call",
  "新進展": "What's new",
  "好處導向": "Benefit-led",
  "專業敘述": "Professional tone",
  "共同點切入": "Common-ground opener",
  "問題切入": "Problem opener",
  "價值交換": "Value exchange",
  "精簡型": "Minimal",
  "完整型": "Complete",
  "貼心型": "Caring",
  "成就版": "Achievements",
  "懷舊版": "Nostalgia",
  "排名版": "Rankings",
  "數字型": "Number-led",
  "好處型": "Benefit-led",
  "疑問型": "Question-led",
  "布料故事": "Fabric story",
  "工廠故事": "Factory story",
  "理念故事": "Philosophy story",
  // PR
  "事實式": "Fact-led",
  "受影響者視角": "Affected person's view",
  "對比式": "Contrast",
  "反問式": "Rhetorical question",
  "數據衝擊": "Data impact",
  "時機式": "Timing",
  "引述式": "Quote-led",
  "懸念式": "Suspense",
  "影響面": "Impact",
  "規模延伸": "Scale",
  "時程感": "Timeline",
  "事實密度型": "Fact-dense",
  "影響面型": "Impact-led",
  "故事感型": "Story-led",
  "願景式": "Vision",
  "客戶價值": "Customer value",
  "市場觀察": "Market view",
  "產品導向": "Product-led",
  "規模導向": "Scale-led",
  "里程碑導向": "Milestone-led",
  "產品優先": "Product first",
  "公司優先": "Company first",
  "市場優先": "Market first",
  "共同議題切入": "Shared-issue angle",
  "獨家數據切入": "Exclusive-data angle",
  "採訪邀請切入": "Interview-invite angle",
  "防禦型": "Defensive",
  "透明型": "Transparent",
  "主動引導": "Proactive steer",
  "FB 口吻": "Facebook voice",
  "LinkedIn 口吻": "LinkedIn voice",
  "Threads 口吻": "Threads voice",
  "Reframe 換框架": "Reframe",
  "Newsjack 借時事": "Newsjack",
  "反直覺數據": "Counterintuitive data",
  "人的故事": "Human story",
  "產業意義": "Industry meaning",
  "對比衝突": "Contrast and conflict",
  "首次/之最": "First / most",
  "在地連結": "Local link",
  "場景版": "Scene",
  "限時版": "Limited-time",
  "開放參觀版": "Open house",
  "自嘲版": "Self-deprecating",
  "時間軸版": "Timeline",
  "第三方查核版": "Third-party check",
  // Research
  "JTBD 框架": "JTBD framework",
  "5 Whys 框架": "5 Whys framework",
  "旅程地圖式": "Journey-map style",
  "主流 segment": "Mainstream segment",
  "新興 segment": "Emerging segment",
  "邊緣 segment": "Edge segment",
  "新客視角": "New customer view",
  "回購客視角": "Repeat customer view",
  "流失客視角": "Lapsed customer view",
  "Win 訪": "Win interview",
  "Loss 訪": "Loss interview",
  "Mixed 訪": "Mixed interview",
  "精簡版": "Short version",
  "完整版": "Full version",
  "兒童 / 老人友善": "Kid / senior friendly",
  "First-impression 重": "First-impression focus",
  "Task completion 重": "Task-completion focus",
  "Error recovery 重": "Error-recovery focus",
  "雙描述版": "Dual description",
  "盲測版": "Blind test",
  "前後測版": "Before / after test",
  "個人換算版": "Personal conversion",
  "對照版": "Comparison",
  "時間成本版": "Time cost",
  // Website
  "官網長文": "Website long-form",
  "品牌專欄": "Brand column",
  "案例深度": "Case deep-dive",
  "產品頁": "Product page",
  "常見問答": "FAQ",
  "成本版": "Cost",
  "取捨版": "Trade-offs",
  "失敗紀錄版": "Failure log",
  "口語版": "Plain talk",
  "比價版": "Price comparison",
  "反話術版": "Anti-spin",
  "每日價版": "Daily price",
  "會員優先版": "Member priority",
  "售罄戰報版": "Sell-out report",
};
