import type { TaskEnMap, VariantLabelEnMap } from "./types";

export const TASK_EN: TaskEnMap = {
  // ── quickTaskIG.ts ──
  "ig-30-caption-short": {
    question: "What is today's IG post about?",
    placeholder: "e.g. New launch / Customer story / Behind the scenes",
    inputs: { topic: { label: "Post topic" } },
  },
  "ig-30-pure-text-hook": {
    question: "Paste the post or article you plan to publish; I'll write IG hooks in different tones to lead it",
    placeholder: "Paste the full post text (the hook goes at the very start)",
    inputs: { article_body: { label: "Original post text" } },
  },
  "ig-30-reel-hook": {
    question: "What's this Reel's topic / selling point?",
    placeholder: "e.g. 30-second tutorial / Unboxing / Before-and-after",
    inputs: { topic: { label: "Reel topic" } },
  },
  "ig-30-reel-script-full": {
    question: "What value should this Reel convey?",
    placeholder: "e.g. 3 IG algorithm myths / How I went from 0 to 10K in 90 days",
    inputs: { topic: { label: "Reel topic / value to convey" } },
  },
  "ig-30-story-text": {
    question: "What do you want to say in today's Story?",
    placeholder: "e.g. Behind the scenes / Limited-time offer / Question / Poll",
    inputs: { topic: { label: "Story topic" } },
  },
  "ig-30-carousel-structure": {
    question: "What topic for the carousel? (tutorial / list / contrast / story)",
    placeholder: "e.g. 5 underrated IG algorithm tips / 3 mistakes I made learning design from scratch",
    inputs: { topic: { label: "Carousel topic" } },
  },
  "ig-30-bio-rewrite": {
    question: "Who is your IG account, what do you do, and who do you want to attract?",
    placeholder: "e.g. “I'm ___, I help ___ solve ___, previously ___”",
    inputs: { context: { label: "You / brand intro" } },
  },
  "ig-30-hashtag-set": {
    question: "Post topic / your niche?",
    placeholder: "e.g. Pour-over coffee / North American interior design / SaaS B2B",
    inputs: { topic: { label: "Topic / niche" } },
  },
  "ig-30-comment-reply": {
    question: "Paste the original user comment (or describe the situation)",
    placeholder: "What did the user say? Paste the whole thing",
    inputs: { user_comment: { label: "User comment" } },
  },
  "ig-30-dm-script": {
    question: "Which kind of DM do you want to handle? Paste sample messages",
    placeholder: "e.g. “Is this still in stock?” / “Unhappy with the product” / “Want to collaborate”",
    inputs: { scenario: { label: "DM scenario / sample message" } },
  },
  "ig-30-live-opening": {
    question: "Tonight's live topic / what do you want to talk about?",
    placeholder: "e.g. New shade swatches / Q&A / Unboxing / Tutorial",
    inputs: { topic: { label: "Live topic" } },
  },
  "ig-30-story-repost-strategy": {
    question: "What was the original Story about?",
    placeholder: "Paste the Story text / topic",
    inputs: { original_story: { label: "Original Story content" } },
  },
  "ig-30-threads-cross-post": {
    question: "Paste the IG caption (to be rewritten for Threads)",
    placeholder: "Paste the whole IG caption",
    inputs: { ig_caption: { label: "Original IG caption" } },
  },
  "ig-30-feed-single-object": {
    source: {
      short: "World Record Egg",
      metric: "52M+ likes, the most in IG history at the time",
      takeaway: "When the barrier is absurdly low, taking part becomes the content—a post needn't look good, it must be easy to join.",
    },
    question: "What small thing do you want everyone to do together?",
    placeholder: "e.g. Show the cup on your desk / Guess which packaging generation this is",
    inputs: { topic: { label: "Small thing to invite everyone to do" } },
  },
  "ig-30-reel-brand-event": {
    source: {
      short: "Duolingo “Death of Duo”",
      metric: "1.7B organic impressions in two weeks; Dua Lipa's comment on that IG post got 141K+ likes",
      takeaway: "A persona only matters if things can happen to it—the event needs consequences, and the audience's actions must decide them.",
    },
    question: "What could happen to your brand persona (mascot, owner, shop cat)?",
    placeholder: "e.g. Mascot quits / Sign blown away by a typhoon / Owner bets with staff",
    inputs: { topic: { label: "Brand persona + what could happen to it" } },
  },
  "ig-30-carousel-proof-set": {
    source: {
      short: "Heinz “Draw Ketchup”",
      metric: "$5.8M in earned media, 127x the amount spent on paid media",
      takeaway: "Rather than claim to be first, collect strangers' answers and let the conclusion emerge—evidence persuades more than adjectives.",
    },
    question: "What examples can you collect where everyone's answer comes out the same?",
    placeholder: "e.g. Ask customers to draw our product / How 100 people describe this flavor",
    inputs: { topic: { label: "Examples you can collect + the line you want to prove" } },
  },
  "ig-30-story-one-action": {
    source: {
      short: "Coinbase QR ad",
      metric: "20M+ scans within one minute; the official app crashed for about an hour",
      takeaway: "With only one interactive thing on screen, viewers have no second option—hesitation is created by extra elements.",
    },
    question: "What do you want Story viewers to do right now?",
    placeholder: "e.g. Scan to get a coupon / Vote for a flavor / DM a keyword",
    inputs: { topic: { label: "The one action you want them to take right away" } },
  },
  "ig-30-profile-self-insert": {
    source: {
      short: "Barbie selfie generator",
      metric: "Used 13M+ times after the filter launched",
      takeaway: "Brand visuals spread when others can “wear” them—make fans the star and lend them the stage.",
    },
    question: "What visual element of your brand can fans put on themselves?",
    placeholder: "e.g. Brand-color frame / Standard title card / Signature question",
    inputs: { topic: { label: "Visual element fans can apply" } },
  },
  "ig-30-live-host-relay": {
    source: {
      short: "Walmart TikTok live shopping",
      metric: "Viewership hit 7x expectations; account followers +25%",
      takeaway: "Switching people keeps viewers better than switching products—each handoff is a new opening, so latecomers needn't catch up.",
    },
    question: "What will this live sell? Who can take turns hosting?",
    placeholder: "e.g. Three staff + one longtime customer, selling winter new arrivals",
    inputs: { topic: { label: "Products + people who can take turns" } },
  },
  "ig-30-post-platform-firstday": {
    source: {
      short: "Threads launch",
      metric: "100M sign-ups within 5 days, the fastest ever at the time",
      takeaway: "A new platform takes off when existing relationships move over at once, not by rebuilding—on day one, give longtime fans a must-follow reason.",
    },
    question: "Which new platform are you taking fans to? What do you have on the old one that they'd hate to lose?",
    placeholder: "e.g. Moving to Threads; our daily question on IG moves over",
    inputs: { topic: { label: "Target platform + the content you most want to keep" } },
  },
  "ig-30-feed-account-takeover": {
    source: {
      short: "Singapore LTA “Baby bus selfie” (寶寶在公車上自拍)",
      metric: "12,500+ likes in 3 days",
      caveat: "Government account; riding a meme—take only the “account takeover” mechanic.",
      takeaway: "The official account pretends to be “taken over” by a very contrasting, cute outsider, with your own setting (the bus) hidden in the frame; the tone instantly softens and people comment to guess and play along.",
    },
    question: "What is your most iconic scene or object? Who taking over the account would be funniest?",
    placeholder: "e.g. The store's cash register / Let the shop cat take over for a day",
    inputs: { topic: { label: "Brand setting + the taker-over (baby, pet, mascot, intern…)" } },
  },
  "ig-30-carousel-fake-callout": {
    source: {
      short: "Your Social Team fake call-out carousel",
      metric: "50K views in 24 hours",
      caveat: "Agency self-reported; the page shows no year, inferred as 2026-08 from the post ID.",
      takeaway: "The first slide uses a conflict-style fake call-out to stop the scroll, the middle frames your service's benefits as “things stolen” from the target, and the last slide reveals it's a joke—so the pitch gets read to the end.",
    },
    question: "What are your three biggest benefits? Whom (a made-up target) will you “call out”?",
    placeholder: "e.g. Call out “you, working late until 10 every day” / Benefits: auto scheduling, one-click reports, no weekend logins",
    inputs: { topic: { label: "Made-up call-out target + three benefits" } },
  },
  "ig-30-reel-native-language-try": {
    source: {
      short: "NYC mayor 曼達尼 (Zohran Mamdani)'s Chinese-language promo Reel",
      metric: "IG post 1.4M+ likes, about 37K comments",
      caveat: "Politician's account.",
      takeaway: "Open by admitting “I don't speak this language, but I want to try,” then explain one concrete perk in their native language; clumsiness itself shows sincerity, and people comment to correct it and share with fellow community members.",
    },
    question: "Which group speaking a different language do you want to address, and with which concrete perk?",
    placeholder: "e.g. To Japanese tourists: show your passport for 10% off, until 10/31",
    inputs: { topic: { label: "Audience's language + concrete perk (numbers, deadline)" } },
  },
  "ig-30-live-vote-bracket": {
    source: {
      short: "SwissWatchExpo “The Grail Bracket”",
      metric: "Hundreds of comments, the brand's most-engaged live ever",
      caveat: "Brand self-reported; numbers are imprecise.",
      takeaway: "16 talked-about products fight in groups, comments vote each round, and dual cameras compare details side by side—even high-ticket items can build trust by “watching a match,” with sales closed by DM after the live.",
    },
    question: "Which 8 or 16 products can face off? What criteria will viewers use to choose?",
    placeholder: "e.g. 8 signature breads / Criterion: which you'd most want for breakfast",
    inputs: { topic: { label: "Contestant products (8 or 16) + voting criterion" } },
  },
  "ig-30-profile-one-rule-debut": {
    source: {
      short: "珍妮佛勞倫斯 (Jennifer Lawrence) joins IG",
      metric: "3M followers gained in under 24 hours",
      caveat: "Celebrity account, relies on existing fame.",
      takeaway: "Open the account with no polished photos; the first video sets one very personal rule (“if you roast me, I'm out”), and the Story flips the same joke, making “opening an account” itself the talking point.",
    },
    question: "Are you opening a new account (or relaunching)? What's your brand's most distinctive line?",
    placeholder: "e.g. Dessert shop opens IG / Personality: we only make until sold out, no pre-orders",
    inputs: { topic: { label: "New account / relaunch + the brand's most distinctive line" } },
  },
  "ig-30-comment-fill-blank": {
    source: {
      short: "InterContinental Taipei “The First 80”",
      metric: "82,956 entries, about 1,037 people competing for 1 spot",
      caveat: "Combined across FB, IG and Threads.",
      takeaway: "A fill-in-the-blank (“I love Taipei because ___”) lowers the comment barrier to the minimum, then asking people to tag a companion makes every comment UGC and spreads the campaign; with only 80 spots, scarcity makes people rush to write.",
    },
    question: "What scarce prize can you give? What sentence do you want people to comment with?",
    placeholder: "e.g. 30 spots for a new-store tasting / Pattern: “I most want to bring ___ here, because ___”",
    inputs: { topic: { label: "Prize and spots + the comment pattern you want" } },
  },
  "ig-30-comment-ex-partner-jab": {
    source: {
      short: "Samsung's comment under Rosé's IG post",
      metric: "That comment got 212K likes and 2,000+ replies",
      caveat: "Global brand; reports don't say which official account commented.",
      takeaway: "When someone posts a big post related to your category, the brand leaves a friendly-but-pointed line from an existing relationship (former ambassador, former partner), with no statement and no follow-up explanation, letting the reply thread ferment on its own.",
    },
    question: "Which recent hot post relates to your category? What existing relationship do you have with the poster?",
    placeholder: "e.g. A blogger posts she's looking for good coffee / We once sent her beans",
    inputs: { topic: { label: "What the hot post says + your relationship with the poster" } },
  },
  "ig-30-dm-sample-request": {
    source: {
      short: "Plainspeak IG DM trial packs",
      metric: "Thousands of trial packs shipped",
      caveat: "Reports only say “thousands,” no exact number.",
      takeaway: "Make “DM us” the only way to get a free trial, collecting a lead list and first-hand questions at once; the most-asked DM questions later became product changes (e.g. opening single-pack sales).",
    },
    question: "What trial item can you give? What's the one thing you most want to ask customers?",
    placeholder: "e.g. Single drip bag / Want to know what time everyone drinks coffee",
    inputs: { topic: { label: "Trial item + one thing to ask customers" } },
  },

  // ── quickTaskIG60.ts ──
  "ig-60-feed-full": {
    question: "What is today's IG post about?",
    placeholder: "e.g. New launch, customer story, behind the scenes",
    inputs: { topic: { label: "Post topic" } },
  },
  "ig-60-reel-full": {
    question: "What's this Reel's topic / selling point?",
    placeholder: "e.g. 30-second tutorial / Unboxing / Before-and-after",
    inputs: { topic: { label: "Reel topic" } },
  },
  "ig-60-story-3frame": {
    question: "What should the Story convey?",
    placeholder: "e.g. New product teaser, limited-time offer, Q&A interaction",
    inputs: { topic: { label: "Story topic" } },
  },
  "ig-60-countdown-5day": {
    question: "What are you counting down to?",
    placeholder: "e.g. New product / Anniversary sale / Live",
    inputs: {
      event_name: { label: "Event name" },
      key_offer: { label: "Main hook / offer" },
    },
  },
  "ig-60-highlight-suite": {
    question: "What kind of highlights do you want to feature?",
    placeholder: "e.g. Product intro / Founder story / Customer testimonials",
    inputs: { highlight_focus: { label: "Highlight topic" } },
  },
  "ig-60-live-suite": {
    question: "What will this live cover / sell? Include any live-only offers",
    placeholder: "e.g. Unboxing the new face wash—low-irritation, removes makeup, rinses easily; live-only discount code LIVE20",
    inputs: { live_topic: { label: "Live topic / key points / live-only offer" } },
  },
  "ig-60-live-event": {
    question: "What number do you want to hit with viewers during this live? What will you give on the spot when you hit it?",
    placeholder: "e.g. Anniversary unboxing live, goal of 300 concurrent viewers, 3 new products raffled on the spot if hit; the next goal is announced even if missed",
    inputs: { live_goal: { label: "Live topic / group goal / reward for hitting it" } },
  },
  "ig-60-live-founder": {
    question: "Why did you (the founder) start this brand? What product or decision do you want to discuss?",
    placeholder: "e.g. I've had sensitive skin for 10 years and everything I tried stung, so I made my own; this time I want to explain why the new sunscreen costs 1,280",
    inputs: { founder_story: { label: "Founding motivation / the product or decision to discuss" } },
  },
  "ig-60-serial-3": {
    question: "What story do you want to serialize?",
    placeholder: "Customer transformation / Team growth / Product journey",
    inputs: { story_topic: { label: "Series topic" } },
  },
  "ig-60-viral-rewrite": {
    question: "Paste the viral original / link / topic",
    placeholder: "Original viral post / link / topic",
    inputs: {
      viral_source: { label: "Viral original / link / topic" },
      brand_angle: { label: "Brand angle (optional)" },
    },
  },
  "ig-60-testimonial-rewrite": {
    question: "Paste the customer testimonial / interview / review",
    placeholder: "Customer's own words, verbatim interview, text from a review screenshot",
    inputs: {
      testimonial_source: { label: "Original testimonial" },
      consent_status: { label: "Publishing consent obtained?", placeholder: "yes / anonymized / pending" },
    },
  },

  // ── quickTaskIGLive.ts ──
  "ig-60-live-versus": {
    question: "Who will face off? What will each bring in turn?",
    placeholder: "e.g. Head chef vs pastry chef, each picks the 5 dishes they're most confident in and takes turns making them; or a new product vs a ten-year bestseller",
    inputs: { versus_setup: { label: "The two sides / what each will bring" } },
  },
  "ig-60-live-comeback": {
    question: "How long were you gone? Why? What do you plan to do now you're back?",
    placeholder: "e.g. Off for eight months because of the shop renovation and family matters; coming back with a weekly Thursday live, starting with the new menu",
    inputs: { comeback_context: { label: "Length of gap / reason / what you'll do on return" } },
  },
  "ig-60-live-collab-drop": {
    question: "Who are you collaborating with? What will you reveal live on the spot?",
    placeholder: "e.g. Limited-edition dessert co-branded with the café next door, pre-orders open live; their account has 20K followers, ours 8K",
    inputs: { collab_setup: { label: "Collab partner / what to launch live" } },
  },
  "ig-60-live-first-ever": {
    question: "Is this your first live? What do you most want viewers to see?",
    placeholder: "e.g. Open three years and never gone live; want to show the kitchen and answer the reservation rules people keep asking about",
    inputs: { first_live_context: { label: "Account background / what you want viewers to see first" } },
  },
  "ig-60-live-behind-scenes": {
    question: "What one thing will you finish on camera today?",
    placeholder: "e.g. Pack and ship all 50 of today's orders; or finish shelving the new stock",
    inputs: { workday_anchor: { label: "The one thing to finish today" } },
  },
  "ig-60-live-crew": {
    question: "Who will appear on camera with you? What's each person's role?",
    placeholder: "e.g. Me, the store manager, a chef of five years, a newcomer from last month; want to talk about the craziest customer",
    inputs: { crew_setup: { label: "Who's on camera / each role / what to talk about" } },
  },

  // ── quickTaskThreads.ts ──
  "th-30-reply-mock-statement": {
    source: {
      short: "錢都 (Qiandu) “Clam apology statement”",
      metric: "Official reply 160K+ likes (original post 210K+ likes)",
      takeaway: "A user joked in a complaint, “my clams are eating my bacon beef”; the brand replied in formal statement format—“錢都 here on behalf of the clams, formally apologizes to colleague bacon beef”—writing the product as an employee who erred.",
    },
    question: "What joke did a user make about your product? (Paste the original line)",
    placeholder: "e.g. “Are your pearls on strike? There are only five in a cup”",
    inputs: { topic: { label: "The user's joke complaint, verbatim" } },
  },
  "th-30-reply-one-word-magic": {
    source: {
      short: "UNIQLO self-checkout “Magic~”",
      metric: "Official reply got 140K hearts",
      takeaway: "A user asked how the self-checkout recognizes a whole basket of clothes instantly; UNIQLO replied only “Magic~”—not explaining preserved the wonder, and in-the-know users filled in the answer in the comments.",
    },
    question: "What do you do that makes customers wonder “how did they do that?”",
    placeholder: "e.g. Delivery arrives in 15 minutes / Every layer of the cake cross-section is the same thickness",
    inputs: { topic: { label: "The amazing thing + the real mechanism (for your reference, won't be written out)" } },
  },
  "th-30-post-self-deprecating-ask": {
    source: {
      short: "松屋 (Matsuya) “Why doesn't anyone eat at Matsuya?”",
      metric: "Nearly 7K likes, 1,700+ comments",
      caveat: "Flooded with negative reviews; be ready to take criticism, and no follow-up response was reported.",
      takeaway: "The brand showed vulnerability and half-jokingly asked “why does no one come? Are we really pricier?”, and comments exploded—but mostly real criticism, so the key of this card is how you handle it afterward.",
    },
    question: "What do you most want to know about why customers don't come / buy?",
    placeholder: "e.g. Why does no one come on weekday evenings / Are our bento boxes really pricier?",
    inputs: { topic: { label: "One thing to ask customers" } },
  },
  "th-30-reply-verse": {
    source: {
      short: "台鐵 (Taiwan Railways) three-line verse reply (“被火車誤點的徐志摩”, Xu Zhimo delayed by the train)",
      metric: "38K likes",
      caveat: "Only one outlet reported the number.",
      takeaway: "A user said “40 minutes by bike, only 4 minutes by train”; Taiwan Railways turned their own numbers into a three-line parallel poem, hid the product's benefits (fast, restful) in the middle line, and users dubbed the social editor “被火車誤點的徐志摩 (Xu Zhimo, delayed by the train).”",
    },
    question: "What number comparison involving you appears in a user's post? (Paste the original line)",
    placeholder: "e.g. “Cooking myself takes 1 hour, your delivery arrives in 20 minutes”",
    inputs: { topic: { label: "The user's original line (with the number comparison)" } },
  },
  "th-30-reply-celebrity-pile-on": {
    source: {
      short: "始源 (Siwon) × Ministry of Agriculture / local farmers' associations scramble",
      metric: "始源 (Siwon)'s post got 140K likes in 1 day; local farmers' association editors chained in to compete for a collaboration",
      caveat: "The numbers are from 始源 (Siwon)'s post, not the brand replies.",
      takeaway: "始源 (Siwon) posted Taiwanese fruit; the Ministry of Agriculture replied “Got it, let me go ask the boss,” and 梧棲農會 (Wuqi Farmers' Association) filmed a video with a cheer stick—when a celebrity calls out a whole category, the first brand to reply in a fan's voice gets the most traffic, and the chain replies push the buzz further.",
    },
    question: "Which celebrity or KOL recently posted about your category? What did they say?",
    placeholder: "e.g. A Korean star said they badly want Taiwanese pineapple cakes / A YouTuber said they can't find good soy milk",
    inputs: { topic: { label: "Who the celebrity is + what they said" } },
  },
  "th-30-reply-personified-apology-deal": {
    source: {
      short: "Domino's “The mayo has its own ideas”",
      metric: "Complaint post nearly 10K likes, nearly 1M views",
      caveat: "The numbers are from the complaint post, not the brand reply.",
      takeaway: "A user posted a pizza with mayo squeezed into a giant S; Domino's replied “This mayo has its own ideas…”, DM'd a replacement pizza, then launched a nationwide limited-time promo code named after the incident—a complaint became a national talking point.",
    },
    question: "What did the user complain about? (Paste the original line) What compensation and limited-time deal can you offer?",
    placeholder: "e.g. “All the pearls in my milk tea are stuck together” / Free replacement + second cup 50% off nationwide through Sunday",
    inputs: { topic: { label: "Original complaint + compensation + limited-time deal you can offer" } },
  },
  "th-30-post-reverse-seasonal": {
    source: {
      short: "Danyaoshi skips Mid-Autumn gift boxes this year",
      metric: "26K+ likes",
      caveat: "Rode a political controversy (sheltered-workshop gift box budget); most brands shouldn't copy the reasoning.",
      takeaway: "The brand announced it wouldn't make the Mid-Autumn gift box everyone expected this year and asked people to buy from sheltered workshops instead—giving up one holiday sale earned more goodwill than selling the boxes.",
    },
    question: "What seasonal product does everyone assume you'll release this year? Where do you want to redirect demand?",
    placeholder: "e.g. New Year gift boxes / Ask people to buy from nearby small farms or social welfare organizations instead",
    inputs: { topic: { label: "Seasonal product skipped this year + where to redirect" } },
  },

  // ── quickTaskLine.ts ──
  "ln-30-survey-segment-menu": {
    source: {
      short: "Calbee LINE official account in-housing",
      metric: "Message open rate about 1.8x, click rate 2x; daily survey replies about 2.8x after participatory content",
      caveat: "Japan case; only multiples, no baseline value, and no comparison period stated.",
      takeaway: "Open rate is decided by “the notification line + the message opener,” and engagement by “a monthly participatory, changing rich menu”: ask one question the moment someone adds you, segment by answer, and keep A/B testing the notification copy.",
    },
    question: "Which survey question will you use to segment friends? What participation activity can you run each month?",
    placeholder: "e.g. When do you snack most? (at work / binge-watching / after a workout) / Monthly vote on next month's limited flavor",
    inputs: { topic: { label: "Segmentation survey question + monthly participation activity" } },
  },
  "ln-30-segmented-single-action": {
    source: {
      short: "幣託 BitoPro segmented messages",
      metric: "Segmented message open rate passed 50% (up about 60%), click rate 2x, friends +35% a year",
      caveat: "Full-year aggregate announced at LINE's digital transformation annual conference, with no explanation of how audiences were split.",
      takeaway: "Don't blast one message to everyone for the same campaign; split friends into groups by behavior and rewrite each group's opener and action, and open rate can rise from the average to over 50%.",
    },
    question: "What are you pushing this time? Roughly what groups can your friends be split into?",
    placeholder: "e.g. Anniversary sale / New joiners, no interaction for six months, regulars",
    inputs: { topic: { label: "What to push this time + rough friend segments" } },
  },
  "ln-30-rich-menu-order-entry": {
    source: {
      short: "月眉鴨肉焿 (Yuemei Duck Soup) LINE official account",
      metric: "Rich menu annual click rate about 55%; about 20%–40% of new customers come via LINE",
      caveat: "Annual numbers announced at LINE's digital transformation annual conference, with no single-campaign details.",
      takeaway: "Local restaurants treat the rich menu as a permanent “order / reserve” entry, which is steadier than repeated blasts; a blast should push just one featured item of the day, linking straight to ordering.",
    },
    question: "What do customers most often do via LINE? Which featured item do you want to push today?",
    placeholder: "e.g. Reserve, takeout, view menu, ask opening hours / Today's special: duck soup with noodles",
    inputs: { topic: { label: "What customers often do + today's special" } },
  },
  "ln-30-triggered-moment-messages": {
    source: {
      short: "TENTIAL LINE ID linkage situational messages",
      metric: "ID-linked users' LTV 1.2x; new initiative ROAS 500% in 3 months",
      caveat: "Japan case; vendor's own press release, not third-party reporting.",
      takeaway: "First guide members to link LINE with their member account, then trigger personal-moment messages such as “coupon about to expire,” “item you viewed is restocked,” and “you've been upgraded.”",
    },
    question: "What personal moments do your customers have? (expiry, restock, upgrade, birthday…)",
    placeholder: "e.g. Points expire at month end / Out-of-stock item restocked / Upgrade to VIP after 5 purchases",
    inputs: { topic: { label: "Personal moments that can trigger messages" } },
  },
};

export const VARIANT_LABEL_EN: VariantLabelEnMap = {
  // quickTaskIG.ts
  "生活感版": "Lifestyle",
  "品牌感版": "Brand voice",
  "問句式": "Question",
  "反問式": "Rhetorical question",
  "數字式": "Numbers",
  "反差式": "Contrast",
  "懸念開場": "Suspense opening",
  "反差開場": "Contrast opening",
  "直接挑釁": "Direct provocation",
  "教學型": "Tutorial",
  "故事型": "Story",
  "反差型": "Contrast",
  "驚奇式": "Surprise",
  "提問式": "Question",
  "幕後式": "Behind the scenes",
  "教學清單型": "Tutorial list",
  "專家定位": "Expert positioning",
  "個性風格": "Personality style",
  "結果導向": "Results-driven",
  "曝光導向 (20)": "Reach-driven (20)",
  "品牌導向 (8)": "Brand-driven (8)",
  "利基導向 (12)": "Niche-driven (12)",
  "溫暖式": "Warm",
  "幽默式": "Humorous",
  "邀請式": "Inviting",
  "詢價回覆": "Price inquiry reply",
  "售後安撫": "After-sales reassurance",
  "合作回覆": "Collaboration reply",
  "懸念式": "Suspense",
  "互動式": "Interactive",
  "直球式": "Straightforward",
  "精選封面型": "Highlight cover",
  "Feed 改編型": "Feed adaptation",
  "後續限時動態型": "Follow-up Story",
  "觀點式": "Opinion",
  "故事縮短": "Short story",
  "極簡版": "Minimal",
  "邀請版": "Invitation",
  "紀錄版": "Record",
  "出事版": "Something happens",
  "求救版": "Plea for help",
  "反轉版": "Twist",
  "實例版": "Examples",
  "對照版": "Side by side",
  "統計版": "Statistics",
  "純動作版": "Action only",
  "倒數版": "Countdown",
  "選一個版": "Pick one",
  "模板版": "Template",
  "稱號版": "Title",
  "會員版": "Membership",
  "接力版": "Relay",
  "對打版": "Face-off",
  "顧客上場版": "Customer on stage",
  "搬家版": "Moving day",
  "限定版": "Limited",
  "先搶版": "Be first",
  "寶寶接管": "Baby takeover",
  "寵物接管": "Pet takeover",
  "實習生接管": "Intern takeover",
  "點名你": "Call out you",
  "點名老闆": "Call out the boss",
  "點名週一": "Call out Monday",
  "承認不會版": "Admit you can't",
  "努力講完版": "Push through",
  "請你糾正版": "Please correct me",
  "8 強版": "Top 8",
  "16 強版": "Top 16",
  "爆冷版": "Upset",
  "規則版": "Rule",
  "自嘲版": "Self-deprecating",
  "加碼版": "Bonus",
  "故事填空": "Story fill-in",
  "回憶填空": "Memory fill-in",
  "願望填空": "Wish fill-in",
  "前任角度": "Ex angle",
  "老朋友角度": "Old friend angle",
  "同城角度": "Same city angle",
  "一個字就寄": "One word and we ship",
  "限量版": "Limited quantity",
  "問一題版": "Ask one question",

  // quickTaskIG60.ts
  "情感版": "Emotional",
  "理性版": "Rational",
  "故事版": "Story",
  "數據版": "Data",
  "懸念版": "Suspense",
  "教學版": "Tutorial",
  "反差版": "Contrast",
  "節奏版": "Rhythm",
  "前情鋪陳": "Setup",
  "重點揭曉": "Key reveal",
  "CTA 收束": "CTA close",
  "第5天": "Day 5",
  "第4天": "Day 4",
  "第3天": "Day 3",
  "第2天": "Day 2",
  "第1天": "Day 1",
  "商品": "Products",
  "客評": "Reviews",
  "案例": "Case studies",
  "00:00-03:00 黃金開場": "00:00-03:00 Golden opening",
  "03:00-10:00 主軸切入": "03:00-10:00 Main theme",
  "10:00-18:00 深度互動": "10:00-18:00 Deep interaction",
  "18:00-23:00 高潮／優惠公布": "18:00-23:00 Climax / offer reveal",
  "23:00-28:00 限時催單": "23:00-28:00 Last-call push",
  "28:00-30:00 收尾預告": "28:00-30:00 Wrap-up teaser",
  "T-24h 預熱宣告": "T-24h Warm-up announcement",
  "00:00-03:00 目標宣告": "00:00-03:00 Goal announcement",
  "03:00-10:00 第一波衝刺": "03:00-10:00 First push",
  "10:00-18:00 內容填充": "10:00-18:00 Content filler",
  "18:00-24:00 臨門一腳": "18:00-24:00 Final push",
  "24:00-28:00 達標兌現": "24:00-28:00 Goal reached, reward delivered",
  "28:00-30:00 下一個目標": "28:00-30:00 Next goal",
  "00:00-04:00 起源故事": "00:00-04:00 Origin story",
  "04:00-10:00 為什麼是我": "04:00-10:00 Why me",
  "10:00-20:00 事前徵集提問": "10:00-20:00 Pre-collected questions",
  "20:00-26:00 最難的三題": "20:00-26:00 The three hardest questions",
  "26:00-30:00 邀請與下一步": "26:00-30:00 Invitation and next step",
  "第 1 集": "Episode 1",
  "第 2 集": "Episode 2",
  "第 3 集": "Episode 3",
  "保結構式": "Keep structure",
  "情感放大式": "Emotion amplified",
  "數據式": "Data",
  "故事式": "Story",
  "對比式": "Comparison",
  "情感式": "Emotional",
  "簡短式": "Short",

  // quickTaskIGLive.ts
  "T-24h 對打預告": "T-24h Face-off teaser",
  "00:00-03:00 雙方登場": "00:00-03:00 Both sides enter",
  "03:00-12:00 第一輪對打": "03:00-12:00 Round 1",
  "12:00-21:00 第二輪對打": "12:00-21:00 Round 2",
  "21:00-27:00 觀眾投票輪": "21:00-27:00 Audience vote round",
  "27:00-30:00 不分勝負收尾": "27:00-30:00 Close with no winner",
  "00:00-04:00 先講消失去哪": "00:00-04:00 Where I disappeared to",
  "04:00-10:00 空白期發生什麼": "04:00-10:00 What happened during the gap",
  "10:00-18:00 回答最想問的": "10:00-18:00 Answer the top questions",
  "18:00-25:00 接下來要做什麼": "18:00-25:00 What's next",
  "25:00-30:00 重新開始的邀請": "25:00-30:00 Invitation to start again",
  "T-1h 各自暖場": "T-1h Separate warm-ups",
  "00:00-05:00 連麥合流": "00:00-05:00 Join on a live call",
  "05:00-15:00 為什麼是這個組合": "05:00-15:00 Why this pairing",
  "15:00-22:00 當場發布": "15:00-22:00 Live launch",
  "22:00-30:00 雙向分流": "22:00-30:00 Two-way traffic split",
  "00:00-05:00 承認這是第一次": "00:00-05:00 Admit it's the first time",
  "05:00-13:00 只有第一次才做的事": "05:00-13:00 Things only a first time allows",
  "13:00-22:00 回答沒講過的": "13:00-22:00 Answer what you've never said",
  "22:00-27:00 把人拉進來連線": "22:00-27:00 Bring people on a live call",
  "27:00-30:00 約下一次": "27:00-30:00 Set the next one",
  "00:00-03:00 今天要做完什麼": "00:00-03:00 What gets done today",
  "03:00-12:00 動手做第一段": "03:00-12:00 First stretch of work",
  "12:00-20:00 抬頭回留言": "12:00-20:00 Look up and reply to comments",
  "20:00-27:00 動手做收尾段": "20:00-27:00 Final stretch of work",
  "27:00-30:00 完成的那一刻": "27:00-30:00 The finishing moment",
  "00:00-05:00 逐一介紹角色": "00:00-05:00 Introduce each person",
  "05:00-13:00 有舊事可挖的題": "05:00-13:00 Topics with old stories to dig up",
  "13:00-21:00 指名回留言": "13:00-21:00 Reply to comments by name",
  "21:00-27:00 全員都要講的題": "21:00-27:00 Topic everyone answers",
  "27:00-30:00 下次找誰來": "27:00-30:00 Who joins next time",

  // quickTaskThreads.ts
  "正式聲明版": "Formal statement",
  "內部處分版": "Internal disciplinary notice",
  "公關部長版": "PR chief",
  "一字版": "One word",
  "兩字版": "Two words",
  "表情符號版": "Emoji",
  "示弱版": "Show vulnerability",
  "撒嬌版": "Coy",
  "認真問版": "Serious ask",
  "排比版": "Parallelism",
  "新詩版": "Free verse",
  "對聯版": "Couplet",
  "粉絲版": "Fan voice",
  "官方版": "Official voice",
  "接龍版": "Chain reply",
  "擬人版": "Personified",
  "正經版": "Straight-faced",
  "公益版": "Public good",
  "惜福版": "Cherish what we have",
  "品質版": "Quality",

  // quickTaskLine.ts
  "興趣分眾": "By interest",
  "時段分眾": "By time of day",
  "頻率分眾": "By frequency",
  "行為分群": "By behavior",
  "新舊分群": "New vs existing",
  "價值分群": "By value",
  "點餐優先": "Ordering first",
  "訂位優先": "Reservations first",
  "優惠優先": "Offers first",
  "到期提醒": "Expiry reminder",
  "補貨通知": "Restock alert",
  "升等恭喜": "Upgrade congrats",
};
