import type { TaskEnMap, VariantLabelEnMap } from "./types";

export const TASK_EN: TaskEnMap = {
  "tt-30-opening-hook": {
    question: "What is this TikTok about?",
    placeholder: "e.g. 3 underrated Notion AI uses / A design mistake I made",
    inputs: { topic: { label: "Topic" } },
    source: {
      short: "e.l.f. “#eyeslipsface”",
      metric: "1 billion plays in 6 days, the fastest at the time",
      takeaway: "The memorable part is the sound, not the visuals: the brand commissioned original music, so the hook works even when viewers aren't looking at the screen.",
    },
  },
  "tt-30-full-script": {
    question: "What topic do you want your TikTok to cover?",
    placeholder: "e.g. Bust a common myth",
    inputs: { topic: { label: "TikTok topic" } },
  },
  "tt-30-caption-rhythm": {
    question: "Paste your voiceover script (or TikTok topic)",
    placeholder: "Paste the full voiceover",
    inputs: { voiceover: { label: "Voiceover script / topic" } },
  },
  "tt-30-visual-illusion": {
    question: "What do you want to film a “one-second flip” of?",
    placeholder: "e.g. A stroller that folds in one second / A tea bag that changes color only when dunked",
    inputs: { topic: { label: "Product / topic + the moment you want seen" } },
  },
  "tt-30-process-payoff": {
    question: "What making or fixing process can you film?",
    placeholder: "e.g. 90 seconds of pour-over coffee / A messy closet made tidy / Cake piping",
    inputs: { topic: { label: "Process to film + finished result" } },
  },
  "tt-30-beat-sync": {
    question: "Which items or shots do you want to string together?",
    placeholder: "e.g. 8 flavors taking turns / A week of outfits / Store to shipping",
    inputs: { topic: { label: "Shots or items to link" } },
  },
  "tt-30-scale-reveal": {
    question: "What scale, quantity, or detail deserves to be seen?",
    placeholder: "e.g. A warehouse shipping 3,000 boxes a day / The 12 steps behind one lens",
    inputs: { topic: { label: "The scale or detail to show" } },
  },
  "tt-30-real-reaction": {
    question: "Who will have an unmissable reaction the first time they use your product?",
    placeholder: "e.g. Grandma's first time with a voice assistant / A customer smelling fresh-baked bread",
    inputs: { topic: { label: "Who + the situation that triggers the reaction" } },
  },
  "tt-30-bio-rewrite": {
    question: "Who are you or your account, what do you do, and who do you want to attract?",
    placeholder: "Describe yourself + the audience you want to attract",
    inputs: { context: { label: "Your bio" } },
  },
  "tt-30-hashtag-set": {
    question: "TikTok topic or niche",
    placeholder: "e.g. Office tips / Beauty reviews",
    inputs: { topic: { label: "Topic / niche" } },
  },
  "tt-30-caption-description": {
    question: "What is the video about? What action do you want viewers to take?",
    placeholder: "Video content + call-to-action goal",
    inputs: { context: { label: "Content + call to action" } },
  },
  "tt-30-duet-angle": {
    question: "Paste the URL of the video to duet, or describe it",
    placeholder: "TikTok URL or video description",
    inputs: { target: { label: "Target video" } },
    source: {
      short: "Ocean Spray × Nathan Apodaca “Dreams”",
      metric: "Original video: 80 million views, 12.9 million likes, 143K comments",
      takeaway: "The brand didn't start this video; it caught momentum a regular person had already built. For duets, find what people are already doing instead of inventing a meme.",
    },
  },
  "tt-30-trend-remix": {
    question: "Which trend or sound do you want to ride?",
    placeholder: "e.g. “oh no oh no oh no no no” / A lip-sync trend",
    inputs: { trend: { label: "Trend / audio" } },
  },
  "tt-30-comment-reply": {
    question: "Paste the comment to reply to",
    placeholder: "User comment",
    inputs: { user_comment: { label: "User comment" } },
  },
  "tt-30-live-opening": {
    question: "Tonight's livestream topic",
    placeholder: "e.g. New product unboxing / Q&A / Swatches",
    inputs: { topic: { label: "Livestream topic" } },
  },
  "tt-30-product-hero": {
    question: "Which product to feature? What's the one thing you most want seen?",
    placeholder: "e.g. Screen-free kids' audio story annual pass / Bedtime companionship",
    inputs: { topic: { label: "Product + key selling point" } },
  },
  "tt-30-product-asmr": {
    question: "Which product's texture or feel do you want to film?",
    placeholder: "e.g. Storybook cover paper texture / The unboxing moment",
    inputs: { topic: { label: "Product + texture to highlight" } },
  },
  "tt-30-text-hook-card": {
    question: "What's the one line you want viewers to see?",
    placeholder: "e.g. Stop using your phone to soothe your baby to sleep",
    inputs: { topic: { label: "Claim / the one line to say" } },
  },
  "tt-30-storyboard": {
    question: "Paste your script, or describe what you want to film",
    placeholder: "Paste an existing script, or describe the topic and let AI plan from scratch",
    inputs: { topic_or_script: { label: "Script or video topic" } },
  },
  "tt-30-before-after": {
    question: "What changed after using it?",
    placeholder: "e.g. 40-minute bedtime battle → asleep after 10 minutes of stories",
    inputs: { topic: { label: "Situation before use → change after use" } },
  },
  "tt-30-live-relay-host": {
    question: "What is this livestream selling? Who can take turns hosting?",
    placeholder: "e.g. Owner + senior staff member + a regular customer",
    inputs: { topic: { label: "Products + people who can take turns on camera" } },
    source: {
      short: "Walmart TikTok livestream shopping",
      metric: "Viewership hit 7x expectations; account followers +25%",
      takeaway: "Viewers drop off when they can't tell what's going on. Re-explaining the premise at every host change wins back a batch of new arrivals every 10 minutes.",
    },
  },
  "tt-30-profile-self-aware": {
    question: "What do people joke about most when it comes to you?",
    placeholder: "e.g. Tight seats / Long lines / Ugly packaging",
    inputs: { topic: { label: "The thing people joke about most" } },
    source: {
      short: "Ryanair self-deprecating short videos",
      metric: "16 videos in one month, nearly 30 million views",
      takeaway: "An account persona should grow from what others already say, not from how the brand wants to be seen. Own the joke and you go from being laughed at to hosting it.",
    },
  },
  "tt-30-storyboard-catch-wave": {
    question: "Has anyone filmed something about you on their own?",
    placeholder: "e.g. A customer's own unboxing video / Someone dancing outside the store",
    inputs: { topic: { label: "Content someone has already made on their own" } },
    source: {
      short: "Ocean Spray × Nathan Apodaca",
      metric: "Original video: 80 million views, 12.9 million likes",
      takeaway: "Viral moments are usually caught by brands, not made by them. Keep the original creator as the lead in your follow-up and the brand in second place, so people are willing to share it again.",
    },
  },
  "tt-30-live-landmark-launch": {
    question: "What new product is launching? Is there a buzzworthy location? What's the limited quantity?",
    placeholder: "e.g. New-flavor chili sauce / Streaming from the rooftop of an old shop / Limited to 3,000 jars",
    inputs: { topic: { label: "New product + livestream location + limited quantity" } },
    source: {
      short: "Sambal Nyet new-product first-sale livestream on TikTok Shop",
      metric: "RM2 million sold in 1 min 51 s; 388K concurrent viewers",
      caveat: "Malaysian case; the brand was founded by the creator himself, who brought his own fans.",
      takeaway: "Turn a product launch into a livestream event with a date, a landmark set, and a limited-quantity number, so the rush itself becomes content, then post results afterward to earn a second wave of buzz.",
    },
  },
  "tt-30-account-staff-trend-lines": {
    question: "What is your account goal? Which staff are willing to be on camera?",
    placeholder: "e.g. Turn college students into regulars / Two managers and a part-timer who dances well",
    inputs: { topic: { label: "Account goal + staff who can appear on camera" } },
    source: {
      short: "コメダ珈琲店 (Komeda's Coffee) official TikTok",
      metric: "Followers passed 200K; 220 million total views, top video 4.3 million",
      caveat: "Japanese case; press release from the agency running the account, and view counts are cumulative.",
      takeaway: "Use product videos to learn what your audience wants to watch, then lock in two series: staff on camera and trending formats made brand-specific. Tie the KPI to turning young people into regulars, not follower count.",
    },
  },
  "tt-30-comment-ugc-hack": {
    question: "Has any customer recently filmed a “new way to eat or use” your product on TikTok?",
    placeholder: "e.g. Someone sandwiched our ice cream in a waffle / Added two servings of boba to the drink",
    inputs: { topic: { label: "The customer's new way to eat or use it" } },
    source: {
      short: "McDonald's comment on the “Cookie McDouble” hack",
      metric: "Creator's video: 10.6 million views, nearly 990K reactions; the official account commented",
      caveat: "The numbers belong to the creator's video, not the brand's; US case.",
      takeaway: "When a customer's invented hack goes viral, the brand's official account drops a casual, non-promotional comment under the video and its remixes to share the traffic at very low cost, then decides whether to make it a limited item.",
    },
  },
  "tt-30-account-embrace-creator-meme": {
    question: "Has any creator or customer misread or misused your brand or product name and turned it into a meme?",
    placeholder: "e.g. Everyone pronounces our “沐光 (Mùguāng)” as “木瓜 (Mùguā, papaya)”",
    inputs: { topic: { label: "How it was misread + who started it" } },
    source: {
      short: "Vaseline renamed itself “Baseline” to play along",
      metric: "Creator's TikTok video: 4.6 million views, 625.5K likes",
      caveat: "The numbers belong to the creator's video; the brand's own response videos got only “millions of views.”",
      takeaway: "When a creator accidentally mispronounces the brand name and goes viral, the brand immediately acknowledges and amplifies it: rename the official account, give the creator a joke title, and invite fans to remix under the new name, which earns buzz faster than a made ad.",
    },
  },
  "tt-30-live-auction-trust": {
    question: "What high-priced or authenticity-sensitive items do you sell? How many in this session?",
    placeholder: "e.g. 12 pre-owned designer bags / 8 pairs of limited sneakers",
    inputs: { topic: { label: "Category + number of items this session" } },
    source: {
      short: "UK TikTok Shop livestream auctions (Lux Laces and others)",
      metric: "Lux Laces first livestream sold £30,000; over £100,000 revenue in the first month",
      caveat: "UK case; TikTok official press release, and the first livestream's date isn't stated.",
      takeaway: "Show rare or pre-owned items one by one with details and flaws, then use timed auctions to create a rush, so trust converts directly into sales; the schedule grew from 2–3 sessions a week to daily.",
    },
  },
  "tt-30-live-daily-show": {
    question: "What time slot can you stream at every day? Who is the host?",
    placeholder: "e.g. Every night at 9 pm / Store manager and a senior staff member take turns",
    inputs: { topic: { label: "Fixed time slot + host" } },
    source: {
      short: "Fashionphile daily TikTok livestream show",
      metric: "94% of US TikTok Shop pre-owned luxury revenue comes from livestreams; category GMV up 400% year over year",
      caveat: "US case; the numbers are for the whole category, not a single brand's single session.",
      takeaway: "Turn livestreams into a named show with a fixed time slot, where the host states each item's condition and flaws and calls out regulars, so the comments become a community of regulars.",
    },
  },
  "tt-30-script-character-scorecard": {
    question: "What can your expertise “score”? Which kind of familiar character do you want to use?",
    placeholder: "e.g. Rate cartoon characters' breakfasts as a dietitian / Rate houses in animation as a real-estate agent",
    inputs: { topic: { label: "Your expert scoring framework + character type" } },
    source: {
      short: "EMOLVA “Rating business skills with anime characters” series",
      metric: "A single video passed 1 million views",
      caveat: "Japanese case; a press release from the company itself, and the video's upload date wasn't found.",
      takeaway: "Use a familiar character as the vehicle for a fixed professional framework with scores and a verdict (hire or not), so you can mass-produce a series by swapping the character.",
    },
  },
  "tt-30-topic-local-contest-kickoff": {
    question: "Are you opening a new account or running an anniversary event? Is there a local group or staff who can demo?",
    placeholder: "e.g. Shop's 10th anniversary / A nearby junior high dance club is willing to film with us",
    inputs: { topic: { label: "Occasion + local group or staff who can demo" } },
    source: {
      short: "Iruma City “緑翠プロジェクト (Ryokusui Project)”",
      metric: "Passed 130K total views within 10 days of launch",
      caveat: "Japanese local government; the numbers are small, and it's a press release from the government itself.",
      takeaway: "A new account first has real locals demo a song and a dance (with rehearsal behind-the-scenes), then runs a cover contest with real prizes so people film their own, which gives the account UGC from a cold start.",
    },
  },
  "tt-30-copy-founder-number-story": {
    question: "What are your starting and current numbers? Which setback can you tell?",
    placeholder: "e.g. Started with one food cart, now three shops / Nearly closed in year one",
    inputs: { topic: { label: "Starting number + current number + one setback" } },
    source: {
      short: "女子麥麵包 (Nüzi Mai Bakery) founder story series",
      metric: "Founder story series has over 1 million cumulative views",
      caveat: "Taiwanese case; 1 million is the series total, it isn't confirmed as a recent hit, and it comes from a platform press release.",
      takeaway: "Open the series with a number contrast like “from NT$2,000 to NT$18 million in annual revenue,” then follow with a real setback or product-development behind-the-scenes each episode, ending with a holiday product or course.",
    },
  },
};

export const VARIANT_LABEL_EN: VariantLabelEnMap = {
  "懸念": "Suspense",
  "反差": "Contrast",
  "直球": "Straight shot",
  "教學型": "How-to",
  "故事型": "Story",
  "反差型": "Contrast",
  "標準": "Standard",
  "極簡": "Minimal",
  "強調式": "Emphasis",
  "一秒變身": "One-second flip",
  "借位錯覺": "Forced-perspective illusion",
  "倒放回原": "Reverse to original",
  "製作過程": "Making process",
  "整理復原": "Tidy-up restore",
  "組裝完成": "Assembly complete",
  "多品項快切": "Multi-item quick cuts",
  "情境輪播": "Scene rotation",
  "安靜→爆點": "Quiet → burst",
  "細節拉到全景": "Detail to wide shot",
  "一鏡到底走位": "One-take tracking shot",
  "數量堆疊": "Quantity stack",
  "第一次使用": "First use",
  "旁人被吸引": "Bystanders drawn in",
  "素人真實回饋": "Real feedback from regular people",
  "專家定位": "Expert positioning",
  "個性風格": "Personality style",
  "結果導向": "Results-driven",
  "fyp 大流量": "FYP high traffic",
  "精準利基": "Precise niche",
  "趨勢搭便車": "Trend riding",
  "共鳴反應": "Relatable reaction",
  "專業補充": "Expert add-on",
  "反差吐槽": "Contrast roast",
  "產業共鳴版": "Industry-relatable",
  "反差版": "Contrast",
  "教育型": "Educational",
  "同感式": "Empathetic",
  "幽默式": "Humorous",
  "反問式": "Counter-question",
  "互動": "Interactive",
  "質感特寫": "Texture close-up",
  "情境使用": "In-use scene",
  "材質特寫": "Material close-up",
  "開箱瞬間": "Unboxing moment",
  "共鳴": "Relatable",
  "分鏡完整版": "Full storyboard",
  "睡前場景": "Bedtime scene",
  "日常場景": "Daily scene",
  "接力版": "Relay",
  "雙人對打版": "Two-host duel",
  "顧客上場版": "Customer on camera",
  "自嘲版": "Self-deprecating",
  "對嗆版": "Banter back",
  "擺爛版": "Deadpan slacker",
  "續拍版": "Continuation",
  "致敬版": "Tribute",
  "回禮版": "Give-back",
  "地標版": "Landmark",
  "倒數版": "Countdown",
  "戰報版": "Results report",
  "員工線": "Staff series",
  "流行格式線": "Trend-format series",
  "覆盤版": "Weekly review",
  "朋友口吻": "Friendly tone",
  "驚訝口吻": "Surprised tone",
  "試吃預告": "Tasting teaser",
  "改名版": "Rename",
  "封頭銜版": "Joke title",
  "二創版": "Remix",
  "驗貨版": "Inspection",
  "競標版": "Auction",
  "班表版": "Schedule",
  "節目版": "Show format",
  "熟客版": "Regulars",
  "主題輪替版": "Theme rotation",
  "錄用判決": "Hire verdict",
  "買不買判決": "Buy verdict",
  "住不住判決": "Live-here verdict",
  "示範先行": "Demo first",
  "比賽先行": "Contest first",
  "NG 花絮先行": "Outtakes first",
  "起點集": "Starting point episode",
  "卡關集": "Setback episode",
  "轉折集": "Turning point episode",
};
