import type { TaskEnMap, VariantLabelEnMap } from "./types";

export const TASK_EN: TaskEnMap = {
  // ── quickTaskYT.ts ──
  "yt-30-title-strategies": {
    question: "Paste a video URL (auto-read) or describe the video topic",
    placeholder: "https://youtu.be/...  or  video topic",
    inputs: { topic_or_url: { label: "Video URL or topic" } },
  },
  "yt-30-thumbnail-text": {
    question: "Paste a video URL or describe the video topic",
    placeholder: "https://youtu.be/...  or  video topic",
    inputs: { topic_or_url: { label: "Video URL or topic" } },
  },
  "yt-30-description-seo": {
    question: "Paste a video URL (auto-read) or describe the video topic",
    placeholder: "https://youtu.be/...  or  video topic",
    inputs: { topic_or_url: { label: "Video URL or topic" } },
  },
  "yt-30-chapter-timeline": {
    question: "Paste a YouTube video URL (captions are fetched automatically)",
    inputs: { url: { label: "Video URL" } },
  },
  "yt-30-shorts-script": {
    question: "What should the Short be about? A video URL or a topic both work",
    placeholder: "https://youtu.be/...  or  Shorts topic",
    inputs: { topic_or_url: { label: "Shorts topic or long-video URL" } },
  },
  "yt-30-opening-hook": {
    question: "Video URL or topic",
    placeholder: "https://youtu.be/...  or  video topic",
    inputs: { topic_or_url: { label: "Video URL or topic" } },
  },
  "yt-30-end-cta": {
    question: "Video topic / what do you want viewers to do?",
    placeholder: "e.g. Watch the next episode / subscribe / comment / click the product link",
    inputs: { intent: { label: "Action to prompt at the end" } },
  },
  "yt-30-comment-reply": {
    question: "Paste the original comment + the attitude you want to show",
    placeholder: "Paste the whole comment",
    inputs: { user_comment: { label: "Viewer comment" } },
  },
  "yt-30-pinned-comment": {
    question: "Video URL or topic (the hook comment is written from the content)",
    placeholder: "https://youtu.be/...  or  video topic",
    inputs: { topic_or_url: { label: "Video URL or topic" } },
  },
  "yt-30-community-post": {
    question: "What do you want to say on the Community tab today?",
    placeholder: "e.g. Next episode teaser / ask fans what they want to see / behind the scenes",
    inputs: { topic: { label: "Post topic" } },
  },
  "yt-30-shorts-clip": {
    question: "What should the opening shot of this Short show?",
    placeholder: "e.g. Close-up of the product's texture in natural light / the steam of a pour-over coffee",
    inputs: { scene_desc: { label: "Opening scene description" } },
  },
  "yt-30-live-test-demo": {
    question: "Which of your specs can you demonstrate live?",
    placeholder: "e.g. Waterproof enough to soak for 24 hours / steering precise enough to walk a tightrope",
    inputs: { topic: { label: "Spec to prove" } },
    source: {
      short: "Volvo Trucks \"Epic Split\"",
      metric: "6.5M views on day one, 59M+ total",
      takeaway: "Turn the spec into a risky live test: viewers watch to see if it fails, and the spec is just the condition for failure.",
    },
  },
  "yt-30-premiere-countdown-room": {
    question: "What will this premiere show? What shared language do your fans have?",
    placeholder: "e.g. Product launch / behind-the-scenes documentary; the phrase fans will spam",
    inputs: { topic: { label: "Premiere content + fans' shared language" } },
    source: {
      short: "BTS \"Butter\" YouTube premiere",
      metric: "3.9M concurrent viewers, Guinness World Record",
      takeaway: "A premiere's value is in \"at the same time\": run the countdown chat as part of the show so people arrive on time instead of catching up later.",
    },
  },
  "yt-30-watch-mirror-test": {
    question: "What do your customers misjudge about themselves that you can prove to them?",
    placeholder: "e.g. Think they can't choose well / think they need the pricier one",
    inputs: { topic: { label: "Customers' misjudgment of themselves" } },
    source: {
      short: "Dove \"Real Beauty Sketches\"",
      metric: "50M+ views in 12 days, 3.7M shares",
      takeaway: "The most shared long videos aren't about the brand; they let people discover on camera that they were wrong, with the gap revealed by a third party and the brand only designing the setup.",
    },
  },
  "yt-30-shorts-sound-brand": {
    question: "What fixed sound could your brand have?",
    placeholder: "e.g. How a slogan is pronounced / a can-opening sound / a three-note melody",
    inputs: { topic: { label: "Sound element you can repeat" } },
    source: {
      short: "e.l.f. \"#eyeslipsface\"",
      metric: "1B plays in 6 days, the fastest ever at the time",
      takeaway: "Make the memory hook in short video the sound: the visual gets swiped away, the sound stays in the ear, and remakes carry your brand automatically.",
    },
  },
  "yt-30-storyboard-one-take": {
    question: "What in your workplace can be filmed walking all the way through?",
    placeholder: "e.g. Walking from the warehouse to the shipping dock / from prep to serving",
    inputs: { topic: { label: "Workplace route you can walk end to end" } },
    source: {
      short: "Dollar Shave Club",
      metric: "12,000 orders in 48 hours; website overwhelmed in the first hour",
      takeaway: "A one-take shot forces you to speak clearly: there is no editing to hide behind, and failing to finish means you hadn't thought it through; viewers also know it can't be faked.",
    },
  },
  "yt-30-thumbnail-one-object": {
    question: "What is the most unusual shot in this video?",
    placeholder: "e.g. An egg / an empty shelf / a handwritten note",
    inputs: { topic: { label: "Most unusual shot in the video" } },
    source: {
      short: "World Record Egg",
      metric: "52M+ likes, the most ever on Instagram at the time",
      takeaway: "A thumbnail's competitor isn't other thumbnails but the scrolling finger: the emptier the frame and the bigger the subject, the more it looks like a mistake and the more people stop.",
    },
  },
  "yt-30-community-cliffhanger": {
    question: "What upcoming channel decision could viewers take part in?",
    placeholder: "e.g. What to film next / whether to pause a series / whether to change the intro",
    inputs: { topic: { label: "Something you can leave to viewers to decide" } },
    source: {
      short: "Duolingo \"Death of Duo\"",
      metric: "1.7B organic impressions in two weeks",
      takeaway: "A community post isn't a notice board but a way to hand some of the channel's decisions to viewers: people come back for the result of a vote they cast.",
    },
  },
  "yt-30-videocard-single-action": {
    question: "What do you want viewers to do mid-video?",
    placeholder: "e.g. Jump to the tools page / claim the file / watch the previous episode",
    inputs: { topic: { label: "The one thing viewers should do mid-video" } },
    source: {
      short: "Coinbase QR ad",
      metric: "20M+ scans within a minute; the official app crashed for about an hour",
      takeaway: "The info card competes with the video for the same eyes: while the card shows, the visuals and narration must pause and give way, or no one will click.",
    },
  },

  // ── quickTaskYT60.ts ──
  "yt-60-video-package": {
    question: "Video topic / selling point?",
    placeholder: "e.g. Tutorial / unboxing / review",
    inputs: { topic: { label: "Video topic" } },
  },
  "yt-60-shorts-script": {
    question: "Shorts topic?",
    placeholder: "Tutorial / contrast / reveal",
    inputs: { topic: { label: "Shorts topic" } },
  },
  "yt-60-thumbnail-suite": {
    question: "Video topic / what should the thumbnail convey?",
    placeholder: "Video topic or key visual",
    inputs: { topic: { label: "Thumbnail topic" } },
  },
  "yt-60-series-3ep": {
    question: "What topic do you want to make a series about?",
    placeholder: "Tutorial series / story series / review series",
    inputs: { story_topic: { label: "Series topic" } },
  },
  "yt-60-community-post": {
    question: "What should the Community post convey?",
    placeholder: "New video teaser / interactive Q&A / behind the scenes",
    inputs: { topic: { label: "Community topic" } },
  },
  "yt-60-viral-rewrite": {
    question: "Paste the viral video's title / link / topic",
    placeholder: "Original viral title / URL / topic",
    inputs: {
      viral_source: { label: "Viral original / link" },
      brand_angle: { label: "Brand angle" },
    },
  },
  "yt-60-storyboard": {
    question: "Paste a script, or describe the video topic",
    placeholder: "Paste an existing script, or describe the video topic and let AI plan it from scratch",
    inputs: { topic_or_script: { label: "Script or video topic" } },
  },

  // ── quickTaskLI.ts ──
  "li-30-insight-post": {
    question: "What professional insight do you want to share today?",
    placeholder: "e.g. 3 takeaways after using AI tools for 6 months",
    inputs: { topic: { label: "Topic / view" } },
  },
  "li-30-hook-3": {
    question: "Post topic?",
    placeholder: "e.g. Optimizing B2B SaaS marketing costs",
    inputs: { topic: { label: "Topic" } },
  },
  "li-30-article-opener": {
    question: "What do you want to discuss in this article?",
    placeholder: "e.g. Why 70% of digital transformations fail",
    inputs: { topic: { label: "Article topic" } },
  },
  "li-30-poll": {
    question: "What do you want to ask your industry?",
    placeholder: "e.g. B2B marketing KPIs / remote work efficiency",
    inputs: { topic: { label: "Question area" } },
  },
  "li-30-event-invite": {
    question: "Event topic / time / audience?",
    placeholder: "e.g. \"B2B SaaS Growth\" online talk, 6/15 19:00",
    inputs: { event: { label: "Event details" } },
  },
  "li-30-dm-intro": {
    question: "Who do you want to connect with? What for?",
    placeholder: "Their role + what you want to do (collaborate / ask advice / introduce yourself)",
    inputs: { context: { label: "Person + purpose" } },
  },
  "li-30-comment": {
    question: "Paste the original post / describe its content",
    placeholder: "The other person's post content",
    inputs: { context: { label: "Original post" } },
  },
  "li-30-headline": {
    question: "What do you do? Who do you want to attract?",
    placeholder: "Your role + who you want to attract (potential partners / clients / peers)",
    inputs: { context: { label: "Role + audience" } },
  },
  "li-30-newsletter": {
    question: "What is this issue of the newsletter about?",
    placeholder: "This issue's topic",
    inputs: { topic: { label: "This issue's topic" } },
  },
  "li-30-document": {
    question: "What do you want the document to teach / explain?",
    placeholder: "e.g. 5 common mistakes in the B2B funnel",
    inputs: { topic: { label: "Document topic" } },
  },
  "li-30-feed-cost-of-stance": {
    question: "What do you do that you know costs you revenue?",
    placeholder: "e.g. Declining a type of project / using pricier materials / refusing rush surcharges",
    inputs: { topic: { label: "Something you do despite knowing it costs revenue" } },
    source: {
      short: "Patagonia \"Don't Buy This Jacket\"",
      metric: "Revenue grew about 30% the next year to $543M",
      takeaway: "B2B trust isn't built on claims but on how much you paid for them: put the cost in numbers and the claim stops being rhetoric.",
    },
  },
  "li-30-article-own-the-failure": {
    question: "What was your most recent mistake, and how did you handle it?",
    placeholder: "e.g. Shipment delayed three weeks / system outage / quality batch issue",
    inputs: { topic: { label: "The mistake + how it was handled" } },
    source: {
      short: "KFC \"FCK\"",
      metric: "700+ articles, reach of about 797M people",
      takeaway: "A public post-mortem spreads because it's rare: admit fault first, lower defenses with self-mockery, then give a concrete fix, and the wrong order turns it into a PR statement.",
    },
  },
  "li-30-document-proof-deck": {
    question: "What examples can you collect to prove the point you want to make?",
    placeholder: "e.g. Answers from 50 customers asked the same question",
    inputs: { topic: { label: "Examples you can collect + the point to prove" } },
    source: {
      short: "Heinz \"Draw Ketchup\"",
      metric: "$5.8M in earned media, 127x the media spend",
      takeaway: "A deck's strongest slides aren't the conclusion but the ones that let people count their way to it: show the samples first, and the conclusion comes last and only once.",
    },
  },
  "li-30-newsletter-referral-loop": {
    question: "Which section of your newsletter would readers want to forward to colleagues?",
    placeholder: "e.g. One data chart per issue / an insider story",
    inputs: { topic: { label: "The section readers would want to forward" } },
    source: {
      short: "Morning Brew referral program",
      metric: "Subscribers grew from 100K to 4.5M; acquired in 2020 for $75M",
      takeaway: "Subscriber growth comes from giving readers a reason to forward: make the most shareable section a standalone block, then reward the person who forwards it.",
    },
  },
  "li-30-poll-public-wager": {
    question: "What will you do depending on the poll result?",
    placeholder: "e.g. Make internal training materials public if it passes 500 votes",
    inputs: { topic: { label: "What you'll deliver based on the poll result" } },
    source: {
      short: "Wendy's × Carter Wilkerson",
      metric: "3.4M retweets, the most ever at the time",
      takeaway: "Poll turnout is low because there are no consequences: tie a condition you'll truly honor to the vote count, and voting becomes participation instead of a stance.",
    },
  },

  // ── quickTaskX.ts ──
  "x-30-hot-take": {
    question: "What do you want to claim on X? Include your reasons.",
    placeholder: "e.g. We don't run limited-time discounts. Discounts train customers to wait for sales, which hurts those willing to pay full price",
    inputs: { context: { label: "Claim and reasons" } },
  },
  "x-30-data-hook": {
    question: "What number do you want to share? What does it mean?",
    placeholder: "e.g. Our repurchase rate is 43%. The industry average is 18%. The difference is that we handwrite a card for every order",
    inputs: { context: { label: "The number and its meaning" } },
  },
  "x-30-build-in-public": {
    question: "What did you do this week? What didn't go to plan?",
    placeholder: "e.g. Launched new packaging, but the first batch's damage rate went up because the thinner box (0.3mm less) couldn't hold",
    inputs: { context: { label: "Progress and surprises" } },
  },
  "x-30-industry-reply": {
    question: "Which industry topic do you want to respond to? What's your angle?",
    placeholder: "e.g. Everyone's discussing shipping price hikes. We want to say why we'd rather absorb the cost than switch to thinner packaging",
    inputs: { context: { label: "Topic and your angle" } },
  },
  "x-30-launch": {
    question: "What are you announcing? What does it solve for users?",
    placeholder: "e.g. Restock notifications are live. Before, out-of-stock meant checking back yourself; now leave an email and we'll notify you",
    inputs: { context: { label: "What launched and the problem it solves" } },
  },
  "x-30-tip": {
    question: "What practice do you want to teach? Who will find it useful?",
    placeholder: "e.g. How to tell if skincare needs refrigeration. Just check whether the ingredient list has vitamin C derivatives",
    inputs: { context: { label: "The tip and who it's for" } },
  },
  "x-30-thread-howto": {
    question: "What will you teach? What result will readers get when done?",
    placeholder: "e.g. How to pick a chair for long sitting. After reading, they can judge in the store without listening to sales pitches",
    inputs: { context: { label: "Topic and the result when done" } },
  },
  "x-30-thread-story": {
    question: "Which stretch of events will you tell? What was the turning point?",
    placeholder: "e.g. Switched suppliers to cut costs, complaints rose, and in the end it cost more than before",
    inputs: { context: { label: "What happened and the turning point" } },
  },
  "x-30-thread-teardown": {
    question: "What will you tear down? What conclusion do you want to prove?",
    placeholder: "e.g. Tear down a best-selling competitor's product page, to prove it wins by putting the return policy at the top",
    inputs: { context: { label: "Teardown subject and conclusion" } },
  },
  "x-30-thread-listicle": {
    question: "What list will you make? Who is it for?",
    placeholder: "e.g. List 5 ways first-time online store owners waste money, for people about to open a store",
    inputs: { context: { label: "List topic and reader" } },
  },
};

export const VARIANT_LABEL_EN: VariantLabelEnMap = {
  // YT 30s
  "SEO 友善": "SEO-friendly",
  "反差 + 數字": "Contrast + numbers",
  "懸念式": "Suspense",
  "大字震撼型": "Bold big text",
  "人臉表情型": "Face expression",
  "對比拼貼型": "Contrast collage",
  "關鍵字密集型": "Keyword-dense",
  "故事敘述型": "Storytelling",
  "清單導向型": "List-driven",
  "精簡 5 章": "Concise, 5 chapters",
  "標準 8 章": "Standard, 8 chapters",
  "細緻 12 章": "Detailed, 12 chapters",
  "教學型": "Tutorial",
  "故事型": "Story",
  "反差型": "Contrast",
  "數字 / 反差": "Numbers / contrast",
  "直球觀點": "Straight take",
  "訂閱導向": "Subscribe-focused",
  "下集導向": "Next-episode-focused",
  "留言互動導向": "Comment-focused",
  "溫暖式": "Warm",
  "幽默式": "Humorous",
  "深度回應": "In-depth reply",
  "提問式": "Question",
  "補充式": "Add-on",
  "反差式": "Contrast",
  "純文字觀點": "Text-only take",
  "民調型": "Poll",
  "預告倒數型": "Teaser countdown",
  "質感特寫": "Texture close-up",
  "情境動態": "In-context motion",
  "實測版": "Live test",
  "對照組版": "Control group",
  "素人挑戰版": "Everyday-people challenge",
  "倒數版": "Countdown",
  "解謎版": "Puzzle",
  "應援版": "Fan cheer",
  "雙描述版": "Dual description",
  "盲測版": "Blind test",
  "時間差版": "Time gap",
  "原創旋律版": "Original melody",
  "招牌音效版": "Signature sound",
  "口號節奏版": "Slogan rhythm",
  "動線版": "Walkthrough",
  "交接版": "Handoff",
  "逆向版": "Reverse",
  "單一主體版": "Single subject",
  "反常版": "Unusual",
  "留白版": "Negative space",
  "投票版": "Vote",
  "求救版": "Call for help",
  "公開帳本版": "Open ledger",
  "停頓版": "Pause",
  "懸念版": "Suspense",
  "補完版": "Completion",
  // YT 60s
  "教學版": "Tutorial",
  "故事版": "Story",
  "數據版": "Data",
  "對比版": "Contrast",
  "反差版": "Contrast",
  "揭密版": "Reveal",
  "節奏版": "Rhythm",
  "數字式": "Numbers",
  "反問式": "Rhetorical question",
  "誇張式": "Exaggerated",
  "第 1 集": "Episode 1",
  "第 2 集": "Episode 2",
  "第 3 集": "Episode 3",
  "投票式": "Poll",
  "圖片式": "Image",
  "文字式": "Text",
  "問答式": "Q&A",
  "預告式": "Teaser",
  "保結構式": "Structure-preserving",
  "情感放大式": "Emotion-amplified",
  "數據式": "Data-driven",
  "故事式": "Story-driven",
  "分鏡完整版": "Full storyboard",
  // LI
  "反共識": "Contrarian",
  "數據驅動": "Data-driven",
  "個人故事": "Personal story",
  "數據反差": "Data contrast",
  "場景式": "Scene-setting",
  "個人連結": "Personal connection",
  "重點預告": "Key points preview",
  "策略選擇": "Strategic choice",
  "經驗分歧": "Divergent experiences",
  "未來預測": "Future prediction",
  "專業敘述": "Professional",
  "故事邀請": "Story invite",
  "稀缺感": "Scarcity",
  "求教式": "Ask for advice",
  "共同點": "Common ground",
  "價值交換": "Value exchange",
  "補充經驗": "Add experience",
  "不同觀點": "Different view",
  "提問擴展": "Question to expand",
  "職稱+價值": "Title + value",
  "結果型": "Results-driven",
  "個性型": "Personality-driven",
  "故事性": "Storytelling",
  "問題式": "Question-driven",
  "教學清單型": "How-to list",
  "數字版": "Numbers",
  "拒絕清單版": "Decline list",
  "時間軸版": "Timeline",
  "根因版": "Root cause",
  "賠償版": "Compensation",
  "樣本版": "Samples",
  "對照版": "Comparison",
  "時間序版": "Chronological",
  "轉寄誘因版": "Forwarding incentive",
  "專屬解鎖版": "Exclusive unlock",
  "共同署名版": "Co-signed",
  "門檻版": "Threshold",
  "二選一版": "Either-or",
  "公開挑戰版": "Public challenge",
  // X
  "直說版": "Straight-up",
  "代價版": "Cost",
  "落差版": "Gap",
  "時間版": "Time",
  "換算版": "Conversion",
  "單次版": "Single instance",
  "可借用版": "Borrowable",
  "實務版": "Practical",
  "被影響的人版": "Affected people",
  "長期版": "Long-term",
  "情境版": "Scenario",
  "一句版": "One-liner",
  "直接教版": "Direct how-to",
  "破除誤解版": "Myth-busting",
  "踩坑版": "Pitfalls",
  "教學串": "How-to thread",
  "敘事串": "Narrative thread",
  "拆解串": "Teardown thread",
  "清單串": "Listicle thread",
};
