/**
 * squadSearchRouter — server-side semantic search for squads.
 *
 * GET /api/squads/search?q=<query>[&limit=20][&threshold=0.22]
 *
 * Pipeline:
 *  1. Vectorise the user query via Azure Embedding (text-embedding-3-large)
 *  2. Load all squad embeddings from squads.embedding column (in-process
 *     cache, 5-minute TTL — safe for 699 squads × ~4 MB of floats)
 *  3. Compute cosine similarity for all squads
 *  4. Return top-N squads ordered by similarity score (highest first)
 *
 * Fallback: when embedding API is unavailable or embedding column is empty,
 * falls back to a MySQL full-text LIKE search so the UI always gets results.
 *
 * Note: squad embeddings are generated by
 *   scripts/compute-squad-embeddings.ts (run via admin-embed-squads.yml)
 * and stored in squads.embedding (LONGTEXT, JSON array of floats).
 */

import { Router } from "express";
import localPool from "../localDb.js";
import { getEmbedding, cosineSimilarity } from "../_core/embedding.js";

export const squadSearchRouter = Router();

// ── In-process embedding cache ────────────────────────────────────────────────

interface CachedEmbed {
  squadId: number;
  slug: string;
  embedding: number[];
}

let embedCache: CachedEmbed[] = [];
let cacheLoadedAt = 0;
const CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

async function getEmbedCache(): Promise<CachedEmbed[]> {
  if (Date.now() - cacheLoadedAt < CACHE_TTL_MS && embedCache.length > 0) {
    return embedCache;
  }
  try {
    const [rows]: any = await localPool.execute(
      "SELECT id, slug, embedding FROM squads WHERE is_active = 1 AND embedding IS NOT NULL"
    );
    embedCache = rows
      .map((r: any) => {
        try {
          const vec =
            typeof r.embedding === "string"
              ? JSON.parse(r.embedding)
              : r.embedding;
          return Array.isArray(vec)
            ? { squadId: Number(r.id), slug: String(r.slug), embedding: vec as number[] }
            : null;
        } catch {
          return null;
        }
      })
      .filter(Boolean) as CachedEmbed[];
    cacheLoadedAt = Date.now();
    console.log(`[squadSearch] cache loaded: ${embedCache.length} squad embeddings`);
  } catch (e) {
    console.warn("[squadSearch] embedCache load failed:", e);
  }
  return embedCache;
}

// Warm cache at module load (non-blocking — ignore errors)
getEmbedCache().catch(() => {});

// ── Fallback: MySQL full-text LIKE search ────────────────────────────────────

async function fallbackSearch(q: string, limit: number): Promise<number[]> {
  const tokens = q
    .trim()
    .toLowerCase()
    .split(/[\s,、，;:]+/)
    .filter((t) => t.length >= 2)
    .slice(0, 8);
  if (tokens.length === 0) return [];

  const likes = tokens.map(
    () => `(name LIKE ? OR name_zh LIKE ? OR slug LIKE ? OR description LIKE ?)`
  );
  const params: string[] = tokens.flatMap((t) => [
    `%${t}%`, `%${t}%`, `%${t}%`, `%${t}%`,
  ]);
  const sql = `
    SELECT id FROM squads
     WHERE is_active = 1
       AND (${likes.join(" OR ")})
     LIMIT ${Math.min(limit, 50)}
  `;
  try {
    const [rows]: any = await localPool.execute(sql, params);
    return rows.map((r: any) => Number(r.id));
  } catch {
    return [];
  }
}

// ── Shared: fetch full squad rows by ordered IDs ────────────────────────────

const SQUAD_FIELDS = `
  id, slug, name, name_zh, description, description_zh,
  strategy_layer, mockup_platform, mockup_format,
  task_label_zh, task_label_en, output_kind, is_curated,
  workspace, tags
`;

async function fetchSquadsByIds(orderedIds: number[]): Promise<any[]> {
  if (orderedIds.length === 0) return [];
  const placeholders = orderedIds.map(() => "?").join(",");
  const [rows]: any = await localPool.execute(
    `SELECT ${SQUAD_FIELDS} FROM squads WHERE is_active = 1 AND id IN (${placeholders})`,
    orderedIds
  );
  // Re-order to preserve score order (MySQL IN() doesn't guarantee it)
  const rowMap = new Map(rows.map((r: any) => [Number(r.id), r]));
  return orderedIds.map((id) => rowMap.get(id)).filter(Boolean);
}

// ── Main search route ─────────────────────────────────────────────────────────

squadSearchRouter.get("/", async (req, res) => {
  const q = String(req.query.q ?? "").trim();
  const limit = Math.min(Number(req.query.limit ?? 20), 50);
  const threshold = Number(req.query.threshold ?? 0.22);

  if (q.length < 2) {
    return res.json({ hits: [], mode: "empty", query: q });
  }

  try {
    // 1. Vectorise query via Azure
    const queryVec = await getEmbedding(q);

    if (!queryVec) {
      // Embedding API unavailable → LIKE fallback
      const ids = await fallbackSearch(q, limit);
      const rows = await fetchSquadsByIds(ids);
      return res.json({
        hits: rows,
        mode: ids.length ? "fallback-like" : "fallback-empty",
        query: q,
      });
    }

    // 2. Load embedding cache
    const cache = await getEmbedCache();

    if (cache.length === 0) {
      // No embeddings generated yet → LIKE fallback
      const ids = await fallbackSearch(q, limit);
      const rows = await fetchSquadsByIds(ids);
      return res.json({
        hits: rows,
        mode: ids.length ? "no-embeddings-like" : "no-embeddings-empty",
        query: q,
      });
    }

    // 3. Cosine similarity against all cached embeddings
    const scored = cache
      .map(({ squadId, embedding }) => ({
        squadId,
        score: cosineSimilarity(queryVec, embedding),
      }))
      .filter((s) => s.score >= threshold)
      .sort((a, b) => b.score - a.score)
      .slice(0, limit);

    if (scored.length === 0) {
      return res.json({ hits: [], mode: "semantic-empty", query: q });
    }

    // 4. Fetch full squad rows (score-ordered)
    const rows = await fetchSquadsByIds(scored.map((s) => s.squadId));
    const scoreMap = new Map(scored.map((s) => [s.squadId, s.score]));
    const hits = rows.map((r) => ({ ...r, _score: scoreMap.get(Number(r.id)) ?? 0 }));

    return res.json({ hits, mode: "semantic", query: q });
  } catch (e: any) {
    console.error("[squadSearch] error:", e?.message);
    return res.status(500).json({ error: "search failed", detail: e?.message });
  }
});
